Integrate the IBC relayer and Gaia chain into the crust
CoreumFoundation/crust pull request #136
Opened 2022-11-09 07:34 UTC by dzmitryhil

2022-11-09 07:39 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/znet/mode.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGQJu8QBpJE8JVMC15b:-NGQJu8QBpJE8JVMC15c:b-vxbtly) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/pkg/znet/mode.go#L44)):*
> ```Go
> // DevMode is the environment for developer
> func DevMode(appF *apps.Factory) infra.Mode {
> 	coredApp, coredNodes, err := appF.CoredNetwork("coredev", cored.DefaultPorts, 1, 0)
> ```

@wojtek-coreum  why do we have the "coredev" here as a name but other names are original without the prefixes, and the same for the TestMode ?


<!-- Sent from Reviewable.io -->

2022-11-09 12:21 UTC, wojtek-coreum requested changes
> Reviewed 17 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 30 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/gaia/image.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRDdD4BElViiDmXN-q:-NGRDdD57dL7CUIU85Bg:bh68lwf) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/build/gaia/image.go#L38)):*
> ```Go
> 	return docker.BuildImage(ctx, docker.BuildImageConfig{
> 		ContextDir: gaiaLocalPath,
> 		ImageName:  artifactNames[0],
> ```

Instead of overriding `--entrypoint` when docker is started you may just store that script in `/bin/gaia` but as mentioned in other comments I don't like the idea of this way of configuring gaia. I would prefer to mount a directory containing all the required config like we do for cored.
___
*[`infra/apps/cored/cored.go` line 310 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRGJJS40qMcC6O5KFm:-NGRGJJT9j-mVGA0rWzJ:b6feqwo) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/cored/cored.go#L310)):*
> ```Go
> 
> 	if err := importMnemonicsToKeyring(c.config.HomeDir, c.importedMnemonics); err != nil {
> 		return errors.WithStack(err)
> ```

Here and below: `errors.WithStack` should be used when we receive error from not our code for the first time. Here we receive it from our code so stack should already be there.
___
*[`infra/apps/cored/key.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGREh35-zxTeAC6-TS4:-NGREh36EXr79c3_K8I7:bsgqlxg) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/cored/key.go#L16)):*
> ```Go
> 	kr, err := keyring.New("cored", "test", homeDir, nil)
> 	if err != nil {
> 		return err
> ```

errors.WithStack
___
*[`infra/apps/cored/key.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGREjx_EiU5ShX1FSjk:-NGREjx_EiU5ShX1FSjl:bsgqlxg) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/cored/key.go#L21)):*
> ```Go
> 	for name, mnemonic := range mnemonics {
> 		if _, err := kr.NewAccount(name, mnemonic, "", sdk.GetConfig().GetFullBIP44Path(), hd.Secp256k1); err != nil {
> 			return err
> ```

errors.WithStack
___
*[`infra/apps/gaia/gaia.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRBmAD491IhqyIYAaN:-NGRBmAD491IhqyIYAaO:b-9qj9ub) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L34)):*
> ```Go
> 	DefaultAccountPrefix = "cosmos"
> 
> 	dockerEntrypoint = "run.sh"
> ```

This is quite against the original idea where you prepare whatever config you like using go, store it in app's home directory which is then mounted to the image and binary takes config from there. It's much simpler than preparing bash script, putting it into container and then start it in container as a wrapper for original binary.
The idea was to do everything in go to not deal with bash magic. Moreover the process is correctly maintained by the logic in go meaning that if app inside a container was configured and then restarted, config commands are not executed again which might lead to errors e.g. if keys already exist - I mentioned it in another comment too.
___
*[`infra/apps/gaia/gaia.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRJrlABPmJp4i8S6GX:-NGRJrlABPmJp4i8S6GY:bvev7uo) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L38)):*
> ```Go
> 
> // Ports defines ports used by application.
> type Ports struct {
> ```

Do we need all of them? For gaia (we run only one node) we probably need only RPC
___
*[`infra/apps/gaia/gaia.go` line 152 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRKL9d9SJHykuZV12g:-NGRKL9d9SJHykuZV12h:bsgqlxg) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L152)):*
> ```Go
> 	buf := &bytes.Buffer{}
> 	if err := runScriptTemplate.Execute(buf, args); err != nil {
> 		return err
> ```

errors.WithStack
___
*[`infra/apps/gaia/gaia.go` line 155 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRKN0q1ro7wyGZUj3H:-NGRKN0q1ro7wyGZUj3I:b-d0nwfn) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L155)):*
> ```Go
> 	}
> 
> 	err := os.WriteFile(path.Join(g.config.HomeDir, dockerEntrypoint), buf.Bytes(), 0o700)
> ```

maybe `return errors.WithStack(os.WriteFile(...`
___
*[`infra/apps/gaia/run.tmpl` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRD8FhEXAy6uF0_4YL:-NGRD8FhEXAy6uF0_4YM:b-mx911q) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/run.tmpl#L1)):*
> ```
> #!/bin/sh
> ```

how does this script behave when container is restarted?
___
*[`infra/apps/gaia/wallets.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRFiNX1KZBgALurrqr:-NGRFiNY8iQLBduCUYcL:b-w5kdch) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/wallets.go#L1)):*
> ```Go
> package gaia
> ```

What about defining some accounts with `stake` funds to be able to run some tests executing transactions (IBC) on gaia chain? Optimally we could have similar faucet we have on coreum to fund integration tests. Might be a separate task of course.
___
*[`infra/apps/health/cosmos.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRFOcx6Ydo9e_UJFC6:-NGRFOcx6Ydo9e_UJFC7:bvh1ngn) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/health/cosmos.go#L1)):*
> ```Go
> package health
> ```

I would keep `app` directory strictly for apps, and `health` is not an app. Maybe `infra/helpers.go` is a better place? Health-related types are already there
___
*[`infra/apps/relayer/relayer.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRGrzAD7UxK8MHmyPd:-NGRGrzAD7UxK8MHmyPe:b-fcw7dq) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L75)):*
> ```Go
> 
> // Port returns port used by the application.
> func (r Relayer) Port() int {
> ```

I think this method is not required for relayer
___
*[`infra/apps/relayer/relayer.go` line 85 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRHHgu6R-CswvxQFdk:-NGRHHgu6R-CswvxQFdl:bec70k2) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L85)):*
> ```Go
> 
> // HealthCheck checks if relayer is operating.
> func (r Relayer) HealthCheck(ctx context.Context) error {
> ```

I think health checking implemented here is not enough. This function should return `nil` error if and only if the app is fully operable, meaning that integration tests might be started and run without failures. In terms of the relayer it means that handshake on both chains should be completed and relayer should be able to forward transactions. You may compare it to implementation inside `cored` where it is verified that genesis block was mined, meaning that nodes formed the consensus and they process transactions.
___
*[`infra/apps/relayer/relayer.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRImS-CbOtarAif9vX:-NGRImS-CbOtarAif9vY:b4nfd38) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L118)):*
> ```Go
> 		},
> 		Ports: map[string]int{
> 			"server": r.config.DebugPort,
> [...]

2022-11-10 14:44 UTC, wojtek-coreum requested changes
> Reviewed 13 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 24 of 26 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/gaia/gaia.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRJrlABPmJp4i8S6GX:-NGWxhwn-s509qRmShMA:bbikl66) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Who knows. Those are standard that's why they are used. 
</blockquote></details>

so then, we could reuse the same struct for both chains  - gaia and coreum
___
*[`infra/apps/relayer/relayer.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRIWDH8BPfkF1Ftyo0:-NGWzExYEVIvX41Mbhyh:bf0bnk4) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L128)):*
> This path is the pas inside the Alpine container so no need to use the join. It might be even wrong.

I don't get it. This is exactly what you are doing here - you join two paths. This is exactly what `filepath.Join` is for

> The . indicated that it's executable.

Is it required for anything. This is the first time in my life I see this
___
*[`infra/apps/relayer/run.tmpl` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRCOv0EvYrUNXTzXjj:-NGWzePh8yWjXc4FTJWe:b-ozp8ey) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/run.tmpl#L48)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This config is for the development and test, so we don't need to expect the restarts, but just for you I've added the if statement to make it possible to restart the containers.
</blockquote></details>

There is command `znet stop` which stops everything and `znet start` restarts them again so we need to support it (or remove `znet stop`)
___
*[`infra/testing/run.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGWzrVU9P6R1vCgxmme:-NGWzrVU9P6R1vCgxmmf:bgov1zy) ([raw file](https://github.com/coreumfoundation/crust/blob/5ecaa8b24de30361921595f08ff6de74dc12691f/infra/testing/run.go#L38)):*
> ```Go
> 	log := logger.Get(ctx)
> 	log.Info("Waiting until all applications start...")
> 	waitCtx, waitCancel := context.WithTimeout(ctx, 2*time.Minute)
> ```

Does it take so long for relayer to sync?


<!-- Sent from Reviewable.io -->

2022-11-10 16:21 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 24 of 26 files reviewed, 12 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/gaia/gaia.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRJrlABPmJp4i8S6GX:-NGXK_xe7eFw8kFIMBxY:b-2yba6r) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so then, we could reuse the same struct for both chains  - gaia and coreum
</blockquote></details>

They are not the same.
___
*[`infra/apps/relayer/relayer.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRIWDH8BPfkF1Ftyo0:-NGXKe8ZDyarHew1SmIR:b-but723) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> This path is the pas inside the Alpine container so no need to use the join. It might be even wrong.

I don't get it. This is exactly what you are doing here - you join two paths. This is exactly what `filepath.Join` is for

> The . indicated that it's executable.

Is it required for anything. This is the first time in my life I see this
</blockquote></details>

Let's say I use the windows, so the pass will be "folder\folder", and that path will be used in the Linux which is wrong. 
___
*[`infra/apps/relayer/run.tmpl` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRCOv0EvYrUNXTzXjj:-NGXKq91AkhBHg6-AYlL:b2odr8o) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/run.tmpl#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is command `znet stop` which stops everything and `znet start` restarts them again so we need to support it (or remove `znet stop`)
</blockquote></details>

Got you.
___
*[`infra/testing/run.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGWzrVU9P6R1vCgxmme:-NGXKsO7-CoP71rGef4M:brfwypw) ([raw file](https://github.com/coreumfoundation/crust/blob/5ecaa8b24de30361921595f08ff6de74dc12691f/infra/testing/run.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Does it take so long for relayer to sync?
</blockquote></details>

On my machine about 20-30 sec. But on another machine might be more, that's why I set it to 2 min.


<!-- Sent from Reviewable.io -->

2022-11-11 08:11 UTC, wojtek-coreum requested changes
> Reviewed 1 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 25 of 26 files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/gaia/gaia.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRJrlABPmJp4i8S6GX:-NG_jR-ZCKyqmaAnPOrs:bzasubc) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

They are not the same.
</blockquote></details>

List of ports is the same, numbers are different, no?


<!-- Sent from Reviewable.io -->

2022-11-11 08:29 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 25 of 26 files reviewed, 11 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/gaia/gaia.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRJrlABPmJp4i8S6GX:-NG_nSC_AhvKrKcilaU-:bxy7nmh) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

List of ports is the same, numbers are different, no?
</blockquote></details>

Nope, here we use fewer ports. Just the ports needed for peering and tests. For example, we don't need swagger.


<!-- Sent from Reviewable.io -->

2022-11-11 13:25 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 23 of 26 files reviewed, 11 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGQXU2H9z9s8D8ZtXqo:-NGarYVx7TDNom3Lkge4:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/go.mod#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure :-)
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-11-11 13:56 UTC, wojtek-coreum requested changes
> Reviewed 1 of 15 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/gaia/image.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGQ_s8uBKPQhwHZESsE:-NGaxXqwCKfj-R7UXZXH:b-cjq92w) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/build/gaia/image.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get what is the diff. The "tools.PathLocal" just address the bin. That is what is needed here. 
</blockquote></details>

I'm just saying that it is very complex way of writing `filepath.Join("bin", ".cache", "docker", "gaia")`
And `PathLocal` calls `filepath.Abs` internally which fails if path does not exist, which is the case here.
___
*[`build/gaia/image.go` line 17 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGay6dqDA-jC4qAGX3W:-NGay6dqDA-jC4qAGX3X:b5mm6wd) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/gaia/image.go#L17)):*
> ```Go
> 	const binaryName = "gaiad"
> 
> 	gaiaLocalPath := tools.PathLocal(path.Join(".cache", "docker", "gaia"))
> ```

According to other related discussion on path separators on windows and linux, `filepath.Join` should be used here to use correct separator
___
*[`build/tools/tools.go` line 555 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGav5YlAAh84TPPa3q-:-NGav5YlAAh84TPPa3q0:b-y98tax) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L555)):*
> ```Go
> 	}
> 
> 	// validate binaries
> ```

I don't understand the purpose of this code. It verifies that all the installed binaries exist in binaries requested to be copied.
1. I guess it should be checked the other way - if requested binaries exist in the tool config
2. It is not needed completely because if binary does not exist copying will fail anyway
___
*[`build/tools/tools.go` line 559 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGasCSL-__0smzQCMDW:-NGasCSM9yRQOYZXORnQ:bva4fzj) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L559)):*
> ```Go
> 		storedBinaryName := filepath.Base(PathDocker(storedBinaryPath))
> 		if _, ok := requestedBinaryNames[storedBinaryName]; !ok {
> 			return errors.Errorf("The binary %q doesn't exists for the reqiestd tool %q", storedBinaryName, tool)
> ```

lower letter at the beginning of error message
___
*[`build/tools/tools.go` line 559 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGavDIxD8Psy1JpO8vP:-NGavDIxD8Psy1JpO8vQ:b1okt81) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L559)):*
> ```Go
> 		storedBinaryName := filepath.Base(PathDocker(storedBinaryPath))
> 		if _, ok := requestedBinaryNames[storedBinaryName]; !ok {
> 			return errors.Errorf("The binary %q doesn't exists for the reqiestd tool %q", storedBinaryName, tool)
> ```

reqiestd -> requested
___
*[`build/tools/tools.go` line 569 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGaw3vY9Q0SSBC_FoGf:-NGaw3vY9Q0SSBC_FoGg:boztyuz) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L569)):*
> ```Go
> 	}
> 
> 	for storedBinaryPath := range storedBinaries {
> ```

why not to enumerate over `binaryNames`?
___
*[`infra/apps/relayer/relayer.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRIWDH8BPfkF1Ftyo0:-NGawPXO1AUC2q9w-arD:bns3xpn) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's say I use the windows, so the pass will be "folder\folder", and that path will be used in the Linux which is wrong. 
</blockquote></details>

Nowhere in our code we care about windows - it's ignored by definition. But if you insist, you may use `path.Join` which always uses `/`, like you do in other place.


<!-- Sent from Reviewable.io -->

2022-11-15 10:03 UTC, ysv requested changes
> Reviewed 4 of 25 files at r1, 7 of 15 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 21 of 26 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGujZvP2PQYLW6kZErA:-NGujZvP2PQYLW6kZErB:b-yg36ps) (no related file):*
Publishing a first batch of comments

___
___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NGq8jZq59Y86HElZzJb:b2jhuub) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
> ```Go
> 	"images/cored":            coreum.BuildCoredDockerImage,
> 	"images/faucet":           faucet.BuildDockerImage,
> 	"images/gaia":             gaia.BuildDockerImage,
> ```

minor:
shouldn't it be `gaiad` following the logic of `cored` ?
___
*[`build/gaia/image.go` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGrXIVx2-PgjuVYWTyY:-NGrXIW-Caa16EEvy661:b1vibf8) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/gaia/image.go#L9)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum-tools/pkg/build"
> 	"github.com/CoreumFoundation/crust/build/docker"
> 	"github.com/CoreumFoundation/crust/build/docker/basic"
> ```

minor:
I would probably import it as dockerbasic because when you call in code
```
	dockerfile, err := basic.Execute(...)
```
it is not clear what is happening
___
*[`build/tools/tools.go` line 189 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqAJbM0sTjpbBSHWRy:-NGqAJbN2UuPLg2tl0nm:bcvi35r) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L189)):*
> ```Go
> 				Hash: "sha256:893537acd7fa5b5b9f0814f06ce6c26ba3f944262d7a43f5790216350d8399a9",
> 				Binaries: map[string]string{
> 					"bin/relayer": "Cosmos Relayer",
> ```

What is the meaning of "Cosmos Relayer" ?
does it define the name of unarchived/final binary ?
___
*[`build/tools/tools.go` line 536 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGrVDewBE2QybHQkf1W:-NGrVDewBE2QybHQkf1X:b-1h4516) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L536)):*
> ```Go
> // CopyToolBinaries moves the tools artifacts form docker cache to the target local location.
> // In case the binPath doesn't exist the method will create it.
> func CopyToolBinaries(tool Name, path string, binaryNames ...string) error {
> ```

"CopyToolBinaries moves the tools artifacts form docker cache to the target local location."

But as far as I know we copy tools from local path to another local path which is later mounted into docker.
___
*[`build/tools/tools.go` line 559 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGasCSL-__0smzQCMDW:-NGqDnVD5xHodUxQFwU7:bjv3eks) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L559)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

lower letter at the beginning of error message
</blockquote></details>

that is strange that it passed in CI because we have a linter for this (revive rule: error-strings)
And I've tried to make this change locally and linting fails

Any idea what could be wrong with linter in CI ?

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TnWfhWe_dGQmeuiSG5z8vPNP/image.png)

okay I found that with current linter setup capital letter doesn't trigger this linter to fail. While dot does.

I think we should configure this to be handled on linter level 

Another update: it is actually ignored because we use github.com/pkg/errors not errros pkg and revive doesn't support it I think https://github.com/mgechev/revive/issues/697
___
*[`infra/apps/cored/wallets.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqI9tw4fizGiLjJGjJ:-NGqI9tw4fizGiLjJGjK:bqyix54) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/cored/wallets.go#L12)):*
> ```Go
> const (
> 	// FaucetMnemonic is mnemonic used by faucet to broadcast requested transfers.
> 	FaucetMnemonic = "pitch basic bundle cause toe sound warm love town crucial divorce shell olympic convince scene middle garment glimpse narrow during fix fruit suffer honey"
> ```

why do we have it added only now ? 
___
*[`infra/apps/gaia/gaia.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRBmAD491IhqyIYAaN:-NGqIy6u06omtwvb1WZI:b6s2rra) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I've replied about the same above let's keep that decision there. 
</blockquote></details>

lets discuss this one the call
___
*[`infra/apps/gaia/gaia.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqOzXb7pSiva2UZrs6:-NGqOzXc0Ykxh7c2HbUu:bn76esx) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/gaia/gaia.go#L1)):*
> ```Go
> package gaia
> ```

we can stick to gaia for now.
But ideally I would like to make this package generic so we can easily reuse it for starting e.g osmosis chain.
As far as I understand all of them have similar start procedure. Don't they ?

So ideally image name with prebuild binary should be passed `New` func

same applies to `build/gaia` and some other parts I think ideally `gaia` should not be even mentioned in code and everything should be universal 

WDYT @wojtek-coreum @dzmitryhil ?
___
*[`infra/apps/gaia/wallets.go` line 4 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqJBPG6RTsF_WdmCzp:-NGqJBPG6RTsF_WdmCzq:b-e91ley) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/gaia/wallets.go#L4)):*
> ```Go
> 
> // RelayerMnemonic is mnemonic used be the relayer.
> const RelayerMnemonic = "gas december mango eager element proof budget polar layer worth there eight delay conduct ring wing hover fury flip shield task dismiss ahead olive"
> ```

so the difference between this RelayerMnemonic & one in infra/apps/cored/wallets.go is that this one has corresponding account in gaia chain while other one in coreum chain ?
___
*[`infra/apps/relayer/relayer.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRIWDH8BPfkF1Ftyo0:-NGqJdNj-QoP_pIEUBUm:bs16uvr) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/relayer/relayer.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nowhere in our code we care about windows - it's ignored by definition. But if you insist, you may use `path.Join` which always uses `/`, like you do in other place.
</blockquote></details>

agree with Wojtek here I would use a proper method for this
___
*[`infra/apps/relayer/relayer.go` line 90 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqQrKU276vRoYzQNPg:-NGqQrKU276vRoYzQNPh:bricxiz) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/relayer/relayer.go#L90)):*
> ```Go
> 	statusURL := url.URL{Scheme: "http", Host: infra.JoinNetAddr("", r.Info().HostFromHost, r.config.DebugPort), Path: "/metrics"}
> 	req := must.HTTPRequest(http.NewRequestWithContext(ctx, http.MethodGet, statusURL.String(), nil))
> 	resp, err := http.DefaultClient.Do(req)
> ```

As far as I recall it is not recommended to use default client because it doesn't have timeout


<!-- Sent from Reviewable.io -->

2022-11-15 13:12 UTC, wojtek-coreum requested changes
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/gaia/image.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGQ_s8uBKPQhwHZESsE:-NGvOaRA9V522WoAuGRL:b310b9l) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/build/gaia/image.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, but that "PathLocal" is the commun function to use, if you say that here we can use the `filepath.Join("bin", ".cache", "docker", "gaia")` why do we need to use the `PathLocal ` at all?
</blockquote></details>

`PathLocal` is a function which gives you a path to locally installed tool like `go`. Someone who calls it doesn't even know that th tools are installed under `bin`. Here, you use this function to copy some other file (which is not la locally installed tool) to the `bin` directory. And you use the fact that accidentally `PathLocal`uses `bin` directory. If tomorrow I decide to install tools elsewhere and update the path inside `PathLocal` your code here will suddenly stop working.

If you want to get path to the installed tool use `PathLocal`.
If you want to copy sth to `bin` directory use `filepath.Join`.

Physically these are the same things, locicaly they are different concepts.
___
*[`build/tools/tools.go` line 189 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqAJbM0sTjpbBSHWRy:-NGvM2lm5ocaZ-F-Trf9:b6yrfcs) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L189)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What is the meaning of "Cosmos Relayer" ?
does it define the name of unarchived/final binary ?
</blockquote></details>

yes, surprisingly they really named the binary file this way
___
*[`build/tools/tools.go` line 552 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvMqu20ZXm2vwmHI99:-NGvMqu20ZXm2vwmHI9A:b-mz1u5a) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/build/tools/tools.go#L552)):*
> ```Go
> 
> 	// initial validation to check that we have all binaries
> 	for _, binaryName := range binaryNames {
> ```

you may combine two for loops
___
*[`infra/apps/gaia/gaia.go` line 117 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvNpcBBTsLyIDoIYSo:-NGvNpcBBTsLyIDoIYSp:bk0967) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/infra/apps/gaia/gaia.go#L117)):*
> ```Go
> 		Ports:       infra.PortsToMap(g.config.Ports),
> 		PrepareFunc: g.prepare,
> 		Entrypoint:  filepath.Join(".", targets.AppHomeDir, dockerEntrypoint),
> ```

I really don't understand the purpose of the dot here.
`targets.AppHomeDir` is simply `/app`, which works fine and `./app` will work only if `/` is current dir
___
*[`infra/apps/relayer/relayer.go` line 90 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqQrKU276vRoYzQNPg:-NGvO94141c9Yn5pxOol:b-uhkpgh) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/relayer/relayer.go#L90)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

As far as I recall it is not recommended to use default client because it doesn't have timeout
</blockquote></details>

timeout is in the `ctx` pased to `NewRequestWithContext`


<!-- Sent from Reviewable.io -->

2022-11-15 13:40 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 18 of 27 files reviewed, 13 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGujZvP2PQYLW6kZErA:-NGvWJYREiN19KIH0IeY:bvnrpcm) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Publishing a first batch of comments
</blockquote></details>

updated

___
___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NGvO7xGA4AQOoCjgWac:b-n91l3z) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
shouldn't it be `gaiad` following the logic of `cored` ?
</blockquote></details>

Updated for where is matches logically.



_Code quote:_
```Go
"images/gaia"
```
___
*[`build/gaia/image.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGQ_s8uBKPQhwHZESsE:-NGvQ64gEeCWGK7oT4kn:b2gd3o6) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/build/gaia/image.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`PathLocal` is a function which gives you a path to locally installed tool like `go`. Someone who calls it doesn't even know that th tools are installed under `bin`. Here, you use this function to copy some other file (which is not la locally installed tool) to the `bin` directory. And you use the fact that accidentally `PathLocal`uses `bin` directory. If tomorrow I decide to install tools elsewhere and update the path inside `PathLocal` your code here will suddenly stop working.

If you want to get path to the installed tool use `PathLocal`.
If you want to copy sth to `bin` directory use `filepath.Join`.

Physically these are the same things, locicaly they are different concepts.
</blockquote></details>

Understood your idea, updated it.
___
*[`build/gaia/image.go` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGrXIVx2-PgjuVYWTyY:-NGvOY1o6DvLa_D5H_qO:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/gaia/image.go#L9)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I would probably import it as dockerbasic because when you call in code
```
	dockerfile, err := basic.Execute(...)
```
it is not clear what is happening
</blockquote></details>

Done
___
*[`build/tools/tools.go` line 189 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqAJbM0sTjpbBSHWRy:-NGvOaIb-eoZnXl11UkO:b-tg771p) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L189)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, surprisingly they really named the binary file this way
</blockquote></details>

Yes, the developers use the "Cosmos Relayer" as a name for the binary :-)
___
*[`build/tools/tools.go` line 536 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGrVDewBE2QybHQkf1W:-NGvOhEbECL9K2hTozn6:b8zpenm) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L536)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

"CopyToolBinaries moves the tools artifacts form docker cache to the target local location."

But as far as I know we copy tools from local path to another local path which is later mounted into docker.
</blockquote></details>

We have 2 caches first is OS default where we store the cached files and the second is in the crust. But I agree, I've updated the comment now.
___
*[`build/tools/tools.go` line 559 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGasCSL-__0smzQCMDW:-NGvP9yyBDMB06rozUjn:b-7ufnu8) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L559)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

that is strange that it passed in CI because we have a linter for this (revive rule: error-strings)
And I've tried to make this change locally and linting fails

Any idea what could be wrong with linter in CI ?

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/TnWfhWe_dGQmeuiSG5z8vPNP/image.png)

okay I found that with current linter setup capital letter doesn't trigger this linter to fail. While dot does.

I think we should configure this to be handled on linter level 

Another update: it is actually ignored because we use github.com/pkg/errors not errros pkg and revive doesn't support it I think https://github.com/mgechev/revive/issues/697
</blockquote></details>

I agree to configure it, but not in the scope of the PR, for sure.
___
*[`build/tools/tools.go` line 552 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvMqu20ZXm2vwmHI99:-NGvQSmR8H5UdTSQX708:bq5dg57) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/build/tools/tools.go#L552)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may combine two for loops
</blockquote></details>

Which exactly?
___
*[`infra/apps/cored/wallets.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqI9tw4fizGiLjJGjJ:-NGvPHyr6ogUc9rjOKG4:b-ldn35d) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/cored/wallets.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we have it added only now ? 
</blockquote></details>

It's moved not added. Before it was in the faucet, which isn't logical since the provider is cored, and faucet should use not the constant directly but the `Cored` type which exposed what should be used for the faucet. 
___
*[`infra/apps/gaia/gaia.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRBmAD491IhqyIYAaN:-NGvQiVf8wEVJw5PnCm7:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets discuss this one the call
</blockquote></details>

ok
___
*[`infra/apps/gaia/gaia.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqOzXb7pSiva2UZrs6:-NGvP_5q72ABCRp2xRg7:b7clrgm) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/gaia/gaia.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we can stick to gaia for now.
But ideally I would like to make this package generic so we can easily reuse it for starting e.g osmosis chain.
As far as I understand all of them have similar start procedure. Don't they ?

So ideally image name with prebuild binary should be passed `New` func

same applies to `build/gaia` and some other parts I think ideally `gaia` should not be even mentioned in code and everything should be universal 

WDYT @wojtek-coreum @dzmitryhil ?
</blockquote></details>

Why not gaia? Based on the current state each part is separated, so we can have the osmosis separated as well. 
___
*[`infra/apps/gaia/gaia.go` line 117 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvNpcBBTsLyIDoIYSo:-NGvQnqX5jFLP8wSmfWL:b-hn1ppj) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/infra/apps/gaia/gaia.go#L117)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek)  [...]

2022-11-15 17:54 UTC, ysv requested changes
> Reviewed 5 of 25 files at r1, 6 of 15 files at r2, 1 of 3 files at r4, 2 of 2 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 19 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGujZvP2PQYLW6kZErA:-NGwQKo7-4A0arP9GCLz:b-scktcl) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

updated
</blockquote></details>

Fully finished review

___
___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NGvxyyx-KQRt-YvHwIi:b4pbnl2) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated for where is matches logically.
</blockquote></details>

but should package & other things be named accordingly `gaiad` ?
___
*[`build/tools/tools.go` line 189 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqAJbM0sTjpbBSHWRy:-NGvyVEd8SKVyF6BmMye:bh4x8t1) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L189)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, the developers use the "Cosmos Relayer" as a name for the binary :-)
</blockquote></details>

sort of unexpected :sweat_smile: 
Ok can you just put comment here so none is confused in the future that Cosmos Relayer is the real binary name provided by the team 
___
*[`build/tools/tools.go` line 536 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGrVDewBE2QybHQkf1W:-NGwQNiCANOohhTjb3Hg:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L536)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We have 2 caches first is OS default where we store the cached files and the second is in the crust. But I agree, I've updated the comment now.
</blockquote></details>

ok
___
*[`build/tools/tools.go` line 559 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGasCSL-__0smzQCMDW:-NGvystMEu-AXEkUleu-:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L559)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I agree to configure it, but not in the scope of the PR, for sure.
</blockquote></details>

ok
___
*[`build/tools/tools.go` line 32 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvyK7d4g7GDKKDOQ5Q:-NGvyK7d4g7GDKKDOQ5R:beabll3) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/build/tools/tools.go#L32)):*
> ```Go
> 	Cosmovisor   Name = "cosmovisor"
> 	LibWASMMuslC Name = "libwasmvm_muslc"
> 	Gaia         Name = "gaia"
> ```

I think it should be gaiad here also at least because of binary name: https://github.com/cosmos/gaia/releases/download/v7.0.0/gaiad-v7.0.0-linux-amd64
___
*[`infra/types.go` line 300 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvz7ET-NJU1CH83YUQ:-NGvz7ET-NJU1CH83YUR:b-qo1x6n) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/types.go#L300)):*
> ```Go
> 	RunAsUser bool
> 
> 	// Entrypoint is the custom entrypoint for the container.
> ```

is it a file path or content inside this string is actual `.sh` file ?
___
*[`infra/apps/apps.go` line 191 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGuoSTf4NMj6WsPtcwV:-NGuoSThEBK_nK2DDlVs:bs4w5om) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/infra/apps/apps.go#L191)):*
> ```Go
> 		AppInfo:   f.spec.DescribeApp(relayer.AppType, name),
> 		DebugPort: relayer.DefaultDebugPort,
> 		Cored:     coredApp,
> ```

is it really good idea to pass whole coredApp & gaiaApp to Relayer ?
I don't think soo. IMO relayer shouldn't depend on cored & gaia packages
I would fetch only needed parts and pass them into relayer.Config.

What is more currently relayer is hardcoded to cored & gaia but it should be universal IMO.
Here is the prototype:

```golang
// file relayer/relayer.go
type Config struct {
  Name string
  HomePath string
  DebugPort int
  Networks []Network // not 100% sure about the name here and we might hardcode it to array of size 2 for now for simplicity
 // .. any other config if needed
}

type Network struct {
ChanID          string
RPCUrl          string
AccountPrefix   string
RelayerMnemonic string
RelayerCoinType uint32
}

// file apps/apps.go
func (f *Factory) Relayer(name string, coredApp cored.Cored, gaiaApp gaia.Gaia) relayer.Relayer {
  return relayer.New(
   relayer.Config {
    // ...
   Networks: []relayer.Network{ChainID: coredApp.ChainID(), ...}
    }
)
}
```
___
*[`infra/apps/cored/cored.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGwPAjR2lQmyZQFjobZ:-NGwPAjT1TZO58FwaWaN:bqz5jrx) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/apps/cored/cored.go#L51)):*
> ```Go
> 	IsValidator       bool
> 	StakerMnemonic    string
> 	FundingMnemonic   string
> ```

I personally think that these 3 mnemonics are not part of cored config
They should be just defined as slice of `Mnemonics` or `NonImportedMnemonics` because for cored there is no difference between Funding/Faucet/Relayer mnemonics.

And they should be passed separately into another components
___
*[`infra/apps/cored/wallets.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqI9tw4fizGiLjJGjJ:-NGvzeZPBt7VFsDwdsUh:b-qt7v9l) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/cored/wallets.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's moved not added. Before it was in the faucet, which isn't logical since the provider is cored, and faucet should use not the constant directly but the `Cored` type which exposed what should be used for the faucet. 
</blockquote></details>

I disagree with this approach a bit
IMO app packages incise crust/infra/apps should be as independent on each other as it is possible and for cored it should be just a mnemonic representing account which has to be funded. 
It is not part of required Cored config but just a mnemonic 

But I see that we have a few parts having these type of dependencies on each other so I'm resolving this one but adding comment in another part
___
*[`infra/apps/gaia/gaia.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRBmAD491IhqyIYAaN:-NGw0LF74ZnV6-K8V50_:bfn6i17) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

ok
</blockquote></details>

decided to keep entrypoint on the call
___
*[`infra/apps/gaia/gaia.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqOzXb7pSiva2UZrs6:-NGw-je-5zG-KRSe0L5S:b-1kmabb) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/gaia/gaia.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why not gaia? Based on the current state each part is separated, so we can have the osmosis separated as well. 
</blockquote></details>

we can keep it as it is for now and later once we want to introduce osmosis we can move generic things to `apps/cosmos` and have `apps [...]

2022-11-16 08:12 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 23 of 28 files reviewed, 19 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NGzBrdoEnbfqXSCvi9M:bj8fbpi) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but should package & other things be named accordingly `gaiad` ?
</blockquote></details>

IMHO - no. The gaia is a domain, the gaiad is the runner, similar to the image name and binary name.
___
*[`build/tools/tools.go` line 189 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqAJbM0sTjpbBSHWRy:-NGzCYJj4GUiP5oPOCjs:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/tools/tools.go#L189)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

sort of unexpected :sweat_smile: 
Ok can you just put comment here so none is confused in the future that Cosmos Relayer is the real binary name provided by the team 
</blockquote></details>

Done.



_Code quote:_
```Go
"bin/relayer": "Cosmos Relayer",
```
___
*[`build/tools/tools.go` line 32 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvyK7d4g7GDKKDOQ5Q:-NGzCAxRBFXCXv3RMCgT:b-i60iww) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/build/tools/tools.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it should be gaiad here also at least because of binary name: https://github.com/cosmos/gaia/releases/download/v7.0.0/gaiad-v7.0.0-linux-amd64
</blockquote></details>

I have a bit different understanding f the tool name. The tool name is gaia, but the binary is gaiad. When we build the runner the runner is gaiad as well since the `d` means the `deamon`.
___
*[`infra/types.go` line 300 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvz7ET-NJU1CH83YUQ:-NGzCcYOAYfyUhsiMDeT:b6l934s) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/types.go#L300)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a file path or content inside this string is actual `.sh` file ?
</blockquote></details>

Entrypoint is a Docker entrypoint it can be a path to sh or just a binary reference.
___
*[`infra/apps/apps.go` line 191 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGuoSTf4NMj6WsPtcwV:-NGzD0TyARkYptehwlIh:b-s063uh) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/infra/apps/apps.go#L191)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it really good idea to pass whole coredApp & gaiaApp to Relayer ?
I don't think soo. IMO relayer shouldn't depend on cored & gaia packages
I would fetch only needed parts and pass them into relayer.Config.

What is more currently relayer is hardcoded to cored & gaia but it should be universal IMO.
Here is the prototype:

```golang
// file relayer/relayer.go
type Config struct {
  Name string
  HomePath string
  DebugPort int
  Networks []Network // not 100% sure about the name here and we might hardcode it to array of size 2 for now for simplicity
 // .. any other config if needed
}

type Network struct {
ChanID          string
RPCUrl          string
AccountPrefix   string
RelayerMnemonic string
RelayerCoinType uint32
}

// file apps/apps.go
func (f *Factory) Relayer(name string, coredApp cored.Cored, gaiaApp gaia.Gaia) relayer.Relayer {
  return relayer.New(
   relayer.Config {
    // ...
   Networks: []relayer.Network{ChainID: coredApp.ChainID(), ...}
    }
)
}
```

</blockquote></details>

This is the idea of the dependencies and how it's implemented in the crust now (before my changes): if you need a dependency you pass it whole and then you can take whatever you need from it. The approach is OK for me.
Regarding the "Networks", the idea is good if we have more than two chains and want to connect them all. But if we want to go with it right now we will have to support any amount of the networks and combine them in the config file and passes. The same for the health check. The implementation and testing will require a valuable amount of time. If you still consider that it's needed now, confirm it and I'll reimplement it that way.
___
*[`infra/apps/cored/cored.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGwPAjR2lQmyZQFjobZ:-NGzH2pk61uIMKK9Pufh:b-lga2ls) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/apps/cored/cored.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I personally think that these 3 mnemonics are not part of cored config
They should be just defined as slice of `Mnemonics` or `NonImportedMnemonics` because for cored there is no difference between Funding/Faucet/Relayer mnemonics.

And they should be passed separately into another components
</blockquote></details>

They are different in terms of logic. If we put them all into slice how to chose what to use, since if we use them randomly we might face a problem of the race condition when one tool changes the sequence number and another doesn't expect it.
The same issue will be if we use just on account. 
___
*[`infra/apps/cored/wallets.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqI9tw4fizGiLjJGjJ:-NGzI7b78ebTThspLPTC:bl3hd7i) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/cored/wallets.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree with this approach a bit
IMO app packages incise crust/infra/apps should be as independent on each other as it is possible and for cored it should be just a mnemonic representing account which has to be funded. 
It is not part of required Cored config but just a mnemonic 

But I see that we have a few parts having these type of dependencies on each other so I'm resolving this one but adding comment in another part


</blockquote></details>

I understand what you mean, we can consume what is needed in the constructor and use it. But that is how it was done before and I just follow the strategy. 
___
*[`infra/apps/gaia/gaia.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGRBmAD491IhqyIYAaN:-NGzJd3k4KAo06qfAc-r:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/07df06f1144a82160a47b5de17af03ae41180d89/infra/apps/gaia/gaia.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

decided to keep entrypoint on the call
</blockquote></details>

Done.
___
*[`infra/apps/gaia/gaia.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGqOzXb7pSiva2UZrs6:-NGzIxTB0YQTierL58oe:b3gtfpg) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/infra/apps/gaia/gaia.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we can keep it as it is for now and later once we want to introduce osmosis we can move generic things to `apps/cosmos` and have `apps/osmosis` & `apps/gaiad` which have custom config inside and mostly call methods from cosmos


Do you agree ?
</blockquote></details>

I got your point. In case we will understand that we can simplify the code I agree, but until we see how to do it I would not optimize it since nothing to optimize.
___
*[`infra/apps/gaia/gaia.go` line 51 at r6](https://reviewable.io/re [...]

2022-11-16 18:45 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 23 of 28 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NH0cDnp-HjE8P74iM8T:bi1sg1d) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMHO - no. The gaia is a domain, the gaiad is the runner, similar to the image name and binary name.
</blockquote></details>

I see 
we have a bit of spaghetti here because we have `build/coreum` but `apps/cored`
I would prefer everything to follow the same logic 

 apps/gaia doesn't make sense for me because your app is gaiad or at least the struct in apps/gaia should be named Gaiad because that is what it represetns
___
*[`build/tools/tools.go` line 32 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvyK7d4g7GDKKDOQ5Q:-NH0cUNY5YZ7awjwMmdn:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/build/tools/tools.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I have a bit different understanding f the tool name. The tool name is gaia, but the binary is gaiad. When we build the runner the runner is gaiad as well since the `d` means the `deamon`.
</blockquote></details>

ok
___
*[`infra/apps/apps.go` line 191 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGuoSTf4NMj6WsPtcwV:-NH0Y26437yxwK6_tAoX:baeg4rk) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/infra/apps/apps.go#L191)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the idea of the dependencies and how it's implemented in the crust now (before my changes): if you need a dependency you pass it whole and then you can take whatever you need from it. The approach is OK for me.
Regarding the "Networks", the idea is good if we have more than two chains and want to connect them all. But if we want to go with it right now we will have to support any amount of the networks and combine them in the config file and passes. The same for the health check. The implementation and testing will require a valuable amount of time. If you still consider that it's needed now, confirm it and I'll reimplement it that way.
</blockquote></details>

My intention was to avoid hardcoding of `gaiad` & `cored` as much as possible so we can easily change it no another network in the future.

I don't see problems doing it with my approach anywhere except this.
and here it is also not that complicated
```golang
Dependencies: []infra.HealthCheckCapable{
				r.config.Cored,
				r.config.Gaia,
			},
```

But ok I see that we made it highly dependant before so changing it is not scope of this PR
___
*[`infra/apps/cored/cored.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGwPAjR2lQmyZQFjobZ:-NH0dNoPEr6xDkSTib6R:blno2d4) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/apps/cored/cored.go#L51)):*
> If we put them all into slice how to chose what to use

For cored they are all equal and there is not logic were should treat Faucet mnemonic differently from Relayer so we can put all of them into a slice.

There are other apps where these mnemonics are used differently and I think they should be passed there separately. And we should avoid passing of whole coredApp. Because we currently make our coupling of components to high

But ok I see that it was designed like this initially so we don't want to refactor everything here
___
*[`infra/apps/gaia/gaia.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGwQ4xWBxGn1K6XFG7X:-NH0aO2A23EcFcO5QkAg:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/apps/gaia/gaia.go#L51)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMHO no, we don't even enable it. 
</blockquote></details>

ok
___
*[`infra/testing/run.go` line 38 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGw2yYvDYwrfm8lYnyN:-NH0aseA5QyIkw0FEaJq:b-181q9x) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/testing/run.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

On my machine, it uses + 10-20 sec, but for others it might be different. That's why I set it to x2.
</blockquote></details>

but it is not x2
you had 20 seconds and now it is 2 minutes so x6 

I just think it is a bit too much, no ?
___
*[`infra/testing/run.go` line 38 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGw36IF3R61ndzhMnwQ:-NH0bYzOAB0Hs7xszqmU:b-gdlhpy) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/testing/run.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

For my machine it's ok, the running part isn't heavy and works quite fast. The build part is slower, but that's because of the Docker mounting implementation on the Mac. As an option, we can try to limit the docker resources not to overload the machines. 
</blockquote></details>

ok
I've added task to clickup we will discuss in the next sprint


<!-- Sent from Reviewable.io -->

2022-11-17 06:18 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 23 of 28 files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGq8jZpC0C77wP53bzH:-NH3Clwp0t38Q2rZE_Dt:bhccl07) ([raw file](https://github.com/coreumfoundation/crust/blob/4708cf36480c950a3a9bb1e2ae9a0e4c72466655/build/index.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see 
we have a bit of spaghetti here because we have `build/coreum` but `apps/cored`
I would prefer everything to follow the same logic 

 apps/gaia doesn't make sense for me because your app is gaiad or at least the struct in apps/gaia should be named Gaiad because that is what it represetns
</blockquote></details>

Agree, renamed to apps/gaiad. 
___
*[`infra/testing/run.go` line 38 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGw2yYvDYwrfm8lYnyN:-NH3DjRP2JzMGpq5yL4D:b-yct2tt) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/testing/run.go#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but it is not x2
you had 20 seconds and now it is 2 minutes so x6 

I just think it is a bit too much, no ?
</blockquote></details>

This is the max time, usually it is less, but I've returned it to 1min, we will see whether it's enough.



_Code quote:_
```Go
2*time.Minute
```


<!-- Sent from Reviewable.io -->

2022-11-17 09:39 UTC, wojtek-coreum requested changes
> Reviewed 6 of 9 files at r6, 3 of 5 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/coreum/images.go` line 40 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3v9Vx84VDDOBsg4A_:-NH3v9Vy25PZNW1Wpe44:b-f1wetj) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/coreum/images.go#L40)):*
> ```Go
> 		return err
> 	}
> 	cosmovisorLocalPath := path.Join("bin", ".cache", "docker", "cored")
> ```

let's use filepath for consistency
___
*[`build/gaia/image.go` line 17 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vKS61clvb0__5I5f:-NH3vKS61clvb0__5I5g:bo1ixly) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/gaia/image.go#L17)):*
> ```Go
> 	const binaryName = "gaiad"
> 
> 	gaiaLocalPath := path.Join("bin", ".cache", "docker", "gaia")
> ```

filepath
___
*[`build/relayer/image.go` line 17 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vNbVDrA9_M-5PYL0:-NH3vNbVDrA9_M-5PYL1:bo1ixly) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/relayer/image.go#L17)):*
> ```Go
> 	const binaryName = "relayer"
> 
> 	relayerLocalPath := path.Join("bin", ".cache", "docker", "relayer")
> ```

filepath
___
*[`build/tools/tools.go` line 552 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvMqu20ZXm2vwmHI99:-NH3vkbc9hJ2MFrUDQsC:b-wo04ah) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/build/tools/tools.go#L552)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Which exactly?
</blockquote></details>

you have two `for _, binaryName := range binaryNames {` loops in lines 552 and 566



_Code quote:_
```Go
for _, binaryName := range binaryNames {
```
___
*[`build/tools/tools.go` line 190 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vWfj2PJZFYOnC5uT:-NH3vWfj2PJZFYOnC5uU:b-fsdiv5) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/tools/tools.go#L190)):*
> ```Go
> 				Binaries: map[string]string{
> 					// "Cosmos Relayer" is the binary name in the archive
> 					"bin/relayer": "Cosmos Relayer",
> ```

Now I see that bin name is the same in both amd64 and arm64 archive so you may define it once in the top structure, not separately for each architecture
___
*[`infra/apps/relayer/config.tmpl` line 2 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wCYk1-zsechUbJnq:-NH3wCYl3Xr922VKypvn:b-kk2o5j) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/config.tmpl#L2)):*
> ```
> global:
>     api-listen-addr: :5183
> ```

Is this port exposed from docker? If so, it should be configurable so many instances may run in parallel.
If port is exposed from docker, crust assigns the same port on localhost so two instances may conflict.
___
*[`infra/apps/relayer/relayer.go` line 203 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wvgk-A5ILYdkP_aK:-NH3wvgk-A5ILYdkP_aL:bo1ixly) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/relayer.go#L203)):*
> ```Go
> 	}
> 
> 	configFolderPath := path.Join(r.config.HomeDir, ".relayer", "config")
> ```

filepath
___
*[`infra/apps/relayer/relayer.go` line 209 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wytODAGWVSokRtGE:-NH3wytODAGWVSokRtGF:bo1ixly) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/relayer.go#L209)):*
> ```Go
> 	}
> 
> 	err = os.WriteFile(path.Join(configFolderPath, "config.yaml"), buf.Bytes(), 0o700)
> ```

filepath


<!-- Sent from Reviewable.io -->

2022-11-17 12:52 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 10 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/images.go` line 40 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3v9Vx84VDDOBsg4A_:-NH4cDiQ3Wd4_kY_LfVI:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/coreum/images.go#L40)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's use filepath for consistency
</blockquote></details>

Done.



_Code quote:_
```Go
path.Join("bin", ".cache", "docker", "cored")
```
___
*[`build/gaia/image.go` line 17 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vKS61clvb0__5I5f:-NH4cGfCE5SorY-BjFVc:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/gaia/image.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

filepath
</blockquote></details>

Done.



_Code quote:_
```Go
path.Join("bin", ".cache", "docker", "gaia")
```
___
*[`build/relayer/image.go` line 17 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vNbVDrA9_M-5PYL0:-NH4cK4e4uVws0uS4y-2:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/relayer/image.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

filepath
</blockquote></details>

Done.



_Code quote:_
```Go
path.Join("bin", ".cache", "docker", "relayer")
```
___
*[`build/tools/tools.go` line 552 at r5](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGvMqu20ZXm2vwmHI99:-NH4cX-F9cF73g_aq2rm:b-nu6ax6) ([raw file](https://github.com/coreumfoundation/crust/blob/37ce730824e9213e219d08f3e28c9c063e2acf33/build/tools/tools.go#L552)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you have two `for _, binaryName := range binaryNames {` loops in lines 552 and 566
</blockquote></details>

We shouldn't merge them since in the first loop we validate the existence of all binaries and don't perform the operation if at least one doesn't exist. If we merge them then we might touch file OS and then find that some binaries are missing. 



_Code quote:_
```Go
for _, binaryName := range binaryNames {
```
___
*[`build/tools/tools.go` line 190 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3vWfj2PJZFYOnC5uT:-NH4cSEt5cq9WyuaRfCL:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/build/tools/tools.go#L190)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now I see that bin name is the same in both amd64 and arm64 archive so you may define it once in the top structure, not separately for each architecture
</blockquote></details>

Done.



_Code quote:_
```Go
"bin/relayer": "Cosmos Relayer",
```
___
*[`infra/apps/relayer/config.tmpl` line 2 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wCYk1-zsechUbJnq:-NH4dCWvAF4AwNqRL2SD:b-lahmtf) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/config.tmpl#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is this port exposed from docker? If so, it should be configurable so many instances may run in parallel.
If port is exposed from docker, crust assigns the same port on localhost so two instances may conflict.
</blockquote></details>

Nope, it isn't that is the default config, but we don't use it.



_Code quote:_
```
 api-listen-addr: :5183
```
___
*[`infra/apps/relayer/relayer.go` line 203 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wvgk-A5ILYdkP_aK:-NH4dJOn62eVzJbwpXL-:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/relayer.go#L203)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

filepath
</blockquote></details>

Done.



_Code quote:_
```Go
 path.Join(r.config.HomeDir, ".relayer", "config")
```


<!-- Sent from Reviewable.io -->

2022-11-17 12:52 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: 23 of 28 files reviewed, 10 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/relayer/relayer.go` line 209 at r10](https://reviewable.io/reviews/coreumfoundation/crust/136#-NH3wytODAGWVSokRtGE:-NH4dQswE9rmXFi8Y71k:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/95e7265040ccf592ca67abb4c4d43c336c581a02/infra/apps/relayer/relayer.go#L209)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

filepath
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-17 23:38 UTC, ysv submitted a review, later dismissed
> Reviewed 2 of 5 files at r7, 5 of 6 files at r9, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`infra/testing/run.go` line 38 at r6](https://reviewable.io/reviews/coreumfoundation/crust/136#-NGw2yYvDYwrfm8lYnyN:-NH6wvMj4UUkgRlMW-_M:bb7m07t) ([raw file](https://github.com/coreumfoundation/crust/blob/9b3b17ff9950fefee7da23c158b0878fbebb7cda/infra/testing/run.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the max time, usually it is less, but I've returned it to 1min, we will see whether it's enough.
</blockquote></details>

okay


<!-- Sent from Reviewable.io -->

2022-11-18 11:23 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 3 of 5 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-21 08:45 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-21 09:35 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-21 10:47 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-11-21 13:09 UTC, ysv approved these changes
> Reviewed 4 of 5 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-11-21 14:00 UTC, merged