Adjust crust validator delegation to customParams.Staking.MinimumSelfDelegation
CoreumFoundation/crust pull request #172
Opened 2023-03-01 08:49 UTC by vertex451

# Issue:
https://app.clickup.com/t/862hxz3vw

# Testing:
## `crust znet test` 
All tests succeeded 

## Manual
`crust znet start --profiles=3cored`:
```
cored q staking validator devcorevaloper17wep7cp7kux5maqr5mrqd7we3ndnz97rzdxlvn --chain-id=coreum-devnet-1

# output:
  min_self_delegation: "20000000000"
...
  status: BOND_STATUS_BONDED
  tokens: "1000000000000"

```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/crust/172)

2023-03-01 09:28 UTC, miladz68 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPRUGsv71vBrw2yWkWC:-NPRUGsw2_Zj9_G10aeD:by4mqh2) ([raw file](https://github.com/CoreumFoundation/crust/blob/31d10d7a51e6bfc9e5e633a3b807cd4716862934/infra/apps/cored/cored.go#L82)):*
> ```Go
> 		must.OK(err)
> 
> 		minimumSelfDelegation := sdk.NewInt64Coin(cfg.Network.Denom(), oneMillionCore)
> ```

instead of adding 10 percent to the stake value, we can reduce the min_self_delegation to a reasonable number like 20k or 50k and the problem will go away 
@ysv 
___
*[`infra/apps/cored/cored.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPRUxYQ8I--b9HWMfWh:-NPRUxYQ8I--b9HWMfWi:bak0l5v) ([raw file](https://github.com/CoreumFoundation/crust/blob/31d10d7a51e6bfc9e5e633a3b807cd4716862934/infra/apps/cored/cored.go#L83)):*
> ```Go
> 
> 		minimumSelfDelegation := sdk.NewInt64Coin(cfg.Network.Denom(), oneMillionCore)
> 		// we must have the balance significantly more than the balance of the global validator min_self_delegation
> ```

@dzmitryhil @wojtek-coreum 
the comment here makes no sense to me, could please you provide more input ?


<!-- Sent from Reviewable.io -->

2023-03-01 13:48 UTC, ysv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPRUGsv71vBrw2yWkWC:-NPSQAQL4Zr3K4wav2vN:b-ijkut8) ([raw file](https://github.com/CoreumFoundation/crust/blob/31d10d7a51e6bfc9e5e633a3b807cd4716862934/infra/apps/cored/cored.go#L82)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

instead of adding 10 percent to the stake value, we can reduce the min_self_delegation to a reasonable number like 20k or 50k and the problem will go away 
@ysv 
</blockquote></details>

I agree lets put some reasonable amount here I suggest 20k same as we have on testnet & mainnet

But is this value defined on coreum side or we can fully change it here ?


<!-- Sent from Reviewable.io -->

2023-03-01 14:05 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPRUGsv71vBrw2yWkWC:-NPSUOM-5rnKgNrgsc-7:b-5z4oaw) ([raw file](https://github.com/CoreumFoundation/crust/blob/31d10d7a51e6bfc9e5e633a3b807cd4716862934/infra/apps/cored/cored.go#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree lets put some reasonable amount here I suggest 20k same as we have on testnet & mainnet

But is this value defined on coreum side or we can fully change it here ?
</blockquote></details>

it is defined in coreum. but we put a higher amount there. so we are good here.


<!-- Sent from Reviewable.io -->

2023-03-02 07:32 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPRUxYQ8I--b9HWMfWh:-NPWCuvW6KMdEObrEJ3F:b-8xsu9e) ([raw file](https://github.com/CoreumFoundation/crust/blob/31d10d7a51e6bfc9e5e633a3b807cd4716862934/infra/apps/cored/cored.go#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@dzmitryhil @wojtek-coreum 
the comment here makes no sense to me, could please you provide more input ?
</blockquote></details>

The comment is about the fact that we have integration tests adding new validators with min self delegation, and then we kill them when test completes. So if those tests run together and create validators having 33% of voting power, then killing them will halt the chain. That's why our main validators created here must have much higher stake.

That comment should not be removed, but should be followed here.
___
*[`infra/apps/cored/cored.go` line 44 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPWCH5T6XX9kG3jN0oG:-NPWCH5T6XX9kG3jN0oH:b-myyk7r) ([raw file](https://github.com/CoreumFoundation/crust/blob/f4071befd7750f08a74578eab7936a3084f8b3d4/infra/apps/cored/cored.go#L44)):*
> ```Go
> 	AppType infra.AppType = "cored"
> 
> 	oneMillionCore     = 1_000_000_000_000
> ```

instead of naming the constants by the amount I would prefer to name them by purpose. e.g. `twentyThousandCore` -> `validatorSelfDelegatedAmount`
___
*[`infra/apps/cored/cored.go` line 84 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/172#-NPWCW23-laDzM6bfpeT:-NPWCW23-laDzM6bfpeU:b-g742u5) ([raw file](https://github.com/CoreumFoundation/crust/blob/f4071befd7750f08a74578eab7936a3084f8b3d4/infra/apps/cored/cored.go#L84)):*
> ```Go
> 		must.OK(err)
> 
> 		minimumSelfDelegation := sdk.NewInt64Coin(cfg.Network.Denom(), twentyThousandCore) // 20k core
> ```

`// 20k core` comment might be removed because now it is defined as constant and value might change later


<!-- Sent from Reviewable.io -->

2023-03-02 14:45 UTC, miladz68 submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-03 07:54 UTC, miladz68 submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-03 09:22 UTC, wojtek-coreum approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-03 13:58 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2023-03-03 14:04 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2023-03-04 15:35 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)



<!-- Sent from Reviewable.io -->

2023-03-05 16:28 UTC, merged