New flag cored-version and dev upgrade.
CoreumFoundation/crust pull request #179
Opened 2023-03-15 08:38 UTC by dzmitryhil

* Add `cored-version` flag to add a possibility to run the znet from specific version
* Rename fake upgrade to dev upgrade

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/crust/179)

2023-03-15 16:59 UTC, wojtek-coreum requested changes
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/go.mod` line 7 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQa7yHcDDOu5RTazTEZ:-NQa7yHd7F7wiGWtBpv3:bb7r2f0) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/build/go.mod#L7)):*
> ```XML
> go 1.19
> 
> replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
> ```

why?
___
*[`build/go.mod` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQa8Evv-dq_udYtZjzK:-NQa8Evv-dq_udYtZjzL:b-ixhyu0) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/build/go.mod#L10)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum v0.1.1
> ```

why not the latest commit?
___
*[`build/coreum/images.go` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQa9SZf3YqgsK1OKny8:-NQa9SZf3YqgsK1OKny9:bfytm5l) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/build/coreum/images.go#L16)):*
> ```Go
> // BuildCoredDockerImage builds cored docker image.
> func BuildCoredDockerImage(ctx context.Context, deps build.DepsFunc) error {
> 	deps(ensureCosmovisor, BuildCoredInDocker, ensureReleasedBinaries(allReleases()), buildCoredWithDevUpgrade)
> ```

I don't know how this mechanism of `deps` may behave if eventually another function calls `ensureReleasedBinaries` with the same or different argument. I would advise to hardcode the list of binaries inside `ensureReleasedBinaries` (or reference global var from there). Will we ever use it in another set?
___
*[`build/coreum/images.go` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaADh78Vm9HqAG715c:-NQaADh78Vm9HqAG715d:b-90ctp9) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/build/coreum/images.go#L22)):*
> ```Go
> 		CoredBinary:      binaryName,
> 		CosmovisorBinary: cosmovisorBinaryName,
> 		Networks:         []string{string(constant.ChainIDDev), string(constant.ChainIDTest)},
> ```

why testnet is added?
___
*[`infra/apps/cored/cored.go` line 353 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaC8_U0AVOFxYWjcE0:-NQaC8_U0AVOFxYWjcE1:bp3th4n) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L353)):*
> ```Go
> 		binaryPath += "-" + c.Config().BinaryVersion
> 	}
> 	if err := copyFile(binaryPath, filepath.Join(c.config.HomeDir, "cosmovisor", "genesis", "bin", "cored"), 0o755); err != nil {
> ```

why not symlink to make it faster?
___
*[`infra/apps/cored/cored.go` line 360 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaCKBf6qQ2qhgrN6f0:-NQaCKBf6qQ2qhgrN6f1:b-r2r89e) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L360)):*
> ```Go
> 	upgrades := map[string]string{
> 		"dev-upgrade": "cored-dev-upgrade",
> 		"v1":          "cored-dev-upgrade", // TODO(dhil) update to v1.0.0 once the binary is ready
> ```

v1 -> v1.0.0
___
*[`infra/apps/cored/cored.go` line 363 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaCPPE5glC37gLcEEV:-NQaCPPE5glC37gLcEEW:ba02awt) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L363)):*
> ```Go
> 	}
> 	for upgrade, binary := range upgrades {
> 		return copyFile(filepath.Join(c.config.BinDir, ".cache", "docker", "cored", binary),
> ```

this might be symlinked too
___
*[`pkg/znet/commands.go` line 69 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaAvtr45a-YvP0KiYg:-NQaAvtr45a-YvP0KiYh:b3rfbay) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/pkg/znet/commands.go#L69)):*
> ```Go
> 	}
> 	shellCmd := osexec.Command(shell)
> 	shellCmd.Env = append(os.Environ(),
> ```

Please add `CRUST_ZNET_CORED_VERSION` here


<!-- Sent from Reviewable.io -->

2023-03-15 17:25 UTC, wojtek-coreum reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-15 17:42 UTC, miladz68 submitted a review, later dismissed
> Reviewed 12 of 15 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-15 19:53 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 360 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaCKBf6qQ2qhgrN6f0:-NQapMZT42L8lXtiKrlq:blnlv31) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L360)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Nope, "v1" this is the upgrade version, it's not related with the binary.
</blockquote></details>

I don't understand this. Upgrade always upgrades to some version so it is reasonable to name the upgrade after the binary version


<!-- Sent from Reviewable.io -->

2023-03-16 09:09 UTC, miladz68 approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 7 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-16 13:43 UTC, wojtek-coreum requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 353 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaC8_U0AVOFxYWjcE0:-NQedlLh5HLMU-amE2HQ:bk6agfd) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L353)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Because for some reason the cosmovisor says on my machine:
```
Error: current binary is invalid: cannot stat dir /app/coreum-devnet-1/cosmovisor/genesis/bin/cored: stat /app/coreum-devnet-1/cosmovisor/genesis/bin/cored: no such file or directory
6:38AM ERR error="current binary is invalid: cannot stat dir /app/coreum-devnet-1/cosmovisor/genesis/bin/cored: stat /app/coreum-devnet-1/cosmovisor/genesis/bin/cored: no such file or directory" module=cosmovisor
```

</blockquote></details>

But we used symlink all the time. Did it work for you when you run `znet test` before?
___
*[`infra/apps/cored/cored.go` line 360 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaCKBf6qQ2qhgrN6f0:-NQedxiO1n8bhtmRez_n:bjrv14k) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L360)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The common practice is to call the upgrades incremental, since it's hard to map the binary with the upgrade. 
For example let's say that the upgrade is ready and now, but you don't know the binary version at all what will you use? Or let's assume that you know that you are going to create a new release x.y.z, so you set the upgrade version to the x.y.z and create the release, but then you understand that you need to add something, and create x.y.z2, which is absolutely normal. In case we go with the incremental, all is OK, if we go with the binary version = upgrade version we will have to change it provisionally every time. 
Just to sum up better to go with the incremental upgrade version, like most of the chains do.
</blockquote></details>

Ok, I agree, but let's not use `v` in this context then. We may use some code names or `upgrade1` instead


<!-- Sent from Reviewable.io -->

2023-03-16 14:38 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 360 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/179#-NQaCKBf6qQ2qhgrN6f0:-NQeqjR82vZrUr9AlrPq:b-klmfvu) ([raw file](https://github.com/CoreumFoundation/crust/blob/134262f8b2d8590a082aaa3079bacd6335e1b945/infra/apps/cored/cored.go#L360)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why not v1 ?
</blockquote></details>

because `v` seems like a version of binary


<!-- Sent from Reviewable.io -->

2023-03-16 15:28 UTC, wojtek-coreum submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-16 16:33 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)



<!-- Sent from Reviewable.io -->

2023-03-16 17:02 UTC, merged