F/wasm dev pipeline
CoreumFoundation/crust pull request #22
Opened 2022-07-19 15:12 UTC by xlab

For the feature list to check out and test, see [SMART_CONTRACTS.md](/SMART_CONTRACTS.md)

2022-07-19 20:18 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7N5s3R3vS1-DJXHRyf:b4qbnz6) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

could `crust setup` do it for us?
</blockquote></details>

Thing is that contract development is separate from cored and Go development. You don't install full Go and Geth when you want to create a smart contract. 

There, smart contracts also don't require building anything related to coreum, you can deploy by RPC.


<!-- Sent from Reviewable.io -->

2022-07-19 20:20 UTC, xlab commented
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7N6HSO2kL9-rnGqGcV:b2b1hiz) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could `workspaceDir` be a part of `config`?
</blockquote></details>

It's a required arg, while config is optional.


<!-- Sent from Reviewable.io -->

2022-07-19 20:21 UTC, xlab commented
*[`pkg/contracts/init.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MFC8I0O-aCkMnOhos:-N7N6lkuE8lqdM0hV3do:b-rtifpn) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/init.go#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`MkdirAll` does not return an error if directory exists so this `if / if else` block might be simplified to:

```go
if err := os.MkdirAll(config.TargetDir, 0o700); err != nil {
    return errors.Wrap(err, "failed to create contract source dir")
}
```
</blockquote></details>

How to tell when `MkdirAll` returns an error for `info.IsDir()` ?


<!-- Sent from Reviewable.io -->

2022-07-19 20:22 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`pkg/contracts/rust.go` line 227 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MGes10F3QSns4y5Ka:-N7N78kj-82MoRJ1rSsd:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/rust.go#L227)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

oldVersion -> installedVersion
newVersion -> requiredVersion
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 21:20 UTC, oliverasistemas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/contracts/build.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NKKlO8HsvKyxBLNTH:-N7NKKlO8HsvKyxBLNTI:b-t5t1bp) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/build.go#L80)):*
> ```Go
> 
> // runCargoCheck checks workspace and all dependencies for errors
> func runCargoCheck(ctx context.Context, workspaceDir string) error {
> ```

Is this function used?
___
*[`pkg/contracts/build.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NKNc5CKbQU8HTQbsl:-N7NKNc5CKbQU8HTQbsm:b-t5t1bp) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/build.go#L96)):*
> ```Go
> 
> // runDebugBuild builds the debug variant of the contract for the wasm target
> func runDebugBuild(ctx context.Context, workspaceDir string) error {
> ```

Is this function used?
___
*[`pkg/contracts/test.go` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NJtXv6-fordnuWyAe:-N7NJtXw01tRvRIzWzJx:b-3lv1cu) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/test.go#L22)):*
> ```Go
> type TestConfig struct {
> 	// NeedCoverageReport enables running additional code coverage collector tool 'tarpaulin',
> 	// which is currently available for linux/amd64 only. Enabling this option on other OSes will trigger a warn.
> ```

warn -> warning


<!-- Sent from Reviewable.io -->

2022-07-20 06:06 UTC, wojtek-coreum requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7PBHdS3Fq4hJUMy8fb:-N7PBHdS3Fq4hJUMy8fc:b-c6osfb) (no related file):*
@xlab @miladz68 @ysv 

I would like to discuss this during the daily:

Who is the target audience of this tool?
1. Smart contract developers? If so, then they probably have their own workflow configured together with rust IDE, CI etc. They know how to do their job. Do they need a support from us?
2. Our team to deploy test smart contract? Then we only need to compile a single, simple smart contract inside docker container, so generic tool for smart contract development is not needed.

Technically this code is fine, my question is if we need it and if we really should deliver it to the community, meaning we will need to support and maintain it.

___
___
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7PAMtb6rw7RRV78zGu:bbpb6ib) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Thing is that contract development is separate from cored and Go development. You don't install full Go and Geth when you want to create a smart contract. 

There, smart contracts also don't require building anything related to coreum, you can deploy by RPC.
</blockquote></details>

How our test smart contract will be built for integration tests? Using this tool or directly inside docker? If inside docker and it doesn't require me to install rust manually then I'm fine.
___
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7PAlevDhNqIE5ZEoWi:b-3hlu9m) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
> config is optional
WDYM? `config` is an argument to this function
___
*[`pkg/contracts/init.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MFC8I0O-aCkMnOhos:-N7PAvjtCscE9lkdJJYu:b-yttyky) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/init.go#L53)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

How to tell when `MkdirAll` returns an error for `info.IsDir()` ?
</blockquote></details>

I've never tested it but my guess is that if file `/tmp/test` exists then `os.MkdirAll("/tmp/test", 0o700)` will return an error. You may try.


<!-- Sent from Reviewable.io -->

2022-07-20 10:02 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7Q2d714iFPqWyey3bf:b-59c0u3) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

How our test smart contract will be built for integration tests? Using this tool or directly inside docker? If inside docker and it doesn't require me to install rust manually then I'm fine.
</blockquote></details>

The test one will be a pre-compiled optimized fixture. So only deployment stage will be used during integration testing stage.


<!-- Sent from Reviewable.io -->

2022-07-20 10:04 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/contracts/build.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NKKlO8HsvKyxBLNTH:-N7Q3FFSEhOhaSrAaJCO:bsrke6d) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/build.go#L80)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

Is this function used?
</blockquote></details>

Done. Was a typo in other place.


<!-- Sent from Reviewable.io -->

2022-07-20 10:05 UTC, xlab commented
*[`pkg/contracts/build.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NKNc5CKbQU8HTQbsl:-N7Q3IVm1fZlLpIbOXT8:bnxaspq) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/build.go#L96)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

Is this function used?
</blockquote></details>

It's there to fix flags for debug build, shall we need one. Don't want to remember them later. It might be removed if you insist.


<!-- Sent from Reviewable.io -->

2022-07-20 10:11 UTC, xlab commented
*[`pkg/contracts/init.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MFC8I0O-aCkMnOhos:-N7Q4iQpBBw7DP-8sxUs:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/init.go#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I've never tested it but my guess is that if file `/tmp/test` exists then `os.MkdirAll("/tmp/test", 0o700)` will return an error. You may try.
</blockquote></details>

Done.



_Code quote:_
```Go
os.Stat(config.TargetDir)
```


<!-- Sent from Reviewable.io -->

2022-07-20 10:19 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/contracts/test.go` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7NJtXv6-fordnuWyAe:-N7Q6dzX1-e0MUgb6ene:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/c0ff401d3d8e236723aeb6e8d4a7ac72a2be69d3/pkg/contracts/test.go#L22)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

warn -> warning
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-20 10:35 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7Q9spd0fRqk6vT1rKv:b-53elc9) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

The test one will be a pre-compiled optimized fixture. So only deployment stage will be used during integration testing stage.
</blockquote></details>

So another point to discuss during the meeting: I would prefer to keep rust source in the repo, compile it each time and then deploy

^ @miladz68 @ysv 
___
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7QAB4gBO7hWYDXKMDH:b-dob696) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Yes, but you can pass `BuildConfig{}`, I mean all the fields are optional
</blockquote></details>

So there might be a non-optional field `WorkspaceDir`


<!-- Sent from Reviewable.io -->

2022-07-20 10:49 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7QDLNCD6aR0SxifdWU:b9ddhd1) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So another point to discuss during the meeting: I would prefer to keep rust source in the repo, compile it each time and then deploy

^ @miladz68 @ysv 
</blockquote></details>

And what part of the integration it really tests that way?


<!-- Sent from Reviewable.io -->

2022-07-20 10:50 UTC, xlab commented
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7QD_AM-9nXSKzIjJrv:b-htt9hs) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So there might be a non-optional field `WorkspaceDir`
</blockquote></details>

Might be, but what is the problem to have it as a function argument though?


<!-- Sent from Reviewable.io -->

2022-07-20 10:52 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7QE0xB82_eLWq5ntNc:bpk16x0) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

And what part of the integration it really tests that way?
</blockquote></details>

It's not about testing, it's about having source code in the repo instead of the binary.


<!-- Sent from Reviewable.io -->

2022-07-20 14:00 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7Qu9QD0Jo86EW2J_gH:b-cuqdxv) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not about testing, it's about having source code in the repo instead of the binary.
</blockquote></details>

It can be both then. But that doesnt mean you have to rebuild the code of a contract every time you run a test.


<!-- Sent from Reviewable.io -->

2022-07-20 16:15 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7RNBhpEklrDFL8NNcz:b-v57krc) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It can be both then. But that doesnt mean you have to rebuild the code of a contract every time you run a test.
</blockquote></details>

If source code is in repo, then I don't need to have binary there. Because it means that someone needs to build that binary manually using local environment prepared according to magic procedure. It should be automated to save manpower and as a form of documentation saying how it is done. Not by following outdated instruction.
___
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7RNhMr80tT9VDwcPxV:bi2jmj) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Might be, but what is the problem to have it as a function argument though?
</blockquote></details>

You have a two config parameters:
- one is a container for (almost) all the parameters
- second one is so special that you placed it separately in the argument list

I don't see why that argument is so special, that's why it should be placed in the container together with others.


<!-- Sent from Reviewable.io -->

2022-07-21 12:51 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MDEsH78RwCR2xGLW9:-N7VnX64BZlYPZnWPHbj:bfpooy6) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/SMART_CONTRACTS.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If source code is in repo, then I don't need to have binary there. Because it means that someone needs to build that binary manually using local environment prepared according to magic procedure. It should be automated to save manpower and as a form of documentation saying how it is done. Not by following outdated instruction.
</blockquote></details>

I have no idea what are you talking about there, I totally lost the context.

If test needs a fixture, it shall be a fixture. If you want to re-generate a fixture at some point, I agree we should include the source of that fixture. But rebuilding the fixture every time CI runs is a waste of time, especially when the method used to generate the artefact is specifically designed to be deterministic, i.e. a fixture built on local machine would be exactly the same as from CI. And the size of that fixture is about ~140K.


<!-- Sent from Reviewable.io -->

2022-07-21 12:53 UTC, xlab commented
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N7VoK0O0z5HqDARkXWl:b2zht0e) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
> I don't see why that argument is so special, that's why it should be placed in the container together with others.

This argument is required, others are optional.


<!-- Sent from Reviewable.io -->

2022-07-22 08:49 UTC, wojtek-coreum reviewed
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 5 of 14 files reviewed, 6 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-02 17:05 UTC, begmaroman reviewed
Really like this code style 👍

2022-08-02 17:05 UTC, begmaroman commented on cmd/contracts/main.go
> +}
Does it make sense to move it to some kind of utils package?

2022-08-02 17:05 UTC, begmaroman commented on pkg/contracts/build.go
> +		return err
Is it a code style you are using across all codebase? Like instead of just returning wrapped error

2022-08-02 17:05 UTC, begmaroman commented on pkg/contracts/init.go
> +
Should be removed?

2022-08-02 17:05 UTC, begmaroman commented on pkg/contracts/init.go
> +
Should be removed?

2022-08-02 17:05 UTC, begmaroman commented on pkg/contracts/init.go
> +func (c InitConfig) Sanitize() InitConfig {
As I see, all exported types have comments. Shouldn't this function be commented on as well?

2022-08-03 09:27 UTC, xlab commented
*[`pkg/contracts/init.go` line 11 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPd-r6-11:-N8Y10ut1TYWPafzxOHz:b21ju6j) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/init.go#L11)):*
<details><summary><i>Previously, begmaroman wrote…</i></summary><blockquote>

Should be removed? 
</blockquote></details>

Why? Go checks for unused imports, this import is unused.


<!-- Sent from Reviewable.io -->

2022-08-03 09:29 UTC, xlab commented
*[`pkg/contracts/init.go` line 6 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPd-r6-6:-N8Y1PJQ1v_XRWFfK-Yr:b-6hngg2) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/init.go#L6)):*
<details><summary><i>Previously, begmaroman wrote…</i></summary><blockquote>

Should be removed? 
</blockquote></details>

Ah I get it, the comment addresses the blank space. This one is extra, yeah.


<!-- Sent from Reviewable.io -->

2022-08-03 09:30 UTC, xlab commented
*[`pkg/contracts/init.go` line 11 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPd-r6-11:-N8Y1VU12K3_5-_Ikdue:bfj6kcz) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/init.go#L11)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Why? Go checks for unused imports, this import is unused.
</blockquote></details>

Ah I get it, yeah the blank space was extra. May be removed.


<!-- Sent from Reviewable.io -->

2022-08-03 09:33 UTC, xlab commented
*[`cmd/contracts/main.go` line 160 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPa-r6-160:-N8Y24fRBXngLrD0548x:btebtmp) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/cmd/contracts/main.go#L160)):*
<details><summary><i>Previously, begmaroman wrote…</i></summary><blockquote>

Does it make sense to move it to some kind of utils package? 
</blockquote></details>

It's not worth introducing a dependency for this trivial functionality, usually.

But I agree that implementing flag parsing for every app is tedious job. However, entire approach there is dirty, so I just continued to build upon existing code, because otherwise we'll spend weeks in discussion how to make flag parsing ideally :)


<!-- Sent from Reviewable.io -->

2022-08-03 11:34 UTC, ysv requested changes
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/22)* status: 6 of 14 files reviewed, 11 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7PBHdS3Fq4hJUMy8fb:-N8YLn4c2_7Iqjc0-lVj:bnsoepd) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab @miladz68 @ysv 

I would like to discuss this during the daily:

Who is the target audience of this tool?
1. Smart contract developers? If so, then they probably have their own workflow configured together with rust IDE, CI etc. They know how to do their job. Do they need a support from us?
2. Our team to deploy test smart contract? Then we only need to compile a single, simple smart contract inside docker container, so generic tool for smart contract development is not needed.

Technically this code is fine, my question is if we need it and if we really should deliver it to the community, meaning we will need to support and maintain it.
</blockquote></details>

Thanks for bringing this question

Also discussed with Reza and I have some input from him will share it with you during todays discussion

___
___
*[`cmd/contracts/main.go` line 160 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPa-r6-160:-N8YPQWN-JTaotbnpVwo:b-sp43f0) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/cmd/contracts/main.go#L160)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's not worth introducing a dependency for this trivial functionality, usually.

But I agree that implementing flag parsing for every app is tedious job. However, entire approach there is dirty, so I just continued to build upon existing code, because otherwise we'll spend weeks in discussion how to make flag parsing ideally :)
</blockquote></details>

makes sense for me to move `defaultString` & `toBool`   to ./crust/pkg/<stmth> (e.g envs or flags etc)
___
*[`pkg/contracts/build.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7MD0eNAeUaj880vHEf:-N8YPufs2n33hVrmpH45:b-ltfke8) ([raw file](https://github.com/coreumfoundation/crust/blob/a35f0ac77151478c950c484d0fe3638319b7e28f/pkg/contracts/build.go#L24)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> I don't see why that argument is so special, that's why it should be placed in the container together with others.

This argument is required, others are optional.
</blockquote></details>

Agree with Wojtek pls make this change
___
*[`pkg/contracts/build.go` line 29 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPb-r6-29:-N8YQJ4BBuYLmf2VOc0T:bgv517y) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/build.go#L29)):*
Roman's comment makes sense for me 
I think we should use `return errors.Wrap ...`
@xlab  Can you pls change it here and it other parts of PR ?

> Other extreme you may find in our codebase is when a single return statement takes about 50 lines.
We should not be doing these type of things unless there is no other way. 
Please share a code example and possible refactoring approach here if needs discussion or in PR if refactoring is trivial
___
*[`pkg/contracts/init.go` line 30 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPd-r6-30:-N8YSZQmAz8mKokuD6Al:b4uoaer) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/init.go#L30)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

As I see, all exported types have comments. Shouldn't this function be commented on as well? 
</blockquote></details>

yes please add
@begmaroman do you know if we can introduce linter for this ? If yes can you do this pls ?


<!-- Sent from Reviewable.io -->

2022-08-05 00:42 UTC, closed without merging

2022-08-05 16:43 UTC, xlab commented
*[`pkg/contracts/init.go` line 30 at r6](https://reviewable.io/reviews/coreumfoundation/crust/22#-N7M06VRAWKAcaOe8mPd-r6-30:-N8iswS50eUwSKHDpA8B:bnb26gw) ([raw file](https://github.com/coreumfoundation/crust/blob/8b85a0fba543e504220d1707d857b4b1cad2c46f/pkg/contracts/init.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes please add
@begmaroman do you know if we can introduce linter for this ? If yes can you do this pls ?
</blockquote></details>

We have a linter for this, it just had to run at least once.


<!-- Sent from Reviewable.io -->