Proto docs generation
CoreumFoundation/crust pull request #225
Opened 2023-06-16 09:59 UTC by vertex451

Here is the generated file:
[api.md](https://github.com/CoreumFoundation/crust/files/11770550/api.md)

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/crust/225)

2023-06-16 12:06 UTC, wojtek-coreum requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/docs/proto-gen.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY3582a8l0s22OdSI0n:-NY3582a8l0s22OdSI0o:bw83t12) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L34)):*
> ```Go
> 	log := logger.Get(ctx)
> 
> 	err := coreum.Tidy(ctx, deps)
> ```

Use `deps(coreum.Tidy)`
___
*[`build/docs/proto-gen.go` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY32AGlAaLbNyRJ6UAL:-NY32AGlAaLbNyRJ6UAM:b-sl3i86) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L45)):*
> ```Go
> 	}
> 
> 	err = copyProtoFiles(log, moduleToVersion)
> ```

why do we need to copy those files to generate docs from them?
___
*[`build/docs/proto-gen.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34yA27MH8Q5LxcdTw:-NY34yA27MH8Q5LxcdTx:bxx2942) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L51)):*
> ```Go
> 	}
> 
> 	err = git.EnsureRepo(ctx, repoURL)
> ```

use `deps(ensureRepo)` instead. `deps` is used to ignore following calls to the same action made by other actions
___
*[`build/docs/proto-gen.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY32Ide-H4VSKU2HYHj:-NY32Ide-H4VSKU2HYHk:byla0u0) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L66)):*
> ```Go
> }
> 
> func getModulesVersions() (map[string]string, error) {
> ```

getModuleVersions
___
*[`build/docs/proto-gen.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY32ON5D3BCoZfgLPrJ:-NY32ON5D3BCoZfgLPrK:bd9e1ez) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L74)):*
> ```Go
> 
> 	// Go to coreum dir.
> 	err := os.Chdir("../coreum")
> ```

instead of changing working dir, set the working directory for a command (`cmd.Dir`)
___
*[`build/docs/proto-gen.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY32bSU3-DevvZBgwDa:-NY32XeP9IPiQj7dGOU3:b-gmbs2a) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L83)):*
> ```Go
> 	var output []byte
> 	for moduleName := range moduleToVersion {
> 		cmd = exec.Command("go", "list", "-m", moduleName)
> ```

All the commands executing `go` should be done in `golang` package. Check other functions there to see how `go` is called.
___
*[`build/docs/proto-gen.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY33ApqC3O6j2uneB0b:-NY33ApqC3O6j2uneB0c:b-vjufqi) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L104)):*
> ```Go
> 	goPath := os.Getenv("GOPATH")
> 	if goPath == "" {
> 		return errors.New("empty GOPATH")
> ```

Empty GOPATH is expected. In this case go takes $HOME/go (`filepath.Join(must.String(os.UserHomeDir()), "go")`)
___
*[`build/docs/proto-gen.go` line 112 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34gng7-Xec3ssFNhj:-NY34gng7-Xec3ssFNhk:b-jzijgz) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L112)):*
> ```Go
> 		case cosmosSdkModule:
> 			// example: $GOPATH/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.16/proto.
> 			sourceDir = fmt.Sprintf("%s/pkg/mod/%s@%s/proto/cosmos", goPath, repo, version)
> ```

here and below: Use `filepath.Join`
___
*[`build/docs/proto-gen.go` line 136 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY33oX925czEAwrBE0c:-NY33oX925czEAwrBE0d:bp1fbn4) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L136)):*
> ```Go
> func executeProtocCommand() error {
> 	cmd := exec.Command("sh", "-c", `
> 		protoc \
> ```

Ensure that `protoc` is installed by adding it to tools. Take a look how `golang.EnsureGo` works as an example. Also check how `go` binary is called in `golang` package.
___
*[`build/docs/proto-gen.go` line 139 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34Byb-eOGTuoSLRzo:-NY34Byb-eOGTuoSLRzp:b-toh0ji) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L139)):*
> ```Go
> 			--proto_path "proto" \
> 			--proto_path "third_party/proto" \
> 			--doc_out=../docs/src/api \
> ```

If we already specify the output directory, then why do we need to copy all the protos?
___
*[`build/docs/proto-gen.go` line 141 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34M6b61Dh5NxY-Ygr:-NY34M6b61Dh5NxY-Ygs:b-t3nl82) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L141)):*
> ```Go
> 			--doc_out=../docs/src/api \
> 			--doc_opt=../docs/proto/protodoc-markdown.tmpl,api.md \
> 			$(find "proto/coreum" -maxdepth 5 -name '*.proto') \
> ```

Presonaly I would prefer to find those files in go and pass as a list of arguments here. Bash is an evil.
___
*[`build/docs/proto-gen.go` line 148 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34ZEE90wZaNIoxPk2:-NY34ZEE90wZaNIoxPk3:b5r75s1) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L148)):*
> ```Go
> 	cmd.Stderr = os.Stderr
> 
> 	return cmd.Run()
> ```

Check calls to `libexec.Exec` it already covers all the edge cases
___
*[`build/tools/tools.go` line 660 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY31s2sBnCJ8IeGYyN4:-NY31s2sBnCJ8IeGYyN5:b-ywxm06) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/tools/tools.go#L660)):*
> ```Go
> 
> // CopyDir copies a whole directory recursively.
> func CopyDir(src string, dst string) (err error) {
> ```

Consider using https://github.com/otiai10/copy
It covers all the edge cases already
___
*[`build/tools/tools.go` line 681 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY31K1n7QocDPdC9f0z:-NY31K1o2Gke947mC04F:biwmkwp) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/tools/tools.go#L681)):*
> ```Go
> 
> 		if dirEntry.IsDir() {
> 			if err = CopyDir(srcFilePath, dstFilePath); err != nil {
> ```

I would prefer to use stack here, instead of recursion. In case of problems generated call stack might be hard to understand and debug.


<!-- Sent from Reviewable.io -->

2023-06-16 13:37 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 16 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY3Pm1L31-JwvOy6zbV:-NY3Pm1L31-JwvOy6zbW:b-6o59vt) (no related file):*
Tried to run it and got error:
```
2023/06/16 16:27:48 open ../docs/proto/protodoc-markdown.tmpl: no such file or directory
--doc_out: protoc-gen-doc: Plugin failed with status code 1.
2023-06-16T16:27:48.025026+03:00        error   crust   docs/pr
```
Probably once you add `protoc` installation it will be resolved. 

___
___
*[`build/docs/proto-gen.go` line 136 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY33oX925czEAwrBE0c:-NY3NmfS87t5QueEDn8l:b-pbds9z) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L136)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ensure that `protoc` is installed by adding it to tools. Take a look how `golang.EnsureGo` works as an example. Also check how `go` binary is called in `golang` package.
</blockquote></details>

Agree. 
___
*[`build/tools/tools.go` line 660 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY3NFV53d4jLOgUA6kx:-NY3NFV53d4jLOgUA6ky:b-hd6tq1) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/tools/tools.go#L660)):*
> ```Go
> 
> // CopyDir copies a whole directory recursively.
> func CopyDir(src string, dst string) (err error) {
> ```

IMO this is the wrong place for the func. You use it in the `proto-gen.go` so can keep it here.


<!-- Sent from Reviewable.io -->

2023-06-16 13:48 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/docs/proto-gen.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY3SUnb4uuOClB-Ynk0:-NY3SUnb4uuOClB-Ynk1:bi7kqdp) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L140)):*
> ```Go
> 			--proto_path "third_party/proto" \
> 			--doc_out=../docs/src/api \
> 			--doc_opt=../docs/proto/protodoc-markdown.tmpl,api.md \
> ```

The `protodoc-markdown.tmpl,` should be in the crust IMO.


<!-- Sent from Reviewable.io -->

2023-06-20 06:34 UTC, miladz68 approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 17 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-20 06:34 UTC, miladz68 approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 17 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-22 09:01 UTC, miladz68 reviewed
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-22 11:18 UTC, wojtek-coreum requested changes
> Reviewed 11 of 12 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 26 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/go.mod` line 16 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXa9bJ49vnPqN0yv4j:-NYXa9bJ49vnPqN0yv4k:ben2xe3) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/go.mod#L16)):*
> ```XML
> 	github.com/CoreumFoundation/coreum v1.0.1-0.20230413103107-4d8b6d562037
> 	github.com/CoreumFoundation/coreum-tools v0.4.0
> 	github.com/mholt/archiver/v3 v3.5.1
> ```

It is not used anywhere
___
*[`build/docs/proto-gen.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY3582a8l0s22OdSI0n:-NYXaz-003w1aI6FxWH6:b70i5u) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L34)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Done
</blockquote></details>

as the first line in the function please, to make it easier to find what the action depends on
___
*[`build/docs/proto-gen.go` line 148 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NY34ZEE90wZaNIoxPk2:-NYXluQi2AcwhwN0-N1T:b-7cp960) ([raw file](https://github.com/CoreumFoundation/crust/blob/203426018112ded549dcb4f852eaf5fd1c6600df/build/docs/proto-gen.go#L148)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

UPD:
Didn't manage to use `cmd := exec.Command(tools.Path("bin/protoc", tools.PlatformLocal), args...)` in `executeProtocCommand` function, command fails with files not found. Left it with cmd := exec.Command("sh", "-c", strings.Join(command, " ")) for now and switched to CI integration.
</blockquote></details>

Then there is some hidden problem, let's find it and solve :-)
___
*[`build/docs/proto-gen.go` line 33 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXbDkYBYmPJZR8DYVg:-NYXbDkYBYmPJZR8DYVh:b-vb0a0x) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L33)):*
> ```Go
> )
> 
> // Proto collects cosmos-sdk, cosmwasm and tendermint proto files from coreum go.mod,
> ```

IMO it is better to put this logic to existing `coreum` package rather than creating new `docs`
___
*[`build/docs/proto-gen.go` line 46 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXc6VMAUYY3J2ahv6k:-NYXc6VMAUYY3J2ahv6l:by0vgsn) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L46)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Error("failed to get modules versions", zap.Error(err))
> ```

modules versions -> module versions
___
*[`build/docs/proto-gen.go` line 46 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXcSK01F4r6_4pCczJ:-NYXcSK01F4r6_4pCczK:bs17pzc) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L46)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Error("failed to get modules versions", zap.Error(err))
> ```

Here and below: You don't need to log errors. Returned error is printed anyway somewhere up the call stack. To add additional info, just use `errors.Wrap`
___
*[`build/docs/proto-gen.go` line 66 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXdMbg0lEGD0Hw-Vxs:-NYXdMbg0lEGD0Hw-Vxt:b-hoohsr) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L66)):*
> ```Go
> 
> // getModuleVersions returns a map[moduleName]version.
> func getModuleVersions(deps build.DepsFunc, modules []string) (map[string]string, error) {
> ```

Move this function to `golang` package
___
*[`build/docs/proto-gen.go` line 67 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXd0jOAyHCxKnOedwE:-NYXd0jPBhjUEHG1aRL5:b-lid2aa) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L67)):*
> ```Go
> // getModuleVersions returns a map[moduleName]version.
> func getModuleVersions(deps build.DepsFunc, modules []string) (map[string]string, error) {
> 	moduleToVersion := make(map[string]string)
> ```

Minor: `make(map[string]string, len(modules))`
___
*[`build/docs/proto-gen.go` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXcs0XDvhhdXiIr7gu:-NYXcs0XDvhhdXiIr7gv:b-q8u5rh) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L69)):*
> ```Go
> 	moduleToVersion := make(map[string]string)
> 
> 	var version string
> ```

You don't need to declare these variables
___
*[`build/docs/proto-gen.go` line 84 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXdkrk4TbbYtuT-O6m:-NYXdkrk4TbbYtuT-O6n:b-2xegvb) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L84)):*
> ```Go
> 
> // getProtoDirs returns a list of absolute path to needed proto directories.
> func getProtoDirs(modulesMap map[string]string) ([]string, error) {
> ```

modulesMap -> moduleMap 
___
*[`build/docs/proto-gen.go` line 85 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXi-9s4yYWKy_E_GGn:-NYXdFcf70SWp0Un2f8P:b-r6vc12) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L85)):*
> ```Go
> // getProtoDirs returns a list of absolute path to needed proto directories.
> func getProtoDirs(modulesMap map[string]string) ([]string, error) {
> 	goPath := os.Getenv("GOPATH")
> ```

Now I see there is exactly same code in `golang/go.go`. Please create a function there doing this
___
*[`build/docs/proto-gen.go` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXdolL1yIf9eQ64xER:-NYXdolL1yIf9eQ64xES:b-6lzlzx) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L99)):*
> ```Go
> 	}
> 
> 	for module, version := range modulesMap {
> ```

`modulesMap` is a map so you don't need to iterate over all the items. Just retrieve values for keys you are interested in
___
*[`build/docs/proto-gen.go` line 115 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXhIo36KrbfFqjYY9K:-NYXhIo36KrbfFqjYY9L:b2lepvi) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L115)):*
> ```Go
> // executeProtocCommand ensures needed dependencies, composes the protoc command and executes it.
> func executeProtocCommand(ctx context.Context, deps build.DepsFunc, pathList []string) error {
> 	err := golang.EnsureProtoc(ctx, deps)
> ```

protoc has nothing to do with `golang` so this function should not be there. You might move it to `tools`
___
*[`build/docs/proto-gen.go` line 115 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXhVtw7-98e9Z_ZFC4:-NYXhVtw7-98e9Z_ZFC5:b-t3vsgc) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L115)):*
> ```Go
> // executeProtocCommand ensures needed dependencies, composes the protoc command and executes it.
> func executeProtocCommand(ctx context.Context, deps build.DepsFunc, pathList []string) error {
> 	err := golang.EnsureProtoc(ctx, deps)
> ```

`deps(golang.EnsureProtoc, golang.EnsureProtocGenDoc)`
___
*[`build/docs/proto-gen.go` line 120 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXhRaf974h4d0fDooo:-NYXhRaf974h4d0fDoop:b-arzl3p) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L [...]

2023-06-23 10:47 UTC, wojtek-coreum requested changes
> Reviewed 10 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/proto-gen.go` line 49 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbpRws0TH7obAYX5h5:-NYbpRws0TH7obAYX5h6:b3f5jy5) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/coreum/proto-gen.go#L49)):*
> ```Go
> }
> 
> // getProtoDirs returns a list of absolute path to needed proto directories.
> ```

absolute path -> absolute paths
___
*[`build/coreum/proto-gen.go` line 62 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbpc0l9QwkjqG3BdRJ:-NYbpc0l9QwkjqG3BdRK:b-9gfnh4) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/coreum/proto-gen.go#L62)):*
> ```Go
> 	}
> 
> 	cosmosSdkVersion := moduleMap[cosmosSdkModule]
> ```

Please return an error if entry does not exist
___
*[`build/coreum/proto-gen.go` line 82 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbpw8y8hDcS3A6IYYO:-NYbpw8y8hDcS3A6IYYP:bdpdkro) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/coreum/proto-gen.go#L82)):*
> ```Go
> 
> 	for _, path := range pathList {
> 		args = append(args, "--proto_path", fmt.Sprintf("\"%s\"", path))
> ```

You don't need `fmt.Sprintf("\"%s\"", path)` - `exec.Command` obfuscates and quotes arguments for you. Probably this is why you get error related to missing directories.
___
*[`build/coreum/proto-gen.go` line 94 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbqGe5Exr8VdBdp0zs:-NYbqGe5Exr8VdBdp0zt:b6n509m) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/coreum/proto-gen.go#L94)):*
> ```Go
> 	cmd := exec.Command(tools.Path("bin/protoc", tools.PlatformLocal), args...)
> 
> 	// Replace cmd := exec.Command(tools.Path("bin/protoc", tools.PlatformLocal), args...) with the following lines to get working code.
> ```

Just a reminder to remove this commented code
___
*[`build/golang/go.go` line 403 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbo0IIASPGN3MYIQAA:-NYbo0IIASPGN3MYIQAB:bz9yohm) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/golang/go.go#L403)):*
> ```Go
> 
> // GetGopath returns $GOPATH.
> func GetGopath() string {
> ```

GetGopath -> GoPath
___
*[`build/tools/tools.go` line 670 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYboH7P1lH2HMDdSaG1:-NYboH7P1lH2HMDdSaG2:b-xlt8v3) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/tools/tools.go#L670)):*
> ```Go
> 		destPath := filepath.Join(path, zf.Name)
> 
> 		if !zf.FileInfo().IsDir() {
> ```

Minor: 

```go
if zf.FileInfo().IsDir() {
    continue
}
```

It's not important but saving on indentation makes code more readable
___
*[`build/docs/proto-gen.go` line 69 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYXcs0XDvhhdXiIr7gu:-NYbqaz58dnekwZhcgan:b-l5918l) ([raw file](https://github.com/CoreumFoundation/crust/blob/3ac72173507e622572d2b8838d8150f1897ac392/build/docs/proto-gen.go#L69)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

In this case, they will be defined every time we go through the loop iteration, or do I have outdated knowledge? 
</blockquote></details>

Yes, they will be and usually it's a good thing because you re protected against them containing some outdated data (not so important here)


<!-- Sent from Reviewable.io -->

2023-06-23 11:22 UTC, wojtek-coreum requested changes
> Reviewed 1 of 12 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/golang/go.go` line 403 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/225#-NYbo0IIASPGN3MYIQAA:-NYbzEOMDX35Nwtxkplk:bjwbhj2) ([raw file](https://github.com/CoreumFoundation/crust/blob/91e3094c81cf0c10350e9db4a954f7eb7e2e2ce4/build/golang/go.go#L403)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Renamed
</blockquote></details>

But you should avoid "Get" - according to some naming standards in go


<!-- Sent from Reviewable.io -->

2023-06-23 11:37 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-23 14:53 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-23 14:53 UTC, dzmitryhil submitted a review, later dismissed
> Reviewed 2 of 12 files at r2, 7 of 12 files at r5, 1 of 1 files at r6, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-26 11:12 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2023-06-26 11:37 UTC, merged