Generate go code from proto files
CoreumFoundation/crust pull request #271
Opened 2023-08-11 13:15 UTC by wojtek-coreum

- Generate go code from proto files
- Extend crust to install tools based on the go package because some providers don't share precompiled binaries

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2023-08-14 17:07 UTC, miladz68 approved these changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-08-16 09:16 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NbodQyuC1saUUOHI9dg:-NbxRq5h9V-C6K5bpFyc:b-vow2dz) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The fixmes you left `FIXME (wojtek)`, are they supposed to be fixed in this PR ?
</blockquote></details>

There is one. No, if the approach presented in this PR is accepted, I will go with automatic generation of needed files later

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NbomgnsBR_etGJONz9r:-NbxSYqt4mNfMnh3f0SP:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I appreciate if you can put more detailed description of PR
I think it is worth mentioning because this PR is a bit complicated to understand right away
</blockquote></details>

Done.

___
___
*[`build/coreum/generate-proto-docs.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NboZjsGB-qyZPxgGvev:-NbxU6Y_5gRwLaSXTte_:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/5a9758278558b65935e7819e2780f5f60da5526d/build/coreum/generate-proto-docs.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you pls explain what is done inside this loop ?

I guess leaving it as comment makes sense
</blockquote></details>

Done.
___
*[`build/golang/go.go` line 412 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/271#-Nbok_UQ8qjh39q7sWHc:-NbxWytD8yUpLb5V4PoE:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/5a9758278558b65935e7819e2780f5f60da5526d/build/golang/go.go#L412)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: 
here you can use `-json` flag to get it in json format 

e.g
```
go list -json -m cosmossdk.io/api

{
	"Path": "cosmossdk.io/api",
	"Version": "v0.2.6",
	"Time": "2022-12-08T19:58:56Z",
	"Indirect": true,
	"Dir": "/Users/yaroslavsavchuk/go/pkg/mod/cosmossdk.io/api@v0.2.6",
	"GoMod": "/Users/yaroslavsavchuk/go/pkg/mod/cache/download/cosmossdk.io/api/@v/v0.2.6.mod",
	"GoVersion": "1.19"
}
```
</blockquote></details>

Done
___
*[`build/tools/goinstall.go` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NbodZ1Q2vkKD_zoJ8Oj:-NbxRdNgAGpG1HA2bRjl:b-sqp9n0) ([raw file](https://github.com/CoreumFoundation/crust/blob/5a9758278558b65935e7819e2780f5f60da5526d/build/tools/goinstall.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the trick of this file ?
</blockquote></details>

https://github.com/golang/go/issues/25922


<!-- Sent from Reviewable.io -->

2023-08-16 09:44 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: 4 of 14 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NboZN9m8-sNX3J3q1Up:-Nbxit5dESkd9cSExW5b:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Got error when trying `go generate`
```
2023-08-14T17:00:46.07571+02:00	info	crust	golang/go.go:349	Running go mod tidy	{"path": "../coreum"}
2023-08-14T17:00:47.630591+02:00	info	crust	golang/go.go:349	Running go mod tidy	{"path": "../coreum/integration-tests"}
2023-08-14T17:00:48.089167+02:00	info	crust	tools/tools.go:514	Installing binaries	{"tool": "protoc", "version": "v24.0", "url": "https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-osx-aarch_64.zip", "platform": "darwin.arm64"}
2023-08-14T17:00:51.008636+02:00	info	crust	tools/tools.go:559	Binary installed to path	{"tool": "protoc", "version": "v24.0", "url": "https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-osx-aarch_64.zip", "platform": "darwin.arm64", "path": "/Users/yaroslavsavchuk/Library/Caches/crust/bin/darwin.arm64/bin/protoc"}
2023-08-14T17:00:51.008666+02:00	info	crust	tools/tools.go:562	Binaries installed	{"tool": "protoc", "version": "v24.0", "url": "https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-osx-aarch_64.zip", "platform": "darwin.arm64"}
/Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/msg/v1/msg.proto: Input is shadowed in the --proto_path by "/Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto".  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.
2023-08-14T17:00:52.164298+02:00	error	crust	run/run.go:71	Application returned error: exit status 1: "/Users/yaroslavsavchuk/Library/Caches/crust/bin/darwin.arm64/downloads/protoc-v24.0/bin/protoc --doc_out=docs --doc_opt=docs/api.tmpl.md,api.md --proto_path /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/token.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/types.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/delay/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/amino/amino.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/runtime/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/config.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/auth.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/event.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/options.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/bank.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/abci/v1beta1/abci.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/kv/v1beta1/kv.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/node/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/query/v1beta1/pagination.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.4 [...]

2023-08-16 10:00 UTC, ysv requested changes
> Reviewed 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NboZN9m8-sNX3J3q1Up:-NbxlrPh3NnAE1x-2q7X:b-6kbo0t) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still having an issue but different one:

crust version: 722ac5f
```
crust generate
2023-08-16T11:56:17.996107+02:00	info	crust	golang/go.go:342	Running go mod tidy	{"path": "../coreum"}
2023-08-16T11:56:18.29597+02:00	info	crust	golang/go.go:342	Running go mod tidy	{"path": "../coreum/integration-tests"}
/Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/msg/v1/msg.proto: Input is shadowed in the --proto_path by "/Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto".  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.
2023-08-16T11:56:18.479585+02:00	error	crust	run/run.go:71	Application returned error: exit status 1: "/Users/yaroslavsavchuk/Library/Caches/crust/bin/darwin.arm64/downloads/protoc-v24.0/bin/protoc --doc_out=docs --doc_opt=docs/api.tmpl.md,api.md --proto_path /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/token.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/types.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/delay/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/amino/amino.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/runtime/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/config.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/auth.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/event.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/options.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/bank.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/abci/v1beta1/abci.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/kv/v1beta1/kv.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/node/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/query/v1beta1/pagination.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/reflection/v1beta1/reflection.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/reflection/v2alpha1/reflection.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/snapshots/v1beta1/snapshot.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/store/v1beta1/commit_info.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/store/v1beta1/listening.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/tendermint/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cos [...]

2023-08-16 10:30 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NboZN9m8-sNX3J3q1Up:-NbxtQRp8CiNC95oIYZE:b4b20ul) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Still having an issue but different one:

crust version: 722ac5f
```
crust generate
2023-08-16T11:56:17.996107+02:00	info	crust	golang/go.go:342	Running go mod tidy	{"path": "../coreum"}
2023-08-16T11:56:18.29597+02:00	info	crust	golang/go.go:342	Running go mod tidy	{"path": "../coreum/integration-tests"}
/Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/msg/v1/msg.proto: Input is shadowed in the --proto_path by "/Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto".  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.
2023-08-16T11:56:18.479585+02:00	error	crust	run/run.go:71	Application returned error: exit status 1: "/Users/yaroslavsavchuk/Library/Caches/crust/bin/darwin.arm64/downloads/protoc-v24.0/bin/protoc --doc_out=docs --doc_opt=docs/api.tmpl.md,api.md --proto_path /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto --proto_path /Users/yaroslavsavchuk/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/token.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/ft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/asset/nft/v1/types.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/customparams/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/delay/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/params.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/feemodel/v1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/event.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/genesis.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/nft.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/query.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/coreum/nft/v1beta1/tx.proto /Users/yaroslavsavchuk/Developer/CoreumFoundation/coreum/proto/cosmos/msg/v1/msg.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/amino/amino.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/runtime/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/config.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/app/v1alpha1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/auth.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/auth/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/event.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/authz/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/options.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/autocli/v1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/module/v1/module.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/authz.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/bank.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/genesis.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/bank/v1beta1/tx.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/abci/v1beta1/abci.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/kv/v1beta1/kv.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/node/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/query/v1beta1/pagination.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/reflection/v1beta1/reflection.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/reflection/v2alpha1/reflection.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/snapshots/v1beta1/snapshot.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/store/v1beta1/commit_info.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/store/v1beta1/listening.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/tendermint/v1beta1/query.proto /Users/yaroslavsavchuk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/proto/cosmos/base/tendermint/v1beta1/types.proto /Users/yaroslavsavchuk/go/pkg/mod/githu [...]

2023-08-16 10:41 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/271)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NbodQyuC1saUUOHI9dg:-Nbxvy5W-1YSctT2NDEr:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see 2 of them
commented there

As for this one I'm ok to leave it but lets discuss and create follow up task
</blockquote></details>

Done.

___
___
*[`build/coreum/generate-proto-go.go` line 92 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/271#-NbxmDhIBmuxYsa7dTIT:-NbxvypgCRRRvIDtIs3G:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/722ac5fc91dd070a0fc52b0383adc2abec92bc42/build/coreum/generate-proto-go.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about this fixme ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-17 07:19 UTC, closed without merging