Integrate bridge relayers into znet
CoreumFoundation/crust pull request #357
Opened 2024-02-06 14:12 UTC by wojtek-coreum

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/crust/357)

2024-02-09 11:34 UTC, miladz68 approved these changes
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`infra/apps/profiles.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqCHwPZ9UjUrtGmLQ3L:-NqCHwPZ9UjUrtGmLQ3M:bb7phvt) ([raw file](https://github.com/CoreumFoundation/crust/blob/5b74ffc965ba51065cddb53350605d1d2c689236/infra/apps/profiles.go#L31)):*
> ```Go
> 	AppPrefixMonitoring = "monitoring"
> 	AppPrefixXRPL       = "xrpl"
> 	AppPrefixBrisgeXRPL = "bridge-xrpl"
> ```

typo


<!-- Sent from Reviewable.io -->

2024-02-12 10:06 UTC, miladz68 submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)



<!-- Sent from Reviewable.io -->

2024-02-12 11:45 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 63 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS6NnU7kOxjP9gk8Mz:-NqS6NnU7kOxjP9gk8N-:blzvog4) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L63)):*
> ```Go
> // New creates new cored app.
> func New(cfg Config) (Bridge, error) {
> 	genesisConfig := cfg.Cored.Config().GenesisInitConfig
> ```

IMO that approach is bad practice, to allow the components to mutate the state of each other. 
@ysv @miladz68 WDYT ?
Why don't you use the faucet account to fund the accounts after the coreum deployment, for example in the same part where you deeply the contract? 
___
*[`infra/apps/bridgexrpl/bridge.go` line 65 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS7BQt-IJqdDOEFK7_:-NqS7BQt-IJqdDOEFK7a:bhhoj6b) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L65)):*
> ```Go
> 	genesisConfig := cfg.Cored.Config().GenesisInitConfig
> 
> 	if cfg.Leader == nil {
> ```

When the `Leader` is nil ?
___
*[`infra/apps/bridgexrpl/bridge.go` line 126 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS6llI7GUwpm3Uiq-z:-NqS6llI7GUwpm3Uiq0-:b566l9m) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L126)):*
> ```Go
> 	d := infra.Deployment{
> 		RunAsUser: true,
> 		Image:     "coreumbridge-xrpl-relayer:local",
> ```

Is that name is the result of the build form the bridge makefile?
___
*[`infra/apps/bridgexrpl/xrpl/client.go` line 2 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS7_6j2_3u_4NuzaHt:-NqS7_6j2_3u_4NuzaHu:bhs30vs) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/xrpl/client.go#L2)):*
> ```Go
> //nolint:tagliatelle // json naming
> package xrpl
> ```

Do you copy the code to avoid the bridge import?
___
*[`infra/apps/bridgexrpl/xrpl/client.go` line 187 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS5ijSALjGkURaJ5NF:-NqS5ijSALjGkURaJ5NG:b-da7wv4) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/xrpl/client.go#L187)):*
> ```Go
> 		},
> 	}
> 	err := c.doJSON(ctx, http.MethodPost, request, func(resBytes []byte) error {
> ```

Don't we have the `doJSON(` in the `coreum-tools` ? Also IMO you don't need it here, you can use default HTTP client without the retry, since the network is stable.


<!-- Sent from Reviewable.io -->

2024-02-12 12:42 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 65 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS7BQt-IJqdDOEFK7_:-NqSKDqY2_rz_mYqB7Uu:bei8rnd) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

When the `Leader` is nil ?
</blockquote></details>

When the leader is created
___
*[`infra/apps/bridgexrpl/bridge.go` line 126 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS6llI7GUwpm3Uiq-z:-NqSKNNbDCl79Q1OcjzP:b2nign6) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L126)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is that name is the result of the build form the bridge makefile?
</blockquote></details>

yes
___
*[`infra/apps/bridgexrpl/xrpl/client.go` line 2 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS7_6j2_3u_4NuzaHt:-NqSKPLl83WO7pExeVPb:b1anr82) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/xrpl/client.go#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you copy the code to avoid the bridge import?
</blockquote></details>

yes, e should have a separate module/repo with xrpl client available and importent in boh places. And I can't import the bridge anyway because it's a private repo.
___
*[`infra/apps/bridgexrpl/xrpl/client.go` line 187 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS5ijSALjGkURaJ5NF:-NqSKaJi7LfB0uw5j8Gs:b-fl6et1) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/xrpl/client.go#L187)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't we have the `doJSON(` in the `coreum-tools` ? Also IMO you don't need it here, you can use default HTTP client without the retry, since the network is stable.
</blockquote></details>

I copied what I needed without thinking much. As I said, we should have an "official" xrpl client.


<!-- Sent from Reviewable.io -->

2024-02-14 07:28 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 15 of 25 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 63 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqS6NnU7kOxjP9gk8Mz:-NqaW3UZ6lBrgo_-kOnu:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/6c0762ad6a8e532fcbdb45f2a5ae235402f7be6f/infra/apps/bridgexrpl/bridge.go#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO that approach is bad practice, to allow the components to mutate the state of each other. 
@ysv @miladz68 WDYT ?
Why don't you use the faucet account to fund the accounts after the coreum deployment, for example in the same part where you deeply the contract?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 08:10 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 15 of 25 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqa_AQED21BEaPU-bbT:-NqaeSZO250rxVSDO05j:b-ses2ho) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The target brunch should be the `coreumbridge-xrpl` since the repo is private for now.
</blockquote></details>

who cares? Unless you use `--profiles=bridge-xrpl` everything works normally

___


<!-- Sent from Reviewable.io -->

2024-02-14 08:49 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 15 of 25 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqa_AQED21BEaPU-bbT:-NqanOgX2Kfxe_HFeKtN:b-ldyt49) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

who cares? Unless you use `--profiles=bridge-xrpl` everything works normally
</blockquote></details>

Make sense. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqanTRR-eL2UT6ffyYI:-NqanTRR-eL2UT6ffyYJ:behpacf) (no related file):*
When I run
```
crust build images && crust znet remove && crust znet start --profiles=bridge-xrpl --timeout-commit 0.3s
```

I get error:

``View build details: docker-desktop://dashboard/build/crust/crust0/cn4nag5yxh1o20ryxe4fvalp4
2024-02-14T11:48:50.106015+03:00        info    znet    infra/types.go:49       Staring AppSet deployment, apps: cored-00-val,xrpl-xrpl,bridge-xrpl-bridgexrpl-00,bridge-xrpl-bridgexrpl-01,bridge-xrpl-bridgexrpl-02
2024-02-14T11:48:50.106306+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106316+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106291+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106337+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106344+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.367377+03:00        info    znet.deploy.cored-00-val        infra/types.go:191      Docker image exists     {"image": "cored:znet"}
2024-02-14T11:48:50.367497+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T11:48:50.367503+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T11:48:50.368081+03:00        info    znet.deploy.xrpl-xrpl   infra/types.go:191      Docker image exists     {"image": "xrpllabsofficial/xrpld:2.0.0"}
2024-02-14T11:48:50.368122+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T11:48:50.368127+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T11:48:50.369974+03:00        info    znet.deploy.bridge-xrpl-bridgexrpl-02   infra/types.go:191      Docker image exists     {"image": "coreumbridge-xrpl-relayer:local"}
2024-02-14T11:48:50.370135+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T11:48:50.370154+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val"]}
2024-02-14T11:48:50.37018+03:00 info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T11:48:50.393972+03:00        error   znet    run/run.go:71   Application returned error: fork/exec /Users/dzmitryhil/go/src/github.com/CoreumFoundation/crust/bin/.cache/cored/docker.linux.arm64/bin/cored: exec format error
github.com/CoreumFoundation/coreum-tools/pkg/libexec.Exec
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/libexec/exec.go:48
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.SaveGenesis
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:583
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.prepare
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:491
github.com/CoreumFoundation/crust/infra.Deployment.preprocess
        github.com/CoreumFoundation/crust/infra/types.go:357
github.com/CoreumFoundation/crust/infra.Deployment.Deploy
        github.com/CoreumFoundation/crust/infra/types.go:326
github.com/CoreumFoundation/crust/infra.AppSet.Deploy.func2.1
        github.com/CoreumFoundation/crust/infra/types.go:128
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.prepare
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:492
github.com/CoreumFoundation/crust/infra.Deployment.preprocess
        github.com/CoreumFoundation/crust/infra/types.go:357
github.com/CoreumFoundation/crust/infra.Deployment.Deploy
        github.com/CoreumFoundation/crust/infra/types.go:326
github.com/CoreumFoundation/crust/infra.AppSet.Deploy.func2.1
        github.com/CoreumFoundation/crust/infra/types.go:128
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/coreum-tools/pkg/run.run
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:71
github.com/CoreumFoundation/coreum-tools/pkg/run.Tool
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:32
main.main
        github.com/CoreumFoundation/crust/cmd/znet/main.go:24
runtime.main
        runtime/proc.go:267
`

```
```


___


<!-- Sent from Reviewable.io -->

2024-02-14 08:57 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 15 of 25 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqanTRR-eL2UT6ffyYI:-NqapOkCAkTLFxFSg3MD:b37gcvg) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

When I run
```
crust build images && crust znet remove && crust znet start --profiles=bridge-xrpl --timeout-commit 0.3s
```

I get error:

``View build details: docker-desktop://dashboard/build/crust/crust0/cn4nag5yxh1o20ryxe4fvalp4
2024-02-14T11:48:50.106015+03:00        info    znet    infra/types.go:49       Staring AppSet deployment, apps: cored-00-val,xrpl-xrpl,bridge-xrpl-bridgexrpl-00,bridge-xrpl-bridgexrpl-01,bridge-xrpl-bridgexrpl-02
2024-02-14T11:48:50.106306+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106316+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106291+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106337+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.106344+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T11:48:50.367377+03:00        info    znet.deploy.cored-00-val        infra/types.go:191      Docker image exists     {"image": "cored:znet"}
2024-02-14T11:48:50.367497+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T11:48:50.367503+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T11:48:50.368081+03:00        info    znet.deploy.xrpl-xrpl   infra/types.go:191      Docker image exists     {"image": "xrpllabsofficial/xrpld:2.0.0"}
2024-02-14T11:48:50.368122+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T11:48:50.368127+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T11:48:50.369974+03:00        info    znet.deploy.bridge-xrpl-bridgexrpl-02   infra/types.go:191      Docker image exists     {"image": "coreumbridge-xrpl-relayer:local"}
2024-02-14T11:48:50.370135+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T11:48:50.370154+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val"]}
2024-02-14T11:48:50.37018+03:00 info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T11:48:50.393972+03:00        error   znet    run/run.go:71   Application returned error: fork/exec /Users/dzmitryhil/go/src/github.com/CoreumFoundation/crust/bin/.cache/cored/docker.linux.arm64/bin/cored: exec format error
github.com/CoreumFoundation/coreum-tools/pkg/libexec.Exec
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/libexec/exec.go:48
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.SaveGenesis
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:583
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.prepare
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:491
github.com/CoreumFoundation/crust/infra.Deployment.preprocess
        github.com/CoreumFoundation/crust/infra/types.go:357
github.com/CoreumFoundation/crust/infra.Deployment.Deploy
        github.com/CoreumFoundation/crust/infra/types.go:326
github.com/CoreumFoundation/crust/infra.AppSet.Deploy.func2.1
        github.com/CoreumFoundation/crust/infra/types.go:128
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/crust/infra/apps/cored.Cored.prepare
        github.com/CoreumFoundation/crust/infra/apps/cored/cored.go:492
github.com/CoreumFoundation/crust/infra.Deployment.preprocess
        github.com/CoreumFoundation/crust/infra/types.go:357
github.com/CoreumFoundation/crust/infra.Deployment.Deploy
        github.com/CoreumFoundation/crust/infra/types.go:326
github.com/CoreumFoundation/crust/infra.AppSet.Deploy.func2.1
        github.com/CoreumFoundation/crust/infra/types.go:128
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/coreum-tools/pkg/run.run
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:71
github.com/CoreumFoundation/coreum-tools/pkg/run.Tool
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:32
main.main
        github.com/CoreumFoundation/crust/cmd/znet/main.go:24
runtime.main
        runtime/proc.go:267
`

```
```

</blockquote></details>

ohhh... another bug related to the new mechanism of genesis generation

___


<!-- Sent from Reviewable.io -->

2024-02-14 09:45 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 14 of 26 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqanTRR-eL2UT6ffyYI:-Nqb-QPi4JIQo-82j9il:b-hmo1c7) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ohhh... another bug related to the new mechanism of genesis generation
</blockquote></details>

For no, I rolled back to the old genesis generation mechanism

___


<!-- Sent from Reviewable.io -->

2024-02-14 10:16 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 14 of 26 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqanTRR-eL2UT6ffyYI:-Nqb6UDN1ElmOOF_4EqP:b-mjddls) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For no, I rolled back to the old genesis generation mechanism
</blockquote></details>

New error now:

```
➜  crust git:(wojtek/znet-bridge) ✗ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
➜  crust git:(wojtek/znet-bridge) ✗ crust znet remove && crust znet start --profiles=bridge-xrpl --timeout-commit 0.3s
2024-02-14T13:15:39.524712+03:00        info    znet.container.366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940 targets/docker.go:109   Deleting container      {"id": "366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940", "name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:39.525126+03:00        info    znet.container.9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4 targets/docker.go:109   Deleting container      {"id": "9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4", "name": "znet-cored-00-val", "appName": "cored-00-val"}
2024-02-14T13:15:39.623886+03:00        info    znet.container.9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4 targets/docker.go:115   Container deleted       {"id": "9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4", "name": "znet-cored-00-val", "appName": "cored-00-val"}
2024-02-14T13:15:39.630528+03:00        info    znet.container.366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940 targets/docker.go:115   Container deleted       {"id": "366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940", "name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:39.734791+03:00        info    znet    targets/docker.go:267   Deleting docker network {"network": "znet"}
2024-02-14T13:15:39.834622+03:00        info    znet    targets/docker.go:273   Docker network deleted  {"network": "znet"}
2024-02-14T13:15:40.685239+03:00        info    znet    infra/types.go:49       Staring AppSet deployment, apps: cored-00-val,xrpl-xrpl,bridge-xrpl-bridgexrpl-00,bridge-xrpl-bridgexrpl-01,bridge-xrpl-bridgexrpl-02
2024-02-14T13:15:40.686013+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.68603+03:00 info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686072+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686127+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686197+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:41.062566+03:00        info    znet.deploy.cored-00-val        infra/types.go:191      Docker image exists     {"image": "cored:znet"}
2024-02-14T13:15:41.062702+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T13:15:41.062717+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T13:15:41.064769+03:00        info    znet.deploy.bridge-xrpl-bridgexrpl-02   infra/types.go:191      Docker image exists     {"image": "coreumbridge-xrpl-relayer:local"}
2024-02-14T13:15:41.064846+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T13:15:41.064862+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val"]}
2024-02-14T13:15:41.064868+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T13:15:41.066028+03:00        info    znet.deploy.xrpl-xrpl   infra/types.go:191      Docker image exists     {"image": "xrpllabsofficial/xrpld:2.0.0"}
2024-02-14T13:15:41.066042+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T13:15:41.066046+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T13:15:41.110761+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:241   Creating docker network {"network": "znet"}
2024-02-14T13:15:41.185256+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:247   Docker network created  {"network": "znet"}
2024-02-14T13:15:41.267543+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:150   Starting container      {"name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:41.340819+03:00        info    znet.deploy.cored-00-val        targets/docker.go:150   Starting container      {"name": "znet-cored-00-val", "appName": "cored-00-val"}
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Ports are not available: exposing port TCP 172.20.0.1:5005 -> 0.0.0.0:0: listen tcp 172.20.0.1:5005: bind: can't assign requested address.
2024-02-14T13:15:41.549213+03:00        error   znet    run/run.go:71   Application returned error: exit status 125: "/usr/local/bin/docker run --name znet-xrpl-xrpl -d --label com.coreum.crust.znet.env=znet --label com.coreum.crust.znet.app=xrpl-xrpl --network znet --user 501:20 -p 127.0.0.1:5005:5005/tcp -p 172.20.0.1:5005:5005/tcp -p 127.0.0.1:6006:6006/tcp -p 172.20.0.1:6006:6006/tcp -v /Users/dzmitryhil/Library/Caches/crust/znet/znet/app/xrpl-xrpl:/app --entrypoint /app/run.sh xrpllabsofficial/xrpld:2.0.0"
github.com/CoreumFoundation/coreum-tools/pkg/libexec.Exec.func1.1
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/libexec/exec.go:58
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/coreum-tools/pkg/run.run
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:71
github.com/CoreumFoundation/coreum-tools/pkg/run.Tool
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:32
main.main
        github.com/CoreumFoundation/crust/cmd/znet/main.go:24
runtime.main
        runtime/proc.go:267

```

___


<!-- Sent from Reviewable.io -->

2024-02-14 10:29 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 14 of 26 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/357#-NqanTRR-eL2UT6ffyYI:-Nqb8wil2EsrzlAbSqOi:b-aem68z) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

New error now:

```
➜  crust git:(wojtek/znet-bridge) ✗ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
➜  crust git:(wojtek/znet-bridge) ✗ crust znet remove && crust znet start --profiles=bridge-xrpl --timeout-commit 0.3s
2024-02-14T13:15:39.524712+03:00        info    znet.container.366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940 targets/docker.go:109   Deleting container      {"id": "366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940", "name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:39.525126+03:00        info    znet.container.9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4 targets/docker.go:109   Deleting container      {"id": "9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4", "name": "znet-cored-00-val", "appName": "cored-00-val"}
2024-02-14T13:15:39.623886+03:00        info    znet.container.9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4 targets/docker.go:115   Container deleted       {"id": "9543017d7e744d36f974b94afe9dba776b2c2d898ebc63b11d42c6a3d0b3c4d4", "name": "znet-cored-00-val", "appName": "cored-00-val"}
2024-02-14T13:15:39.630528+03:00        info    znet.container.366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940 targets/docker.go:115   Container deleted       {"id": "366f5c695cbb022ce56a4bf14d65d13a0d9addee8ba0ec9e1599695b7518b940", "name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:39.734791+03:00        info    znet    targets/docker.go:267   Deleting docker network {"network": "znet"}
2024-02-14T13:15:39.834622+03:00        info    znet    targets/docker.go:273   Docker network deleted  {"network": "znet"}
2024-02-14T13:15:40.685239+03:00        info    znet    infra/types.go:49       Staring AppSet deployment, apps: cored-00-val,xrpl-xrpl,bridge-xrpl-bridgexrpl-00,bridge-xrpl-bridgexrpl-01,bridge-xrpl-bridgexrpl-02
2024-02-14T13:15:40.686013+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.68603+03:00 info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686072+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686127+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:40.686197+03:00        info    znet    infra/types.go:96       Deployment initialized
2024-02-14T13:15:41.062566+03:00        info    znet.deploy.cored-00-val        infra/types.go:191      Docker image exists     {"image": "cored:znet"}
2024-02-14T13:15:41.062702+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T13:15:41.062717+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T13:15:41.064769+03:00        info    znet.deploy.bridge-xrpl-bridgexrpl-02   infra/types.go:191      Docker image exists     {"image": "coreumbridge-xrpl-relayer:local"}
2024-02-14T13:15:41.064846+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T13:15:41.064862+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val"]}
2024-02-14T13:15:41.064868+03:00        info    znet    infra/types.go:108      Waiting for dependencies        {"dependencies": ["xrpl-xrpl", "cored-00-val", "bridge-xrpl-bridgexrpl-00"]}
2024-02-14T13:15:41.066028+03:00        info    znet.deploy.xrpl-xrpl   infra/types.go:191      Docker image exists     {"image": "xrpllabsofficial/xrpld:2.0.0"}
2024-02-14T13:15:41.066042+03:00        info    znet    infra/types.go:119      Waiting for free slot for deploying the application
2024-02-14T13:15:41.066046+03:00        info    znet    infra/types.go:126      Deployment started
2024-02-14T13:15:41.110761+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:241   Creating docker network {"network": "znet"}
2024-02-14T13:15:41.185256+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:247   Docker network created  {"network": "znet"}
2024-02-14T13:15:41.267543+03:00        info    znet.deploy.xrpl-xrpl   targets/docker.go:150   Starting container      {"name": "znet-xrpl-xrpl", "appName": "xrpl-xrpl"}
2024-02-14T13:15:41.340819+03:00        info    znet.deploy.cored-00-val        targets/docker.go:150   Starting container      {"name": "znet-cored-00-val", "appName": "cored-00-val"}
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Ports are not available: exposing port TCP 172.20.0.1:5005 -> 0.0.0.0:0: listen tcp 172.20.0.1:5005: bind: can't assign requested address.
2024-02-14T13:15:41.549213+03:00        error   znet    run/run.go:71   Application returned error: exit status 125: "/usr/local/bin/docker run --name znet-xrpl-xrpl -d --label com.coreum.crust.znet.env=znet --label com.coreum.crust.znet.app=xrpl-xrpl --network znet --user 501:20 -p 127.0.0.1:5005:5005/tcp -p 172.20.0.1:5005:5005/tcp -p 127.0.0.1:6006:6006/tcp -p 172.20.0.1:6006:6006/tcp -v /Users/dzmitryhil/Library/Caches/crust/znet/znet/app/xrpl-xrpl:/app --entrypoint /app/run.sh xrpllabsofficial/xrpld:2.0.0"
github.com/CoreumFoundation/coreum-tools/pkg/libexec.Exec.func1.1
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/libexec/exec.go:58
github.com/CoreumFoundation/coreum-tools/pkg/parallel.runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/recover.go:41
github.com/CoreumFoundation/coreum-tools/pkg/parallel.(*Group).runTask
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/parallel/group.go:121
runtime.goexit
        runtime/asm_arm64.s:1197
github.com/CoreumFoundation/coreum-tools/pkg/run.run
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:71
github.com/CoreumFoundation/coreum-tools/pkg/run.Tool
        github.com/CoreumFoundation/coreum-tools@v0.4.1-0.20230627094203-821c6a4eebab/pkg/run/run.go:32
main.main
        github.com/CoreumFoundation/crust/cmd/znet/main.go:24
runtime.main
        runtime/proc.go:267

```
</blockquote></details>

oh... macos. Then we need to discuss this

___


<!-- Sent from Reviewable.io -->

2024-02-14 11:35 UTC, miladz68 approved these changes
> Reviewed 6 of 8 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)



<!-- Sent from Reviewable.io -->

2024-02-15 13:57 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2024-02-15 14:15 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`infra/apps/bridgexrpl/relayer.tmpl.yaml` line 20 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6h-51I9oEuUiYiO-:-Nqh6h-51I9oEuUiYiO0:b-83lt8r) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/relayer.tmpl.yaml#L20)):*
> ```YAML
>     full_scan_enabled: true
>     repeat_full_scan: true
>     retry_delay: 10s
> ```

Update to 1s
___
*[`infra/apps/bridgexrpl/relayer.tmpl.yaml` line 37 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6j4xAK1ts5n8UjUX:-Nqh6j4xAK1ts5n8UjUY:b-83lt8r) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/relayer.tmpl.yaml#L37)):*
> ```YAML
> processes:
>   coreum_to_xrpl:
>     repeat_delay: 10s
> ```

Update to 1s


<!-- Sent from Reviewable.io -->

2024-02-15 14:18 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 106 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh7933BwVC5BnIhult:-Nqh7933BwVC5BnIhulu:b-g1zf0p) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/bridge.go#L106)):*
> ```Go
> 	return *b.contractAddr
> }
> ```

It would be nice to add a health check when you check that there are 250 available tickets in the contract, to do it you can use `available_tickets ` query.
That will give you the proof that relayers relay the transactions from and to Coreum. 
___
*[`infra/apps/bridgexrpl/bridge.go` line 404 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6zMx5ur5XpKje0Ty:-Nqh6zMx5ur5XpKje0Tz:b8csc1c) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/bridge.go#L404)):*
> ```Go
> 	logger.Get(ctx).Info("Contract address of the XRPL bridge", zap.String("contractAddress", contractAddr))
> 
> 	*b.contractAddr = contractAddr
> ```

After the instantiation you need to call tickets recovery from an owner

```
1.  Get account seq from the bridge XRPL address
2.  Call `recover_tickets` method with that seq and 250 tickets.
```


<!-- Sent from Reviewable.io -->

2024-02-15 15:10 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`infra/apps/bridgexrpl/relayer.tmpl.yaml` line 20 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6h-51I9oEuUiYiO-:-NqhJUB8C4Ql1ZryKPkG:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/relayer.tmpl.yaml#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update to 1s
</blockquote></details>

Done.
___
*[`infra/apps/bridgexrpl/relayer.tmpl.yaml` line 37 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6j4xAK1ts5n8UjUX:-NqhJUUXE8gQoz-5pX_E:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/relayer.tmpl.yaml#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update to 1s
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 08:08 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 106 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh7933BwVC5BnIhult:-NqkxU3iAx_2A8mTO2fA:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/bridge.go#L106)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to add a health check when you check that there are 250 available tickets in the contract, to do it you can use `available_tickets ` query.
That will give you the proof that relayers relay the transactions from and to Coreum.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 08:24 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 404 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6zMx5ur5XpKje0Ty:-Nql-bib897b52PAD6Ja:bv8npr2) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/bridge.go#L404)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

let's renamte `deploySmartContract` to `deployAndInitSmartContract`.
___
*[`infra/apps/bridgexrpl/bridge.go` line 137 at r11](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nql-vo28yr7dxTICe5l:-Nql-vo28yr7dxTICe5m:bcoyd28) ([raw file](https://github.com/CoreumFoundation/crust/blob/4c8fd44ec5adfacc9ddb5b2a818fdd898ec0fba2/infra/apps/bridgexrpl/bridge.go#L137)):*
> ```Go
> 	}
> 
> 	if len(ticketsResp.Tickets) < 250 {
> ```

Move the `250` to constant and reuse for the recovery and health check 


<!-- Sent from Reviewable.io -->

2024-02-16 08:38 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/bridgexrpl/bridge.go` line 404 at r9](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nqh6zMx5ur5XpKje0Ty:-Nql3AgJ3G3SbuQgFYYo:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/938b4434d521d857c4dc8a880a1e842e46b48065/infra/apps/bridgexrpl/bridge.go#L404)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

let's renamte `deploySmartContract` to `deployAndInitSmartContract`.
</blockquote></details>

Done.
___
*[`infra/apps/bridgexrpl/bridge.go` line 137 at r11](https://reviewable.io/reviews/CoreumFoundation/crust/357#-Nql-vo28yr7dxTICe5l:-Nql37SCE7oT9a6Ui05e:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/4c8fd44ec5adfacc9ddb5b2a818fdd898ec0fba2/infra/apps/bridgexrpl/bridge.go#L137)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Move the `250` to constant and reuse for the recovery and health check
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 08:53 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: 24 of 26 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2024-02-19 08:53 UTC, miladz68 approved these changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/357)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2024-02-19 10:48 UTC, merged