Revert to setting `cmd.Dir` in go commands
CoreumFoundation/crust pull request #385
Opened 2024-04-09 10:00 UTC by wojtek-coreum

# Description

The original way was there for purpose. If `cmd.Dir` is not set, `go.mod` for the main module is used by the `build` command instead of the one defined in the submodule.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

2024-04-09 10:06 UTC, ysv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv1JYKY2FASs8FkVmUN:b-tnnaw) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
> ```Go
> 
> 	cmd := exec.Command(tools.Path("bin/go", tools.TargetPlatformLocal), args...)
> 	cmd.Dir = config.PackagePath
> ```

this doesn't work properly, that is why I changed it


<!-- Sent from Reviewable.io -->

2024-04-09 10:15 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv1LEg58lb8-lNeozPh:b11h9kw) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
> this doesn't work properly, that is why I changed it

What didn't work?

> What are the benefits of this approach ?

This is how `go build` works. To use the correct `go.mod` you need to be in the right directory.
Try to run `bin/bdjuno-builder build/me` in the bdjuno repo.


<!-- Sent from Reviewable.io -->

2024-04-09 10:20 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv1M6by5xdaXP7uqJEr:ba26pg6) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
> What didn't work?

Test it in coreum repo with native build & in docker.
As far as I remember when building in docker it didn't work properly. Since it changes directory, so resulting binary was mounted to `build/cmd/bin/.cache/cored/docker.linux.arm64/bin/cored` instead of `bin/.cache/cored/docker.linux.arm64/bin/cored`. Smth like this


<!-- Sent from Reviewable.io -->

2024-04-09 10:49 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv1TY0G-EEdHU1eCVc1:b-cpcbei) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> What didn't work?

Test it in coreum repo with native build & in docker.
As far as I remember when building in docker it didn't work properly. Since it changes directory, so resulting binary was mounted to `build/cmd/bin/.cache/cored/docker.linux.arm64/bin/cored` instead of `bin/.cache/cored/docker.linux.arm64/bin/cored`. Smth like this
</blockquote></details>

I see path is correct


<!-- Sent from Reviewable.io -->

2024-04-09 10:54 UTC, miladz68 approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-09 11:12 UTC, dzmitryhil approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-09 13:12 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv1ygACBBRphNs_-nS8:b8by2cd) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see path is correct
</blockquote></details>

workDir = "<path-to-coreu>/build/cmd"

-o = "bin/.cache/..."

check:
`go build -o="bin/.cache"`


<!-- Sent from Reviewable.io -->

2024-04-09 13:20 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv2-xSt09j-2neh9F-c:bcavpu) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

workDir = "<path-to-coreu>/build/cmd"

-o = "bin/.cache/..."

check:
`go build -o="bin/.cache"`
</blockquote></details>

Discussed issue on call


<!-- Sent from Reviewable.io -->

2024-04-10 11:13 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/385#-Nv1JYKY2FASs8FkVmUM:-Nv6hctr070avMXZVUlH:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/0a67f05983fdd5c67c04c4f1fe5e1110bc4fcfdd/build/golang/go.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Discussed issue on call
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-10 11:26 UTC, dzmitryhil approved these changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2024-04-11 10:30 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/385)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)



<!-- Sent from Reviewable.io -->

2024-04-11 14:14 UTC, merged