WASM contracts subcommand
CoreumFoundation/crust pull request #41
Opened 2022-08-05 02:03 UTC by xlab

Depends on this PR from coreum (client was moved there)
https://github.com/CoreumFoundation/coreum/pull/123

For the feature list to check out and test, see [SMART_CONTRACTS.md](https://github.com/CoreumFoundation/crust/blob/f/wasm-contracts/SMART_CONTRACTS.md)

## Running WASM integration tests

```bash
> crust build
> crust znet test
```

## Deploying contracts manually on a znet

```bash
> crust znet start

# your path will vary there:
> export CRUST_KEYRING_DIR=/Users/xlab/Library/Caches/crust/znet/znet/app/coredev-00
> export CRUST_KEYRING_KEY_FROM=alice

> crust contracts deploy ...
```

2022-08-05 10:17 UTC, wojtek-coreum requested changes
> Reviewed 28 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 28 of 36 files reviewed, 22 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hET2x8NpTilPmKaEk:-N8hET2x8NpTilPmKaEl:b-lq93wj) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/.gitignore#L3)):*
> ```ignore
> .idea
> .vscode
> .DS_Store
> ```

Let's discuss this after the daily: https://reviewable.io/reviews/CoreumFoundation/crust/42#-
___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hEWod8LIJYu9CqHz-:-N8hEWod8LIJYu9CqHz0:b-10qvh6) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/.gitignore#L4)):*
> ```ignore
> .vscode
> .DS_Store
> /var
> ```

Whatever temporary files you need to store during building the contracts please place them under `os.UserCacheDir()+"/crust/contracts"` please
___
*[`SMART_CONTRACTS.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hEyof6YYYeg6Xw_QS:-N8hEyof6YYYeg6Xw_QT:b-tnon3l) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L13)):*
> ```Markdown
> And most importantly, make sure you have [crust](/README.md) installed properly and ready to be used for smartcontract operations.
> 
> ```bash
> ```

Here and in other places: `bash` is intended to format bash code, not the console output. Now it applies some colors to "random" words.
___
*[`SMART_CONTRACTS.md` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hF2Vd-Uzc3hAP8-oG:-N8hF2Vd-Uzc3hAP8-oH:b-1me16y) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L41)):*
> ```Markdown
> Creating a WASM-ready contract is just a bit more involved procedure, as compared to Solidity contracts, when you can have a single file and be happy. WASM contracts require to have Cargo configuration for dependency and target management, similar to NPM/YARN.
> 
> We are providing a template repo with bare minimum scaffolded code to help you be up and running with a new shiny contract. Crust provides an `contracts init` subcommand that clones the template into any target dir. Don't forget to specify a name!
> ```

repo -> repository
remove "shiny", it's a technical document, not a poem
___
*[`SMART_CONTRACTS.md` line 124 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFEtO0ZsiRc_NgqHV:-N8hFEtO0ZsiRc_NgqHW:b-t4gop4) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L124)):*
> If you are lucky

Maybe just "If you have". I don't feel to be lucky due to having linux installed.
___
*[`SMART_CONTRACTS.md` line 146 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFJ6t8losT-lyNNLK:-N8hFJ6t8losT-lyNNLL:b-d4dlbo) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L146)):*
> ```Markdown
> `crust contracts building`
> 
> Now, when it comes to building a smart-contract, there are two options and two workflows that are implemented in crust. First option will use your Rust environment to build a Release version of the smart-contract targeting WASM32. This mode doesn't need Docker, but the resulting artefact will be large and the build is not deterministic.
> ```

Something to discuss: do we need to support this use case? Maybe we could build only in docker? It seems to me that binary built outside the docker is useless, as @xlab argued it's non-deterministic and huge. So what's the point of having it?
___
*[`SMART_CONTRACTS.md` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFNpMAJQycjr66Zhs:-N8hFNpMAJQycjr66Zht:bwnu8op) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L211)):*
> ```Markdown
> ## Deploying a smart contract
> 
> WIP
> ```

What about the missing part?
___
*[`bin/crust` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFeHd0CC57AvfJyci:-N8hFeHd0CC57AvfJycj:b-h5wuot) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/bin/crust#L46)):*
> ```
>    "contracts")
>      if [ ! -f "$REPO/bin/.cache/contracts" ]; then
>        "$REPO/bin/.cache/crust" build/contracts
> ```

Compare with the current version in master. Now you need:

```bash
"$CRUST_BIN" build/contracts
```
___
*[`cmd/contracts/main.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hGYZ_ElWx1U9rGk2k:-N8hGYZ_ElWx1U9rGk2l:bxphug2) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/cmd/contracts/main.go#L30)):*
> ```Go
> 
> func main() {
> 	cmd.SetAccountPrefixes("core")
> ```

This is outdated, current version is:

```go
	network := app.NewNetwork(cored.CustomZNetNetworkConfig)
	network.SetupPrefixes()
```
___
*[`cmd/contracts/main.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hHPnk5weK8lRcZYF7:-N8hHPnk5weK8lRcZYF8:b-yma4zc) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/cmd/contracts/main.go#L128)):*
> ```Go
> }
> 
> func initRunE(ctx context.Context, initConfig *contracts.InitConfig) runE {
> ```

Related to all `*RunE` functions: Please assign each `args[x]` to a variable first, so it's easy to understand the meaning
___
*[`pkg/contracts/deploy.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hROql8Ow2mYFYF7un:-N8hROql8Ow2mYFYF7uo:bak9tbu) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/pkg/contracts/deploy.go#L28)):*
> ```Go
> )
> 
> const gasEstimationAdj = 1.5
> ```

gasEstimationAdj -> gasEstimationAdjustment
___
*[`pkg/contracts/docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hSQy5-ntysrsEaH1g:-N8hSQy5-ntysrsEaH1h:b448j6l) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/pkg/contracts/docker/Dockerfile#L1)):*
> ```Dockerfile
> # Dockerfile implements Rust-ready image with tarpaulin installed
> ```

Could you point me to the place where this Dockerfile is used, can't find it
___
*[`tests/wasm/simple_state.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hKktM7iX7tbTGVcn8:-N8hKktM7iX7tbTGVcn9:b-mgls62) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L43)):*
> ```Go
> 		networkConfig = contracts.ChainConfig{
> 			ChainID: string(chain.Network().ChainID()),
> 			// FIXME: Take this value from Network.InitialGasPrice() once Milad integrates it into crust
> ```

Required change has been integrated so you may apply it here
___
*[`tests/wasm/simple_state.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLCnN02LLydAKnEpQ:-N8hLCnN02LLydAKnEpR:b-25nxyk) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L48)):*
> ```Go
> 		}
> 
> 		// FIXME: if workdir for the test is fixed, we can avoid embedding & staging
> ```

Could you elaborate? What's the problem related to working dir?
___
*[`tests/wasm/simple_state.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLSD112rK6TbcmI-h:-N8hLSD112rK6TbcmI-i:bobd8pg) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L58)):*
> ```Go
> 
> 		stagedContractPath = filepath.Join(stagedContractsDir, "simple_state.wasm")
> 		if err := iou [...]

2022-08-05 13:38 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 28 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`tests/wasm/simple_state.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8iDWLN9GJLhPUAMm2u:-N8iDWLN9GJLhPUAMm2v:bkmitoy) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L69)):*
> ```Go
> 		expect := require.New(t)
> 
> 		testing.WaitUntilHealthy(ctx, t, 20*time.Second, chain)
> ```

`testing.WaitUntilHealthy` does not exist anymore and you need to remove this line (healthy state of node is ensured in different place, common to all the tests)


<!-- Sent from Reviewable.io -->

2022-08-05 15:45 UTC, xlab commented
*[`SMART_CONTRACTS.md` line 124 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFEtO0ZsiRc_NgqHV:-N8ifVuYBuARK01j8x0w:b27hp2u) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> If you are lucky

Maybe just "If you have". I don't feel to be lucky due to having linux installed.
</blockquote></details>

Initially, it was Linux specifically, those with Macs were unlucky. But yeah I agree it's now a norm to have this support.

It's seems that you are triggered by this readme ;) Chill man


<!-- Sent from Reviewable.io -->

2022-08-05 15:45 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 27 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hET2x8NpTilPmKaEk:-N8iemIA0PuyhMK52v6D:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/.gitignore#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's discuss this after the daily: https://reviewable.io/reviews/CoreumFoundation/crust/42#-
</blockquote></details>

Done.
___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hEWod8LIJYu9CqHz-:-N8iemxz-4u-AdBrmeEE:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/.gitignore#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Whatever temporary files you need to store during building the contracts please place them under `os.UserCacheDir()+"/crust/contracts"` please
</blockquote></details>

Done.
___
*[`SMART_CONTRACTS.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hEyof6YYYeg6Xw_QS:-N8ieqff4k5WVw4odspy:bxmabrk) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and in other places: `bash` is intended to format bash code, not the console output. Now it applies some colors to "random" words.
</blockquote></details>

It also applies colors to some flags, so it's easier to read.
If you don't want colors, just open `tmux` and use `less README.md`
___
*[`SMART_CONTRACTS.md` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hF2Vd-Uzc3hAP8-oG:-N8ifNRnB0Q_AmKGVyqX:bg52ck7) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

repo -> repository
remove "shiny", it's a technical document, not a poem
</blockquote></details>

Everyone's a critic.


<!-- Sent from Reviewable.io -->

2022-08-05 15:53 UTC, xlab commented
*[`cmd/contracts/main.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hHPnk5weK8lRcZYF7:-N8iha2E6USZmOVPZiSr:bixuibh) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/cmd/contracts/main.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Related to all `*RunE` functions: Please assign each `args[x]` to a variable first, so it's easy to understand the meaning
</blockquote></details>

it's clear from this



_Code quote:_
```Go
TargetDir = args[0]
```


<!-- Sent from Reviewable.io -->

2022-08-05 15:54 UTC, xlab commented
*[`cmd/contracts/main.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hHPnk5weK8lRcZYF7:-N8ihcuh9I4UHilubyCm:b33qwcq) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/cmd/contracts/main.go#L128)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

it's clear from this
</blockquote></details>

Also, the variable list is part of the original `cobra.Command.Use`


<!-- Sent from Reviewable.io -->

2022-08-05 16:02 UTC, xlab commented
*[`tests/wasm/simple_state.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLCnN02LLydAKnEpQ:-N8ijFyC2agsEdW1rwEl:bootz11) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you elaborate? What's the problem related to working dir?
</blockquote></details>

Workdir of the `crust znet test` and thus all tests there depends on the env, it's not fixed. 
So it's hard to use fixtures that are not staged.

If this is unplanned, then this comment might be removed and we continue to stage fixtures in temp dir.


<!-- Sent from Reviewable.io -->

2022-08-05 16:03 UTC, xlab commented
*[`tests/wasm/simple_state.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLSD112rK6TbcmI-h:-N8ijkRCEDjrX2SoKiCg:bbpywzm) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It shouldn't be done by storing the file. Instead, client should accept `[]byte` containing the smart contract and deploy it to the bockchain
</blockquote></details>

Contracts are wasm artifact produced by the build. Even if we move from fixtures to continuous build, those will be artifacts produced on the disk.


<!-- Sent from Reviewable.io -->

2022-08-05 16:06 UTC, xlab commented
*[`tests/wasm/simple_state.go` line 71 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hUCFvCOHP67ylKPa0:-N8ik6yO3_fxle7xNFMe:b2q9sxt) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`contracts.Deploy` is a good function for `crust contracts deploy` but not here.
Instead of doing it this way here, you should get a client by calling `chain.Client()` and call the appropriate method available there (this is the topic I covered in the other PR targeting the cient), accepting `[]byte` containing smart contract and deploying it.

Both intergation tests and `contracts.Deploy` internally should reuse that functionality provided by the client.
</blockquote></details>

I am reusing the same code that exits already for the integration tests now. There is no intention to reimplement the same logic twice. Also, the client is responsible for delivering txns on chain, not for the application logic and message formatting. 


<!-- Sent from Reviewable.io -->

2022-08-05 16:07 UTC, xlab commented
*[`tests/wasm/simple_state.go` line 81 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hUhe5BuZkuTH61ee_:-N8ikW6K3kH19D0n54Uv:b-1391ci) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L81)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do you deploy the contract for the second time? If those two deployments are here to test different cases, then it should be done using two different tests instead.
</blockquote></details>

This is a single deployment, done in 2 stages, so I can test intermediate results and provide more clarity if the test fails. Normally it would be a single command call.


<!-- Sent from Reviewable.io -->

2022-08-05 16:08 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 22 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`SMART_CONTRACTS.md` line 146 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFJ6t8losT-lyNNLK:-N8ifpflD9L5FnDBBec5:b-mlljba) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L146)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Something to discuss: do we need to support this use case? Maybe we could build only in docker? It seems to me that binary built outside the docker is useless, as @xlab argued it's non-deterministic and huge. So what's the point of having it?
</blockquote></details>

Building outside docker is like x10 times faster. Also, it still works (if you don't deploy it on prod)
___
*[`SMART_CONTRACTS.md` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFNpMAJQycjr66Zhs:-N8ig3op2Ik4PdQoIKXL:b-v7hh2d) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L211)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about the missing part?
</blockquote></details>

It will be done after this PR is merged. Because it's not motivating to write about steps that might be changed or removed.
___
*[`bin/crust` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFeHd0CC57AvfJyci:-N8igNo11ACcYd5_MGyU:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/bin/crust#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Compare with the current version in master. Now you need:

```bash
"$CRUST_BIN" build/contracts
```
</blockquote></details>

Done.
___
*[`cmd/contracts/main.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hGYZ_ElWx1U9rGk2k:-N8ihW_B4ULm7HpYganx:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/cmd/contracts/main.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is outdated, current version is:

```go
	network := app.NewNetwork(cored.CustomZNetNetworkConfig)
	network.SetupPrefixes()
```
</blockquote></details>

Done.



_Code quote:_
```Go
.SetAccountPrefixe
```
___
*[`pkg/contracts/deploy.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hROql8Ow2mYFYF7un:-N8iicP36_TGdnqtqPSd:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/pkg/contracts/deploy.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

gasEstimationAdj -> gasEstimationAdjustment
</blockquote></details>

Done.
___
*[`pkg/contracts/docker/Dockerfile` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hSQy5-ntysrsEaH1g:-N8ii7KRAKxm4ZExVaqj:b-4lxrez) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/pkg/contracts/docker/Dockerfile#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you point me to the place where this Dockerfile is used, can't find it
</blockquote></details>

It's a leftover from an old experiment. removed.
___
*[`tests/wasm/simple_state.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hKktM7iX7tbTGVcn8:-N8ijF1fCjes5my_7BE3:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Required change has been integrated so you may apply it here
</blockquote></details>

Done.
___
*[`tests/wasm/simple_state.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLgyO23QBNFFeIh1F:-N8ikjmlAmhOOkO4pY_G:bf8ysj4) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Storing two functions in variables and then returning those variables doesn't add any readability to the code. I would prefer to apply the same pattern to all the tests because doing it different way is an counter-intuitive approach. If the team decide that assigning functions to variables make it easier, then please apply the same pattern to all the existing tests.
</blockquote></details>

That is a side-effect of very annoying linter settings. I had to move bodies of those functions outside, so the linter doesn't complain.

Also, it was your invention there that a testing function must return two functions. If you are expecting two return values, it's totally fine to use variables for returning values.


<!-- Sent from Reviewable.io -->

2022-08-05 16:10 UTC, xlab commented
*[`tests/wasm/test_fixtures/simple-state/.gitignore` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hIfmc53JSFK08_Cg-:-N8ilMG5EoP_P9Ba_UQ5:bn6ldh3) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/test_fixtures/simple-state/.gitignore#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please store the artifacts in the better-named directory, like `bin/contracts`
</blockquote></details>

this name is fine and is related to the tests, not bin with crust and bash scripts.


<!-- Sent from Reviewable.io -->

2022-08-05 16:12 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 22 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/wasm/test_fixtures/simple-state/artifacts/simple_state.wasm` line  at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hJ4XY3uAkHrQ9Vzs0:-N8ilZroBRSQI3zF1pg6:b-8daymr) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/test_fixtures/simple-state/artifacts/simple_state.wasm#L)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: This is just a reminder that we agreed to compile it from source in the next PR ("next" means really "next", not "at some point the future")
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/477998/rq97P8VaWWCadhK6xogdte_L/image.png)


<!-- Sent from Reviewable.io -->

2022-08-05 16:14 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 22 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/wasm/simple_state.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8iDWLN9GJLhPUAMm2u:-N8imAkACugUqLaptptW:bm09nnm) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`testing.WaitUntilHealthy` does not exist anymore and you need to remove this line (healthy state of node is ensured in different place, common to all the tests)
</blockquote></details>

It still exists in all other tests on the branch. So, once it's final, remove it from all tests at once.


<!-- Sent from Reviewable.io -->

2022-08-05 16:26 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 22 of 36 files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`tests/wasm/simple_state.go` line 66 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hV5BNCnDN6cyKXLH9:-N8ip5fdDMgYDTAtPzjb:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would appreciate if some comments explaining the detailed flow of the tests could be provided here and in the second test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 16:26 UTC, xlab reviewed
> Reviewed 27 of 36 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-05 16:57 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 2 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 13 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hET2x8NpTilPmKaEk:-N8iqY1Q1lSQvkt26SpV:b-dtb052) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/.gitignore#L3)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually after discussing it, we decided to keep those entries
___
*[`SMART_CONTRACTS.md` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hFNpMAJQycjr66Zhs:-N8irRhsDF0BRyQTxkNL:b-h7nz2v) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L211)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It will be done after this PR is merged. Because it's not motivating to write about steps that might be changed or removed.
</blockquote></details>

Okay, so blocking it for now. Once code is reviewed we will come back here to fill missing part.
___
*[`SMART_CONTRACTS.md` line 124 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8ir7d63xIuGoQvxFaV:-N8ir7d71O1Vf_LdFVHd:b-wioiyl) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/SMART_CONTRACTS.md#L124)):*
> ```Markdown
> ```
> 
> If you have **Linux x86_64** or **MacOS Intel x64 / M1** platforms at hand, you can run the unit testing with reported coverage:
> ```

Are you sure it doesn't work on linux arm64 (M1s are supported)? 
___
*[`tests/wasm/simple_state.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hKktM7iX7tbTGVcn8:-N8isW097Q7Xk7TgoE15:b10ozqd) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L43)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also remove FIXME
___
*[`tests/wasm/simple_state.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLCnN02LLydAKnEpQ:-N8itHjyDGnU9OnB3eqq:b-umpys0) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L48)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Workdir of the `crust znet test` and thus all tests there depends on the env, it's not fixed. 
So it's hard to use fixtures that are not staged.

If this is unplanned, then this comment might be removed and we continue to stage fixtures in temp dir.
</blockquote></details>

`znet` receives an argument called `--bin-dir` which points to the `bin` directory of the repo. Once contracts are built from source and stored under that directory you may access them. But for now, embedding seems to be a good idea IMO. Unblocking it.
___
*[`tests/wasm/simple_state.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLSD112rK6TbcmI-h:-N8itop41hMPXzZjJdXL:b-fvvo0b) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L58)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Contracts are wasm artifact produced by the build. Even if we move from fixtures to continuous build, those will be artifacts produced on the disk.
</blockquote></details>

Exactly, and those artifacts should be read from the disk and passed to client's method deploying the contract, expecting `[]byte` argument containing that artifact.
___
*[`tests/wasm/simple_state.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8iDWLN9GJLhPUAMm2u:-N8iuJf-9DNgl5ja9Iqt:b-gx6bbc) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L69)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It still exists in all other tests on the branch. So, once it's final, remove it from all tests at once.
</blockquote></details>

But later on you will rebase this branch on top of master where this function does not exist. I'm not saying that you need to do it now, just informing you that this change was made.
___
*[`tests/wasm/simple_state.go` line 71 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hUCFvCOHP67ylKPa0:-N8iv9GaB5d6ctTpNjG3:b-tckbwz) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L71)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I am reusing the same code that exits already for the integration tests now. There is no intention to reimplement the same logic twice. Also, the client is responsible for delivering txns on chain, not for the application logic and message formatting. 
</blockquote></details>

Which part of the config says 
___
*[`tests/wasm/test_fixtures/README.md` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hTLlUEYzUE7yZevWN:-N8ivpTo5jIDIy2vIfYb:baef15n) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/test_fixtures/README.md#L6)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

That's mixing apples with elephants.

Contracts are abstract entities for VM, while the actually contracts subcommand is a Go utility.
I am not happy mixing completely different flows under an ambiguous name
</blockquote></details>

I see, so maybe `crust build/test-contracts` or any other name or path you find useful


<!-- Sent from Reviewable.io -->

2022-08-06 08:47 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 13 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`SMART_CONTRACTS.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hEyof6YYYeg6Xw_QS:-N8mIBZg02PuSCs6AjV_:b-k1sd9c) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/SMART_CONTRACTS.md#L13)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It also applies colors to some flags, so it's easier to read.
If you don't want colors, just open `tmux` and use `less README.md`
</blockquote></details>

I don't see any useful coloring being applied here: https://github.com/CoreumFoundation/crust/blob/f/wasm-contracts/SMART_CONTRACTS.md

Some words like `test` and `help` in commands are colored just because accidentally they are the keywords in bash. Same applies to `for`, `in` etc. The coloring there is 100%  meaningless.
___
*[`tests/wasm/simple_state.go` line 71 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hUCFvCOHP67ylKPa0:-N8mJxYDCYJNLX7NuAbv:b-2oauqu) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Which part of the config says 
</blockquote></details>

Please ignore the above comment, it was a leftover I forgot to remove before publishing.

I'm not saying that this logic should be implemented twice. I'm saying that it should be implemented once in the client and then called from both places: `contracts.Deploy` and integration tests. It should be like that because we decided to store all the communication between client and node inside the client object - not spread it across all the code base.
___
*[`tests/wasm/simple_state.go` line 81 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hUhe5BuZkuTH61ee_:-N8mIjHsAHNxQmwvepTC:b-6iqvwz) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L81)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This is a single deployment, done in 2 stages, so I can test intermediate results and provide more clarity if the test fails. Normally it would be a single command call.
</blockquote></details>

My personal taste is that I would prefer to have two different functions (`contracts.Deploy` and `contracts.Instantiate`). It still means that they might be called one after another in `crust contracts deploy` command without exposing those separate steps to the end user. I don't have a strong opinion on this, so I'm waiting for opinion of others.
___
*[`tests/wasm/simple_state.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLgyO23QBNFFeIh1F:-N8mJLMG42g-ycjkNt8b:b1eanrx) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L128)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

That is a side-effect of very annoying linter settings. I had to move bodies of those functions outside, so the linter doesn't complain.

Also, it was your invention there that a testing function must return two functions. If you are expecting two return values, it's totally fine to use variables for returning values.
</blockquote></details>

What is the linter error produced if those functions are returned directly?
___
*[`tests/wasm/test_fixtures/simple-state/.gitignore` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hIfmc53JSFK08_Cg-:-N8mJWuABOlKjUgM5OqG:b-imxbp9) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/test_fixtures/simple-state/.gitignore#L1)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

this name is fine and is related to the tests, not bin with crust and bash scripts.
</blockquote></details>

`target` is meaningless and it needs to be ignored separately. We already have a directory for binaries ('bin`) and compiled smart contract is a binary so I don't see a reason for storing it in completely different place.


<!-- Sent from Reviewable.io -->

2022-08-06 12:10 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 15 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8n0cIm5UbCj74aS-uv:-N8n0cIm5UbCj74aS-uw:b-8fsfzi) (no related file):*
Please rename `CRUST_*` env variables related to contracts to `CRUST_CONTRACTS_*`, like we do for `CRUST_ZNET_*`

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8n19dz0OUjx5nIKWBv:-N8n19dz0OUjx5nIKWBw:blg62n2) (no related file):*
When user executes
```
$ crust znet
$ start
```

It would be nice to create a wrapper around `crust contracts` which has some env variables set inside it. I mean:

```
export CRUST_KEYRING_DIR=/Users/xlab/Library/Caches/crust/znet/znet/app/coredev-00
export CRUST_KEYRING_KEY_FROM=alice
```

could be set automatically (and even more, like node's endpoint etc.) so the environment is ready to deploy contracts in znet without additional hassle.

To do it:
- inspect how existing wrappers are created: https://github.com/CoreumFoundation/crust/blob/master/pkg/znet/commands.go#L54
- those wrappers are created when `crust znet` without arguments is executed, instead of doing it that way you need to create the wrapper when cored is deployed in znet, an example of how to do it is available here: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/cored/cored.go#L245
- because you need this wrapper to be created for single node only, not all of the nodes deployed by znet, you may create this wrapper only if `c.rootNode == nil`

___


<!-- Sent from Reviewable.io -->

2022-08-06 13:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 16 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nH2lu86EW4FvhgFRI:-N8nH2lu86EW4FvhgFRJ:bslmwa3) (no related file):*
`CRUST_KEYRING_DIR` value you provide in the PR description is outdated, it should be `.../app/coredev-00/coreum-devnet-1`

___


<!-- Sent from Reviewable.io -->

2022-08-06 13:39 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 17 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nMjNB9fHm1ZauDfxY:-N8nMjNCCr84e-cQAwhQ:b-3d6asv) (no related file):*
I've tried to deploy smart contract in znet and got an error. Way to reproduce:

```
$ crust znet
$ start
$ export CRUST_KEYRING_DIR=/home/wojciech/.cache/crust/znet/znet/app/coredev-00/coreum-devnet-1
$ export CRUST_KEYRING_KEY_FROM=alice
$ crust contracts deploy ~/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.wasm --log-format=yaml
```

Error I get:

```
- log: "2022-08-06 13:12:24.432 ERROR Application returned error: failed to run contract code store: failed to estimate gas for MsgStoreCode: failed to simulate the transaction execution: rpc error: code = InvalidArgument desc = 
github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:590
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:579
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:421
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:256
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:159
github.com/tendermint/tendermint/rpc/core.ABCIQuery
	github.com/tendermint/tendermint@v0.34.19/rpc/core/abci.go:20
reflect.Value.call
	reflect/value.go:556
reflect.Value.Call
	reflect/value.go:339
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:96
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:122
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2462
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:236
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:209
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.serverHandler.ServeHTTP
	net/http/server.go:2916
net/http.(*conn).serve
	net/http/server.go:1966
fee must be paid in 'dacore' coin, but 'core' was offered instead: invalid coins: invalid request"
```

It means that you probably hardcoded "core" token somewhere instead of using the one configured in `network` object

___


<!-- Sent from Reviewable.io -->

2022-08-06 13:44 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nMjNB9fHm1ZauDfxY:-N8nOUpP98sQ6LZqc2bP:brayjyr) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I've tried to deploy smart contract in znet and got an error. Way to reproduce:

```
$ crust znet
$ start
$ export CRUST_KEYRING_DIR=/home/wojciech/.cache/crust/znet/znet/app/coredev-00/coreum-devnet-1
$ export CRUST_KEYRING_KEY_FROM=alice
$ crust contracts deploy ~/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.wasm --log-format=yaml
```

Error I get:

```
- log: "2022-08-06 13:12:24.432 ERROR Application returned error: failed to run contract code store: failed to estimate gas for MsgStoreCode: failed to simulate the transaction execution: rpc error: code = InvalidArgument desc = 
github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:590
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:579
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:421
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:256
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:159
github.com/tendermint/tendermint/rpc/core.ABCIQuery
	github.com/tendermint/tendermint@v0.34.19/rpc/core/abci.go:20
reflect.Value.call
	reflect/value.go:556
reflect.Value.Call
	reflect/value.go:339
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:96
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:122
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2462
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:236
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:209
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.serverHandler.ServeHTTP
	net/http/server.go:2916
net/http.(*conn).serve
	net/http/server.go:1966
fee must be paid in 'dacore' coin, but 'core' was offered instead: invalid coins: invalid request"
```

It means that you probably hardcoded "core" token somewhere instead of using the one configured in `network` object
</blockquote></details>

I think these are the places to fix:
https://reviewable.io/reviews/CoreumFoundation/crust/41#-N8nOKCgD5s0OC8NSD_Q
https://reviewable.io/reviews/CoreumFoundation/crust/41#-N8nO0HeA9Ku2XpBofHo

___
___
*[`pkg/contracts/deploy.go` line 411 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nO0HeA9Ku2XpBofHo:-N8nO0HeA9Ku2XpBofHp:b-jual9i) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/pkg/contracts/deploy.go#L411)):*
> ```Go
> 	if len(c.Network.MinGasPrice) == 0 {
> 		c.Network.minGasPriceParsed = types.Coin{
> 			Amount: big.NewInt(1500), // matches InitialGasPrice in cored
> ```

Value for Amount and Denom should be taken from`Network` created for particular chain ID
___
*[`pkg/contracts/execute.go` line 184 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nOKCgD5s0OC8NSD_Q:-N8nOKCgD5s0OC8NSD_R:b-jual9i) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/pkg/contracts/execute.go#L184)):*
> ```Go
> 	if len(c.Network.MinGasPrice) == 0 {
> 		c.Network.minGasPriceParsed = types.Coin{
> 			Amount: big.NewInt(1500), // matches InitialGasPrice in cored
> ```

Value for Amount and Denom should be taken from`Network` created for particular chain ID


<!-- Sent from Reviewable.io -->

2022-08-06 13:48 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 20 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nMjNB9fHm1ZauDfxY:-N8nP4pT0jIRFPbBlxR4:b-lpx1nj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think these are the places to fix:
https://reviewable.io/reviews/CoreumFoundation/crust/41#-N8nOKCgD5s0OC8NSD_Q
https://reviewable.io/reviews/CoreumFoundation/crust/41#-N8nO0HeA9Ku2XpBofHo
</blockquote></details>

Now I also see that default value for `--min-gas-price` flag is `1500core`. @miladz68 it should be adjusted to match the mainnet right?

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nPKDN2DAXEi73Z-bP:-N8nPKDN2DAXEi73Z-bQ:b-dhj36h) (no related file):*
The default value for `--chain-id` flag is `coredev`. We don't provide this network. I think all the default values for all the fags should target mainnet.

___


<!-- Sent from Reviewable.io -->

2022-08-06 13:55 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 21 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nPx3g0_nnfyRxiu9r:-N8nPx3g0_nnfyRxiu9s:b-dyxyg5) (no related file):*
After setting `--min-gas-price` and `--chain-id` I get another error.

How to reproduce:

```
$ crust znet
$ start
$ export CRUST_KEYRING_DIR=/home/wojciech/.cache/crust/znet/znet/app/coredev-00/coreum-devnet-1
$ export CRUST_KEYRING_KEY_FROM=alice
$ crust contracts deploy ~/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.wasm --min-gas-price=1500dacore --chain-id=coreum-devnet-1 --log-format=yaml
```

Error I get:

```
- log: "2022-08-06 13:49:44.045 ERROR Application returned error: failed to run contract instantiate: failed to estimate gas for MsgInstantiateContract: failed to simulate the transaction execution: rpc error: code = InvalidArgument desc = 
github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:590
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:579
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:421
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:256
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:159
github.com/tendermint/tendermint/rpc/core.ABCIQuery
	github.com/tendermint/tendermint@v0.34.19/rpc/core/abci.go:20
reflect.Value.call
	reflect/value.go:556
reflect.Value.Call
	reflect/value.go:339
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:96
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:122
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2462
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:236
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:209
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.serverHandler.ServeHTTP
	net/http/server.go:2916
net/http.(*conn).serve
	net/http/server.go:1966
payload msg: invalid: invalid request"
```

___


<!-- Sent from Reviewable.io -->

2022-08-06 14:05 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 21 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`tests/wasm/simple_state.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8hLgyO23QBNFFeIh1F:-N8nS42T3j3MtoXWeH2v:by5h1ny) ([raw file](https://github.com/coreumfoundation/crust/blob/1d2e396824d62bc4b928c6f38ad7015161e18c3e/tests/wasm/simple_state.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What is the linter error produced if those functions are returned directly?
</blockquote></details>

Also because of introducing those variables test names printed in logs look like this now: `wasm.TestBankSendContract.func2`.
Please fix the regexp here: https://github.com/CoreumFoundation/crust/blob/f/wasm-contracts/infra/testing/types.go#L52
by replacing `.func1` with `.func[0-9]+`.

Also keep in mind that in current master this logic is different: https://github.com/CoreumFoundation/crust/blob/master/infra/testing/types.go#L86
and needs to be adjusted accordingly.

Also keep in mind that FIXME in the line above will be invalid and removed soon (PR is there) due to other changes: https://github.com/CoreumFoundation/crust/blob/move-integration-tests/infra/testing/types.go#L83


<!-- Sent from Reviewable.io -->

2022-08-06 14:13 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 22 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/contracts/main.go` line 407 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nUnuuCSxgkRcd9Fhs:-N8nUnuuCSxgkRcd9Fht:bmu4elw) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/cmd/contracts/main.go#L407)):*
> ```Go
> 		"Path to a file containing JSON-encoded contract instantiate args, or JSON-encoded body itself.",
> 	)
> 	deployCmd.Flags().StringVar(
> ```

The help for this flag says:

`--init-access-type string      Sets the permission flag, affecting who can instantiate this contract. Expects "nobody", "address", "unrestricted". (default "undefined")`

The default value (`undefined`) is not on the list of expected values (`nobody`, `address`, `unrestricted`).
What does it mean? Is `undefined` a valid option? If not then use an empty string, if yes then add it to the list of expected values.


<!-- Sent from Reviewable.io -->

2022-08-06 14:18 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 23 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nVxfdD-offO1ZngUi:-N8nVxfeBgBijGoQ6lLK:bm30oyf) (no related file):*
I see that in flag descriptions you reference other setting by using the env var name instead of the flag.
Example:

`--keyring-dir string           Sets keyring path in the filesystem, useful when CRUST_KEYRING_BACKEND is "file".`

while it should rather be:

`--keyring-dir string           Sets keyring path in the filesystem, useful when --keyring-backend is "file".`

___


<!-- Sent from Reviewable.io -->

2022-08-06 14:21 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 24 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/contracts/main.go` line 425 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nWdEXB_M_bx-M3Vnt:-N8nWdEXB_M_bx-M3Vnu:bkwotih) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/cmd/contracts/main.go#L425)):*
> ```Go
> 		"Set the admin address explicitly. If false, there will be no admin.",
> 	)
> 	deployCmd.Flags().StringVar(
> ```

Could you briefly explain the concept behind `admin`? What it is used for? Is it any kind of privileged address being able to execute additional functions on smart contract?


<!-- Sent from Reviewable.io -->

2022-08-06 14:31 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 27 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nYylE5x7OQs_znZ5q:-N8nYylFB-QHQNLVi64j:bfi379b) (no related file):*
I see that in many places you use `len(someString) > 0` to check if it's non empty rather than `someString != ""`. Is there any particular reason for doing it this way? doing it ` != ""` seems much more natural to me.

@miladz68 @ysv WDYT?

___
___
*[`cmd/contracts/main.go` line 395 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nXp4V3QG6eXAxy1fQ:-N8nXp4WDEEN0ajZKpG1:b-azh8gh) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/cmd/contracts/main.go#L395)):*
> ```Go
> 		"Forces an optimized rebuild of the WASM artefact, even if it exists. Requires WorkspaceDir to be present and valid.",
> 	)
> 	deployCmd.Flags().BoolVar(
> ```

How does this flag cooperates with `--init-access-address`? If `--init` is set then setting `--init-access-address` together with `--init-access-type=address` seems to be an invalid scenario, right?
___
*[`cmd/contracts/main.go` line 398 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nXQ4NCJtLwiLizTGJ:-N8nXQ4NCJtLwiLizTGK:b-i9fpie) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/cmd/contracts/main.go#L398)):*
> ```Go
> 		&deployConfig.InstantiationConfig.NeedInstantiation,
> 		"init",
> 		toBool("CRUST_CONTRACTS_DEPLOY_NEED_INSTANTIATION", true),
> ```

Normally, using regular client deployment and instantiation are two separate commands, that's why IMO the default value here should be `false`, to conform to the standard flow by default


<!-- Sent from Reviewable.io -->

2022-08-06 14:46 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 28 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nPx3g0_nnfyRxiu9r:-N8nayy55fk4s4HzKvBq:b8z71s6) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After setting `--min-gas-price` and `--chain-id` I get another error.

How to reproduce:

```
$ crust znet
$ start
$ export CRUST_KEYRING_DIR=/home/wojciech/.cache/crust/znet/znet/app/coredev-00/coreum-devnet-1
$ export CRUST_KEYRING_KEY_FROM=alice
$ crust contracts deploy ~/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.wasm --min-gas-price=1500dacore --chain-id=coreum-devnet-1 --log-format=yaml
```

Error I get:

```
- log: "2022-08-06 13:49:44.045 ERROR Application returned error: failed to run contract instantiate: failed to estimate gas for MsgInstantiateContract: failed to simulate the transaction execution: rpc error: code = InvalidArgument desc = 
github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:590
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:579
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:421
github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:256
github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:159
github.com/tendermint/tendermint/rpc/core.ABCIQuery
	github.com/tendermint/tendermint@v0.34.19/rpc/core/abci.go:20
reflect.Value.call
	reflect/value.go:556
reflect.Value.Call
	reflect/value.go:339
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:96
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_json_handler.go:122
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2462
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:236
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.19/rpc/jsonrpc/server/http_server.go:209
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2084
net/http.serverHandler.ServeHTTP
	net/http/server.go:2916
net/http.(*conn).serve
	net/http/server.go:1966
payload msg: invalid: invalid request"
```
</blockquote></details>

Okay, I found that I need to create file containing init payload.
Once it is done the command

`crust contracts deploy ~/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.wasm --min-gas-price=1500dacore --chain-id=coreum-devnet-1 --init-payload=/home/wojciech/crust/tests/wasm/test_fixtures/bank-send/artifacts/bank_send.json --log-format=yaml`

works.

Some requests:
- would it be possible to improve the error message or is it something in CosmWASM we don't have access to?
- in the README where you provide commands for building smart contracts, could you also add commands for deploying them?
- could you add a sample json (same ones you use in integration tests) files next to the *.wasm files? Also please describe the meaning of json fields in the readme

___
___
*[`tests/wasm/bank_send.go` line 82 at r5](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8n_KkACmiF00h03iBf:-N8n_KkACmiF00h03iBg:bpi5ga5) ([raw file](https://github.com/coreumfoundation/crust/blob/6fc32d8073d7810600fb957236326e7fadde7658/tests/wasm/bank_send.go#L82)):*
> ```Go
> 	}
> 
> 	return initTestState, runTestFunc
> ```

It might be simplified:

```go
return initTestState, testBankSendContract(
			chain,
			adminWallet,
			testWallet,
			networkConfig,
			stagedContractPath,
			nativeDenom,
			nativeTokens,
)
```


<!-- Sent from Reviewable.io -->

2022-08-06 14:52 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: all files reviewed, 29 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8ncCCS8cnQeqXz85zs:-N8ncCCS8cnQeqXz85zt:b-yd66qn) (no related file):*
I have a general request I would like to discuss with entire team.

I think the part related to deploying smart contract should be removed from this tool. The CosmWASM module provides commands for doing this in `cored` binary, which is the official client for our blockchain (for all the networks: znet, devnet, testnet and mainnet). IMO there is no need to duplicate this functionality and deal with keystores etc. in the second tool, just to provide a command doing the exact same thing.

`crust contracts` may be used for building, linting, testing and estimating gas but the deployment should be done with `cored`.
Same way we have `crust` for building the binaries but it is not used for deploying the validators.

___


<!-- Sent from Reviewable.io -->

2022-08-08 14:43 UTC, oliverasistemas approved these changes

2022-08-09 03:16 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 12 of 40 files reviewed, 30 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 11 at r6](https://reviewable.io/reviews/coreumfoundation/crust/41#-N9-aKjA2_hWhl_pG-Dk:-N9-aKjA2_hWhl_pG-Dl:b-q31b9k) ([raw file](https://github.com/coreumfoundation/crust/blob/2072ec3f79ac3292ccdb4d3fd0e0c164acff4883/go.mod#L11)):*
> ```XML
> )
> 
> replace github.com/CoreumFoundation/coreum => ../coreum
> ```

By doing this you break the ability of `crust` to run current integration tests in PRs targetting `coreum`


<!-- Sent from Reviewable.io -->

2022-08-09 16:32 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 12 of 40 files reviewed, 20 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nMjNB9fHm1ZauDfxY:-N92RIxt5muGK3Q8oXzr:bmwgiso) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now I also see that default value for `--min-gas-price` flag is `1500core`. @miladz68 it should be adjusted to match the mainnet right?
</blockquote></details>

I cannot tell just by looking at the logs, but probably the config should be used to pass the gas price.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nYylE5x7OQs_znZ5q:-N92RdwY2If5BNl2ipHs:bgzp8ur) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see that in many places you use `len(someString) > 0` to check if it's non empty rather than `someString != ""`. Is there any particular reason for doing it this way? doing it ` != ""` seems much more natural to me.

@miladz68 @ysv WDYT?
</blockquote></details>

I don't have a preference really. I find len("") >0 easier to read and write.

___


<!-- Sent from Reviewable.io -->

2022-08-10 06:15 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 12 of 40 files reviewed, 19 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/41#-N8nMjNB9fHm1ZauDfxY:-N95NlnVBpRG6ZpPRU7s:b-ar4d02) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I cannot tell just by looking at the logs, but probably the config should be used to pass the gas price.
</blockquote></details>

I'm asking about default values for those flags. `core` token won't exist on any network we deliver. Same for `--chain-id`. In `cored` the default values match those required by `mainnet`. I think it should be the same fot `crust contracts` commands.

___


<!-- Sent from Reviewable.io -->

2022-08-17 04:50 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/41)* status: 12 of 40 files reviewed, 20 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/build.go` line 57 at r6](https://reviewable.io/reviews/coreumfoundation/crust/41#-N9e7g6t4ZytgT_vkRzA:-N9e7g6t4ZytgT_vkRzB:b7nqi2p) ([raw file](https://github.com/coreumfoundation/crust/blob/f658d0e8b65396deb82b98fe9c7c45b024b56104/build/build.go#L57)):*
> ```Go
> 
> func buildZStress(ctx context.Context, deps build.DepsFunc) error {
> 	deps(golang.EnsureGo)
> ```

`golang.EnsureLibWASMVMMuslC` must be added here, compare with `buildCored`


<!-- Sent from Reviewable.io -->

2022-09-29 12:54 UTC, closed without merging