Enable CGO during compilation.
CoreumFoundation/crust pull request #5
Opened 2022-06-29 11:10 UTC by xlab

Note: docker build is disabled, should be redone. Might do that in this PR.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/crust/5)

2022-06-29 13:10 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5j9VWGAyNhCGb0PxZJ:-N5jZzN1A6ZIx9wCb6kO:b-mu1ut4) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab It doesn't. The goal of this PR is to introduce `CGO` compatibility. If the side-effect is to go closer the expectations of the other one, it's fine. But it's not the goal.
</blockquote></details>

CGO compatibility breaks Docker builds for cored. If you are fine to merge this without Docker implemented, we can ignore the case.

The considerations above might be not related to the goal of the PR, but they are related to consequences of implementing the goal fully in the current toolset. It's still related to `crust/2` because it's will be about the same Dockerfile.




<!-- Sent from Reviewable.io -->

2022-06-29 13:10 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5j9VWGAyNhCGb0PxZJ:-N5j_H6t8dy2lG8XW4zn:bqj1zvz) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab It doesn't. The goal of this PR is to introduce `CGO` compatibility. If the side-effect is to go closer the expectations of the other one, it's fine. But it's not the goal.
</blockquote></details>

I don't have much of exp why we need to enable CGO so not able to comment on this for now

___


<!-- Sent from Reviewable.io -->

2022-06-29 13:11 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5j9VWGAyNhCGb0PxZJ:-N5j_Ug73hbF66_hAQ7-:bsmbuf4) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't have much of exp why we need to enable CGO so not able to comment on this for now
</blockquote></details>

@ysv wasm module uses wasmvm and thus CGO is required. That's the common problem with having Wasm VM on the chain.




<!-- Sent from Reviewable.io -->

2022-06-29 14:17 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5joYgb8Ov6eZQTn5P_:b-rkrv1c) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> My point is that you can't disable building with GOOS=linux

I am running on Mac and stuff works fine and as expected, I don't get your point.
</blockquote></details>

Did you remove `bin/linux`?

___


<!-- Sent from Reviewable.io -->

2022-06-29 20:24 UTC, wojtek-coreum requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5l7eyg22V6E-T4Q5az:b-ls8x9q) (no related file):*
> I am running on Mac and stuff works fine and as expected

How do you run it on mac?

___


<!-- Sent from Reviewable.io -->

2022-06-29 21:48 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5lQaGa93KcIuFuIcOh:b-mcaul1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I am running on Mac and stuff works fine and as expected

How do you run it on mac?
</blockquote></details>

`crust build && cored` 




<!-- Sent from Reviewable.io -->

2022-06-29 21:51 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5lRB5ICupwfRkZeJ96:b-e6xto2) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

`crust build && cored` 
</blockquote></details>

If you were asking about 3-node consensus via znet, I don't really use it locally, but it fails indeed 

```
error	znet	run/run.go:86	Application returned error: panic: stat /Users/xlab/dev/coreum/crust/bin/linux/cored: no such file or directory	{"error": "panic: stat /Users/xlab/dev/coreum/crust/bin/linux/cored: no such file or directory"}
```

But that's because this binary is supposed to be mounted in Docker, the OS and platform itself is irrelevant. 

___


<!-- Sent from Reviewable.io -->

2022-06-30 06:54 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5nMxLcCut-VExJtTcX:b-ie80p5) (no related file):*
> I don't really use it locally, but it fails indeed

It fails even in standard setup with a single node. Also other people use it on macs now so it can't stop working.

> But that's because this binary is supposed to be mounted in Docker, the OS and platform itself is irrelevant.

It fails because you commented out code which builds the docker-specific binary without providing alternative way of building this binary inside docker container with CGO support.

It even fails in CI for that reason now - host-compiled CGO-enabled binary is started in docker where libs are missing.

___


<!-- Sent from Reviewable.io -->

2022-06-30 09:36 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N5jANrI7h1XQn-czHzs:-N5nxwms3g0ECcIvwd_3:bx9a2ho) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I don't really use it locally, but it fails indeed

It fails even in standard setup with a single node. Also other people use it on macs now so it can't stop working.

> But that's because this binary is supposed to be mounted in Docker, the OS and platform itself is irrelevant.

It fails because you commented out code which builds the docker-specific binary without providing alternative way of building this binary inside docker container with CGO support.

It even fails in CI for that reason now - host-compiled CGO-enabled binary is started in docker where libs are missing.
</blockquote></details>

I am working on a fix now.




<!-- Sent from Reviewable.io -->

2022-06-30 09:38 UTC, wojtek-coreum reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-04 13:42 UTC, wojtek-coreum requested changes
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @xlab)

___
*[`build/build.go` line 76 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MWy869DrHhoiG5s-:-N68MWy9CF4GgoDrz2-y:b-aaqb7r) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L76)):*
> ```Go
> 	}
> 
> 	if !cgoEnabled && runtime.GOOS != dockerGOOS {
> ```

Simplify it to
```go
if cgoEnabled {
} else if runtime.GOOS != dockerGOOS {
}
```
___
*[`build/build.go` line 80 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MwlRCsYCTymz1IlP:-N68MwlRCsYCTymz1IlQ:bz2ix0s) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L80)):*
> ```Go
> 	} else if cgoEnabled {
> 		// docker-targeted binary must be built from within Docker environment
> 		return goBuildWithDocker(ctx, pkg, filepath.Join(dir, dockerGOOS), binName)
> ```

The filepath here will overwrite, the one used in the first part of this function on linux. Because on linux `runtime.GOOS == dockerGOOS`. You may use completely new directory like `docker` for this instead
___
*[`build/build.go` line 110 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68Nd_9DqERnli0bT0a:-N68Nd_9DqERnli0bT0b:b-dogq8r) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L110)):*
> ```Go
> 		"--build-arg", "BIN_NAME="+binName,
> 		"--tag", binName+"-cgo-build",
> 		"-f", dockerfilePath,
> ```

Instead of storing Dockerfile in temporary file you may use `"-f", "-"` options and pass content of Dockerfile through stdin of the command
___
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N68OGvs7LzL601UHD-W:bl1k4v1) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
> ```Go
> 		"--tag", binName+"-cgo-build",
> 		"-f", dockerfilePath,
> 		buildContext,
> ```

Don't pass the source code as build context because it copies all the files to the docker daemon. Instead use `run` command to create container with source code mounted as volume and compile the code inside container
___
*[`build/build.go` line 112 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68PvEC2hleoY02wU1_:-N68PvEC2hleoY02wU1a:b1t2ojy) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L112)):*
> ```Go
> 		"-f", dockerfilePath,
> 		buildContext,
> 	).CombinedOutput(); err != nil {
> ```

Please use `libexec` instead of `CombinedOutput` because `libexec` handles terminating the command on canceled context correctly. Now if you press "Ctrl+C" during command execution it won't exit until build is finished.
___
*[`build/build.go` line 126 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68QUlPBFjrxhGK8DSs:-N68QUlPBFjrxhGK8DSt:b-vel0u5) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L126)):*
> ```Go
> 		"-v", fmt.Sprintf("%s:%s", absOutPath, "/mnt"),
> 		"--env", "BIN_NAME="+binName,
> 		binName+"-cgo-build",
> ```

Please don't add suffix here. instead create separate directory like I mentioned in another comment
___
*[`build/build.go` line 127 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68Q_xX84LGY4j_akmJ:-N68Q_xX84LGY4j_akmK:bnhw13g) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L127)):*
> ```Go
> 		"--env", "BIN_NAME="+binName,
> 		binName+"-cgo-build",
> 	).CombinedOutput(); err != nil {
> ```

Use `libexec`
___
*[`build/docker/Dockerfile.cgo` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68QwetBNyQw8OpgRkb:-N68QwetBNyQw8OpgRkc:b4e0p4w) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L15)):*
> ```
> COPY go.sum .
> RUN go mod download
> COPY . .
> ```

So, source code is copied twice. First by the client to daemon, and now from build context to the image.
___
*[`build/docker/Dockerfile.cgo` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68RC8SE07B2yMCf1Bz:-N68RC8SE07B2yMCf1C-:b2fh8ju) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L18)):*
> ```
> 
> ARG BIN_NAME
> RUN CGO_ENABLED=1 LEDGER_ENABLED=false BUILD_TAGS=muslc go build -trimpath -ldflags="-w -s" -o /out/${BIN_NAME} ./cmd/${BIN_NAME}
> ```

To make this `Dockerfile` generic, full path to package should be accepted as an argument instead of constructing it like `./cmd/${BIN_NAME}`
___
*[`build/exec/docker.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68P6dL07YZJUCUfaJQ:-N68P6dM2m0LQQmshSkR:bvdmggx) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/exec/docker.go#L1)):*
> ```Go
> package exec
> ```

Leave those files where they were. `build` is not its only user - crust uses it too


<!-- Sent from Reviewable.io -->

2022-07-04 14:04 UTC, xlab commented
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N68W6X9--UpsjhmC7sD:br0zl9p) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Don't pass the source code as build context because it copies all the files to the docker daemon. Instead use `run` command to create container with source code mounted as volume and compile the code inside container
</blockquote></details>

Copy on build allows to use caching layers, also this building part will be reused for prod builds, wchi won't build anything upon run.


<!-- Sent from Reviewable.io -->

2022-07-04 14:04 UTC, xlab commented
*[`build/build.go` line 110 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68Nd_9DqERnli0bT0a:-N68W4Qq2OakF5bumiF5:b-q7d8mb) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L110)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Instead of storing Dockerfile in temporary file you may use `"-f", "-"` options and pass content of Dockerfile through stdin of the command
</blockquote></details>

Nice nice idea, will try


<!-- Sent from Reviewable.io -->

2022-07-04 14:19 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N68X2Bq0tnObwlto_cg:b-5pr9g6) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Copy on build allows to use caching layers, also this building part will be reused for prod builds, wchi won't build anything upon run.
</blockquote></details>

If you use mounted volume there will be nothing to cache, and caching the source code which is changing all the time is not a good idea anyway. I would vote for not thinking about building prod image at this stage.
The only thing you need is the `alpine-go` image. You run container based on this image with source code mounted, run `go build` and `cp` and this is the end of the story. You have only `run` command, not `build` first and then `run`
___
*[`build/docker/Dockerfile.cgo` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68QwetBNyQw8OpgRkb:-N68Zaw19qTxSBO8FA7z:bqhbcq9) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L15)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This is a common pattern in Docker, if you have a better solution that still separates BUILD and RUN, let me know.

I am not thinking about Docker client and daemon interaction, I am just using Docker as a user.
</blockquote></details>

That's the thing... we don't need the `build` stage. Take a look at my other comment.
___
*[`build/docker/Dockerfile.cgo` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68RC8SE07B2yMCf1Bz:-N68ZjaT4T9XaM_UgvDl:b-hke0pp) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L18)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I don't want to make it generic, it's designed for a particular set of binaries, when you have to go module root and the bin lives in `./cmd/XXX`

Making this image generic will probably trigger some other problems, that the original crust code is not ready to solve yet.
</blockquote></details>

So then name this file like `Dockerfile.cored`
___
*[`build/exec/docker.go` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68P6dL07YZJUCUfaJQ:-N68ZsNw3kmn656wmGdg:b-j64bsg) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/exec/docker.go#L1)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Nope, I didn't move `exec`, I made a copy. This is because `crust build` is on 1.16 and importing `crust` where `exec` lives require 1.18 and a lot of dependencies, I don't want to add an external module just for a simple wrapper around `os.Cmd` 
</blockquote></details>

Let's think about sth better than copying code, like separate module etc?


<!-- Sent from Reviewable.io -->

2022-07-04 14:52 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 112 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68PvEC2hleoY02wU1_:-N68gaUO8pu1gTiSIv6e:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L112)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please use `libexec` instead of `CombinedOutput` because `libexec` handles terminating the command on canceled context correctly. Now if you press "Ctrl+C" during command execution it won't exit until build is finished.
</blockquote></details>

Done.
___
*[`build/build.go` line 127 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68Q_xX84LGY4j_akmJ:-N68gawP4Hu0Gyrx2ueX:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L127)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Use `libexec`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 14:59 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 80 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MwlRCsYCTymz1IlP:-N68hKZ945eaBxwZWVJ6:bcj1sze) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The filepath here will overwrite, the one used in the first part of this function on linux. Because on linux `runtime.GOOS == dockerGOOS`. You may use completely new directory like `docker` for this instead
</blockquote></details>

Doesn't znet look for `linux` specifically? I need a reference to all places that are affected if I change `outPath` there to something like `muslc`


<!-- Sent from Reviewable.io -->

2022-07-04 15:10 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 76 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MWy869DrHhoiG5s-:-N68kpvl17AIjJoal-VD:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L76)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Simplify it to
```go
if cgoEnabled {
} else if runtime.GOOS != dockerGOOS {
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 15:11 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 110 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68Nd_9DqERnli0bT0a:-N68kxGN4khYHIQY2RiJ:b-m6t1gv) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L110)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Nice nice idea, will try
</blockquote></details>

Works fine.


<!-- Sent from Reviewable.io -->

2022-07-04 15:12 UTC, xlab commented
*[`build/docker/Dockerfile.cgo` line 15 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68QwetBNyQw8OpgRkb:-N68l1Uo2o-OqOKW4nI_:b-hinto7) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

That's the thing... we don't need the `build` stage. Take a look at my other comment.
</blockquote></details>

The build stage at least has 1 layer already, with muslc and cgo-related packages, so this claim is vague.


<!-- Sent from Reviewable.io -->

2022-07-04 16:02 UTC, wojtek-coreum requested changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @oliverasistemas and @xlab)

___
*[`build/build.go` line 80 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MwlRCsYCTymz1IlP:-N68nwP54Wj9EBZj0qMh:b-4leb7g) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L80)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Doesn't znet look for `linux` specifically? I need a reference to all places that are affected if I change `outPath` there to something like `muslc`
</blockquote></details>

This is the only place to change: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/cored/cored.go#L189
___
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N68uGEq0HKrw3jZwP38:b8ry1cq) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
Software is written once by one person. Then it is executed many many times by large number of people. It means that investing a little more time during development it's possible to improve it so all the other people will same hundreds of hours in total during the software lifetime every year.

In this particular case for example it means that go modules required by cored will be downloaded twice during the build: once on host machine to build host-specific binary, second one in docker. You could easily save time of everyone by mounting local `~/go` to the docker container so it reuses modules downloaded previously.

So there are really tiny optimizations which will take you 15 minutes to introduce and will save time to everyone in the future:
- mount ~/go inside container
- mount source code inside container instead of copying it twice during build
- compile code in the container, not during build

It's so simple to do that you used more time to write the comment.

> This PR is related to unblocking the pipeline of myself

This PR introduces new functionality and it would be nice to do it in the way that works nicely for everyone for a long time, because this is how it will be used. It's not a temporary dirty hack to solve temporary problem. It will be with us for a long time so let's add some quality there.

> but at the same time don't think about the prod that will happen very soon.

Once the cgo binary is built by the code introduced by this PR building prod image is as simple as copying the binary to the alpine image, so I definitely think about it now. It just does not need to be done in this PR.
___
*[`build/build.go` line 95 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68q7HN0lA0EEfx0iL-:-N68q7HN0lA0EEfx0iL0:b5dermq) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L95)):*
> ```Go
> 	// buildContext should be the module root containing go.sum and go.mod
> 	// with the actualy bin package located under ./cmd/{binName}
> 	buildContext := filepath.Dir(filepath.Dir(absPkgPath))
> ```

The assumption made here on the relative path between package location and repo root directory is wrong for generic case.
But you are lucky, `crust` sets working directory to the repo root already so you don't need to do anything special. Docker command will start in this dir by default.
___
*[`build/build.go` line 115 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rMCI9ESpRNtO4cEC:-N68rMCI9ESpRNtO4cED:b-qy3wyc) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L115)):*
> ```Go
> 			"docker", "build",
> 			"--build-arg", "BIN_NAME=" + binName,
> 			"--tag", binName + "-cgo-build",
> ```

please add `crust-` prefix to the image name
___
*[`build/build.go` line 120 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68r5Mi903A82wBXs3p:-N68r5Mi903A82wBXs3q:bejokwv) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L120)):*
> ```Go
> 		},
> 	}
> 	log.Debug(buildCmd.String())
> ```

leftover?
___
*[`build/build.go` line 125 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rcdnBWyjs4wyUtWo:-N68rcdoAemeVXYCN_jx:b1jf7eo) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L125)):*
> ```Go
> 		Path: dockerCmd,
> 		Args: []string{
> 			"docker", "run",
> ```

please add `--user=os.Getuid():os.Getgid()` option so the built binary is owned by the correct user after copying to filesystem of the host. Or use another mechanism to `chown` it accordingly.
___
*[`build/build.go` line 132 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68s-J2EMyRHp34Og4q:-N68s-J2EMyRHp34Og4r:bejokwv) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L132)):*
> ```Go
> 		},
> 	}
> 	log.Debug(runCmd.String())
> ```

leftover?
___
*[`build/docker/Dockerfile.cgo` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68RC8SE07B2yMCf1Bz:-N68ohuC2ccStEyOo7QX:b-ka5ksl) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L18)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's not only about `cored`, it's about cgo-enabled binary under `./cmd`
</blockquote></details>

you have no guarantee that every package will be located under `cmd/bin-name`. Soemtimes it might be just `cmd`, sometimes it might be just the repo root directory. So I see two possibilities:
- make it generic like `goBuildPkg`, by taking a `pkg` argument pointing to the right location
- make it specific to cored

I prefer the first approach so both `goBuildPkg` and `goBuildWithDocker` work the same way with the only difference being the place were binary is built
___
*[`build/docker/Dockerfile.cgo` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68sr296ztEmijvCygC:-N68sr296ztEmijvCygD:b-6keg9r) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L12)):*
> ```
> 
> WORKDIR /src
> COPY go.mod .
> ```

Why do you copy these two files first, if everything is copied two lines later anyway?
Also keep in mind that not every repo must contain `go.sum` and `go.mod` in the repo root dir.
___
*[`build/docker/Dockerfile.cgo` line 18 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68tBQ4--BkvGQYQZYd:-N68tBQ4--BkvGQYQZYe:b-rnzsfm) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L18)):*
> ```
> 
> ARG BIN_NAME
> RUN CGO_ENABLED=1 LEDGER_ENABLED=false BUILD_TAGS=muslc go build -trimpath -ldflags="-w -s" -o /out/${BIN_NAME} ./cmd/${BIN_NAME}
> ```

It might happen that there are more go modules in single repo. Please change the working directory to the package location like here: https://github.com/CoreumFoundation/crust/blob/master/build/go.go#L33

Otherwise you are at risk that package is built using different `go.mod` file that it should.


<!-- Sent from Reviewable.io -->

2022-07-04 16:52 UTC, xlab commented
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N696hQ03njbZReny7LD:b426a30) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
>  investing a little more time during development it's possible to improve it 
>  nicely for everyone for a long time

This is all very vague and that's why I am calling this nitpicking.

And what thing, in particular, do you want to improve?
Even within this page-long comment, I cannot see a problem you are trying to solve.


<!-- Sent from Reviewable.io -->

2022-07-04 16:53 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 120 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68r5Mi903A82wBXs3p:-N697EeX8Yx0h885FJtC:b-2w5ied) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

No, if the app runs with debug logging, it should print commands it executes.


<!-- Sent from Reviewable.io -->

2022-07-04 16:53 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/build.go` line 132 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68s-J2EMyRHp34Og4q:-N697O422CHyVC49ioya:b-2w5ied) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

No, if the app runs with debug logging, it should print commands it executes.


<!-- Sent from Reviewable.io -->

2022-07-04 16:56 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`build/docker/Dockerfile.cgo` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68sr296ztEmijvCygC:-N697QaT1QX0IsqWZVYP:b-p1imbh) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L12)):*
This dockerfile is not working with repos, it works with go modules.

> Why do you copy these two files first

To separate the dependencies layer from the rest of the source code.
___
*[`build/docker/Dockerfile.cgo` line 18 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68tBQ4--BkvGQYQZYd:-N697qGF3RDjZA3VDrsm:b-kjd8zz) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It might happen that there are more go modules in single repo. Please change the working directory to the package location like here: https://github.com/CoreumFoundation/crust/blob/master/build/go.go#L33

Otherwise you are at risk that package is built using different `go.mod` file that it should.
</blockquote></details>

Dockerfile works with build context, and the build context is set to a go module, not repos. The context is always set to the dir with correct `go.mod` and `go.sum`


<!-- Sent from Reviewable.io -->

2022-07-04 17:09 UTC, oliverasistemas approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @wojtek-coreum and @xlab)



<!-- Sent from Reviewable.io -->

2022-07-04 17:12 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N691AebCFyvjoKqoBvg:b-jmlb5e) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Software is written once by one person. Then it is executed many many times by large number of people. It means that investing a little more time during development it's possible to improve it so all the other people will same hundreds of hours in total during the software lifetime every year.

In this particular case for example it means that go modules required by cored will be downloaded twice during the build: once on host machine to build host-specific binary, second one in docker. You could easily save time of everyone by mounting local `~/go` to the docker container so it reuses modules downloaded previously.

So there are really tiny optimizations which will take you 15 minutes to introduce and will save time to everyone in the future:
- mount ~/go inside container
- mount source code inside container instead of copying it twice during build
- compile code in the container, not during build

It's so simple to do that you used more time to write the comment.

> This PR is related to unblocking the pipeline of myself

This PR introduces new functionality and it would be nice to do it in the way that works nicely for everyone for a long time, because this is how it will be used. It's not a temporary dirty hack to solve temporary problem. It will be with us for a long time so let's add some quality there.

> but at the same time don't think about the prod that will happen very soon.

Once the cgo binary is built by the code introduced by this PR building prod image is as simple as copying the binary to the alpine image, so I definitely think about it now. It just does not need to be done in this PR.
</blockquote></details>

since I'm working on the similar part of crust I suggest we do it there if still applicable
___
*[`build/build.go` line 122 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N692cJ7Aj7jY3COHtQ5:-N692cJ7Aj7jY3COHtQ6:b-lr7vhk) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L122)):*
> ```Go
> 	log.Debug(buildCmd.String())
> 
> 	runCmd := &exec.Cmd{
> ```

I'm just wondering that we run this command here as docker run not as one of steps of build if it supposed

or what is the idea here ?
___
*[`build/docker/Dockerfile.cgo` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68sr296ztEmijvCygC:-N690G5K2w1ojQYtmyy1:bjngij6) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do you copy these two files first, if everything is copied two lines later anyway?
Also keep in mind that not every repo must contain `go.sum` and `go.mod` in the repo root dir.
</blockquote></details>

docker caching works better in this way


<!-- Sent from Reviewable.io -->

2022-07-04 17:30 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N69EUe8A63W3UoH0E8_:b-v0byl4) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

since I'm working on the similar part of crust I suggest we do it there if still applicable
</blockquote></details>

@xlab Could I take this PR from here?
___
*[`build/build.go` line 120 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68r5Mi903A82wBXs3p:-N69EbHJBG5QGS1hCCF9:bkima7t) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L120)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

No, if the app runs with debug logging, it should print commands it executes.
</blockquote></details>

`libexec` does this for you already: https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/libexec/exec.go#L45


<!-- Sent from Reviewable.io -->

2022-07-04 17:51 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 10 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`build/docker/Dockerfile.cgo` line 3 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69KEE2B3Rqi1uWyM-M:-N69KEE2B3Rqi1uWyM-N:bsxawvl) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L3)):*
> ```
> # prepare the building environment
> 
> FROM golang:1.18.3-alpine as builder
> ```

Instead of hardcoding go version here, please put one from here: https://github.com/CoreumFoundation/crust/blob/master/build/tools.go#L26


<!-- Sent from Reviewable.io -->

2022-07-04 18:06 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`build/docker/Dockerfile.cgo` line 8 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69Nv880Wc4hc8i6YV0:-N69Nv880Wc4hc8i6YV1:bxaty6e) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L8)):*
> ```
> RUN set -eux; apk add --no-cache ca-certificates build-base
> 
> ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.a
> ```

Because image is rebuilt every time cgo binary is built, this library is downloaded every time I run `crust build/cored`


<!-- Sent from Reviewable.io -->

2022-07-04 18:10 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`build/docker/Dockerfile.cgo` line 22 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69Otjh0jeKTlMO8SXd:-N69Otjh0jeKTlMO8SXe:brbec8u) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L22)):*
> ```
> # prepare image that exports the bin
> 
> FROM alpine:latest
> ```

Earlier we decided to pin all the docker images we use, so instead of `latest` please specify versioned tag


<!-- Sent from Reviewable.io -->

2022-07-04 18:12 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 13 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`build/docker/Dockerfile.cgo` line 27 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69P9HZCisIwUEDWbx8:-N69P9HZCisIwUEDWbx9:b-k4w5x2) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L27)):*
> ```
> 
> ARG BIN_NAME
> COPY --from=builder /out/${BIN_NAME} /bin/${BIN_NAME}
> ```

You copy binary from one image to another just to start it and copy binary from one folder to another. Could you do it using first image directly?


<!-- Sent from Reviewable.io -->

2022-07-05 00:37 UTC, xlab commented
*[`build/build.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68OGvs7LzL601UHD-V:-N6AmOh82xh3MkAtwPQT:bl2mtkz) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab Could I take this PR from here?
</blockquote></details>

Live rebuilds is a separate feature, if you want, you can rebase the corresponding branch off this one.


<!-- Sent from Reviewable.io -->

2022-07-05 00:38 UTC, xlab commented
*[`build/build.go` line 122 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N692cJ7Aj7jY3COHtQ5:-N6AmbhRA8ER4Fg6CfCh:b-wvtvu5) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L122)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm just wondering that we run this command here as docker run not as one of steps of build if it supposed

or what is the idea here ?
</blockquote></details>

Idea is that to copy the build artifact from the container, you need to run it. It's a docker usage pattern.


<!-- Sent from Reviewable.io -->

2022-07-05 00:41 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 3 of 8 files reviewed, 13 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/build.go` line 80 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68MwlRCsYCTymz1IlP:-N6AmGmE9Pi8YU_ThlwQ:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/build.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the only place to change: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/cored/cored.go#L189
</blockquote></details>

Done.
___
*[`build/build.go` line 95 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68q7HN0lA0EEfx0iL-:-N6AmI_pCyEwe7BQ0-3I:bh46egj) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The assumption made here on the relative path between package location and repo root directory is wrong for generic case.
But you are lucky, `crust` sets working directory to the repo root already so you don't need to do anything special. Docker command will start in this dir by default.
</blockquote></details>

Done. Fixed.
___
*[`build/build.go` line 115 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rMCI9ESpRNtO4cEC:-N6AmJqp4F1CUlwz4NeI:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please add `crust-` prefix to the image name
</blockquote></details>

Done.
___
*[`build/build.go` line 125 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rcdnBWyjs4wyUtWo:-N6AmnD36sdZiiJZVlmU:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please add `--user=os.Getuid():os.Getgid()` option so the built binary is owned by the correct user after copying to filesystem of the host. Or use another mechanism to `chown` it accordingly.
</blockquote></details>

Done.
___
*[`build/build.go` line 132 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68s-J2EMyRHp34Og4q:-N6AmneR2roVpt74r5x0:bss4a2b) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L132)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

No, if the app runs with debug logging, it should print commands it executes.
</blockquote></details>

Removed.
___
*[`build/docker/Dockerfile.cgo` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68RC8SE07B2yMCf1Bz:-N6AnEX2EAiqcw6zbkE2:ba153f) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you have no guarantee that every package will be located under `cmd/bin-name`. Soemtimes it might be just `cmd`, sometimes it might be just the repo root directory. So I see two possibilities:
- make it generic like `goBuildPkg`, by taking a `pkg` argument pointing to the right location
- make it specific to cored

I prefer the first approach so both `goBuildPkg` and `goBuildWithDocker` work the same way with the only difference being the place were binary is built
</blockquote></details>

Implemented the generic approach, which also resolved the problem of finding the module path.
___
*[`build/docker/Dockerfile.cgo` line 3 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69KEE2B3Rqi1uWyM-M:-N6AmpoJCMUUennIXwUy:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Instead of hardcoding go version here, please put one from here: https://github.com/CoreumFoundation/crust/blob/master/build/tools.go#L26
</blockquote></details>

Done.
___
*[`build/docker/Dockerfile.cgo` line 8 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69Nv880Wc4hc8i6YV0:-N6AmqaY8FPtf38fSomL:b967ns1) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because image is rebuilt every time cgo binary is built, this library is downloaded every time I run `crust build/cored`
</blockquote></details>

It's cached really, I suppose this might be a result of turned off BUILDKIT on your docker installation.
I've added an explicit override to enable it (it's enabled by default on newer distros)

![Screenshot 2022-07-05 at 02.13.32.png](https://files.reviewableusercontent.io/images/reviewable/477998/SYB_BYsYoNDzBWRM5kHSNaT8/Screenshot%202022-07-05%20at%2002.13.32.png)

Within BUILDKIT, the remote HTTP headers are respected, and this part is not downloaded every time.
___
*[`build/docker/Dockerfile.cgo` line 22 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69Otjh0jeKTlMO8SXd:-N6AnLDH0rK1ORv_zajY:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Earlier we decided to pin all the docker images we use, so instead of `latest` please specify versioned tag
</blockquote></details>

Done.
___
*[`build/docker/Dockerfile.cgo` line 27 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69P9HZCisIwUEDWbx8:-N6AnM2rEEh0zemr-ZPx:b-w3y2vz) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You copy binary from one image to another just to start it and copy binary from one folder to another. Could you do it using first image directly?
</blockquote></details>

It's a docker pattern, you cannot export any artifacts from the build phase. If you find a way, let me know.


<!-- Sent from Reviewable.io -->

2022-07-05 00:41 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 3 of 8 files reviewed, 13 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/build.go` line 120 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68r5Mi903A82wBXs3p:-N6An_CN5dNRAcNgl9-Q:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`libexec` does this for you already: https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/libexec/exec.go#L45
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 01:49 UTC, xlab reviewed
> Reviewed 3 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 13 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-05 04:00 UTC, wojtek-coreum requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 17 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BR38gDByBcz1dhkjI:-N6BR38h7Iw0pa2Iu2uN:b-c0zcdo) (no related file):*
After your latest changes `crust build/cored` gives me this error:
```
 => ERROR [builder 15/15] RUN echo "Ensuring binary is statically linked ..."   && (file /out/cored | grep "statically linked")                                                                                                                                                                                                                                                          2.4s
------
 > [builder 15/15] RUN echo "Ensuring binary is statically linked ..."   && (file /out/cored | grep "statically linked"):
#27 2.093 Ensuring binary is statically linked ...
------
executor failed running [/bin/sh -c echo "Ensuring binary is statically linked ..."   && (file /out/${BIN_NAME} | grep "statically linked")]: exit code: 1
```

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BSqe16bTs554V-eOn:-N6BSqe16bTs554V-eOo:b-jrjd2r) (no related file):*
I see you added `-static` option to the `go build`. Does it mean that if all libraries are statically linked, the binary file may be safely moved from linux host machine to alpine image without being built inside the container? (Yes, I know that e still need to support macs)

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BTXKV5qgSBCJ0sSL4:-N6BTXKWDzOylvRPvjqp:bz2ielj) (no related file):*
The solution proposed in this PR does not support very important scenario. Let's say I need to modify some external dependency to fix a bug, make temporary change or test the code before opening PR in another repo. Let's take the cosmos SDK as an example.
What I do:

1. Clone the repo: `git clone https://github.com/cosmos/cosmos-sdk.git`
2. Create new branch: `cd cosmos-sdk && git checkout -b test-branch`
3. Modify cosmos-sdk source code
4. Edit coreum's `go.mod` to add: `replace github.com/cosmos/cosmos-sdk => ../cosmos-sdk`
5. Compile cored: `crust build/cored`

Uuups, last step does not work.

___
___
*[`build/docker/Dockerfile.cgo` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BObFx5kVVjIwTjEoq:-N6BObFx5kVVjIwTjEor:b-nyacks) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L14)):*
> ```
> COPY go.mod .
> COPY go.sum .
> RUN go mod download
> ```

This command downloads all the modules instead of reusing what is already available under `$GOPATH` on host.
`docker build` spends ~6 minutes on this line and the job is repeated whenever `go.mod` is changed (so every time dependency is added, removed or replaced).
___
*[`build/docker/Dockerfile.cgo` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BP83UEnxeNmTnxv0k:-N6BP83V8Ehj4bbXUJ04:b-jxyhg9) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L18)):*
> ```
> 
> ARG BIN_NAME
> RUN CGO_ENABLED=1 LEDGER_ENABLED=false BUILD_TAGS=muslc go build -trimpath -ldflags="-w -s" -o /out/${BIN_NAME} ./cmd/${BIN_NAME}
> ```

This command does not preserve cached binaries stored by `go` inside `$GOCACHE` between two consecutive builds, causing entire process to be much much longer. `docker build` spends ~4 minutes here each time source code is changed.


<!-- Sent from Reviewable.io -->

2022-07-05 04:35 UTC, wojtek-coreum requested changes
> Reviewed 3 of 5 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6BZLIB46U0W0v0NRus:b-60oqx7) (no related file):*
Please look at this entire problem from different perspective.
You could take `Dockerfile` like this:

```
ARG GO_VERSION
FROM golang:${GO_VERSION}-alpine3.16 as builder

RUN apk add --no-cache git gcc make libc-dev linux-headers
RUN set -eux; apk add --no-cache ca-certificates build-base

# See https://github.com/CosmWasm/wasmvm/releases
ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.aarch64.a /lib/libwasmvm_muslc.aarch64.a
ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.x86_64.a
RUN sha256sum /lib/libwasmvm_muslc.aarch64.a | grep 7d2239e9f25e96d0d4daba982ce92367aacf0cbd95d2facb8442268f2b1cc1fc
RUN sha256sum /lib/libwasmvm_muslc.x86_64.a | grep f6282df732a13dec836cda1f399dd874b1e3163504dbd9607c6af915b2740479

ARG TARGET_ARCH
RUN cp /lib/libwasmvm_muslc.${TARGET_ARCH}.a /lib/libwasmvm_muslc.a
ENTRYPOINT "go"
```

build the image if it doesn't exist, and then run it this way:

```
docker run
  -v absolutePathTo(".."):/src
  -v $HOME/go:/go
  -v /path/to/cache:/go-build
  --env GOPATH=/go
  --env GOCACHE=/go-build
  --workdir=/src/crust/+pkgPath
  --user=os.Getuid():os.Getgid()
image-name
build [all-the-magic-flags] -o /src/crust/bin/alpine-cgo/bin-name .
```

By doing it this way all the problems I mention in all the comments inside this PR are fixed instantly.
Dependencies are not redownloaded and rebuilds are faster.

@ysv You might also be interested

___
___
*[`build/build.go` line 78 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BWKuJ57SUEcbK-M9d:-N6BWKuJ57SUEcbK-M9e:bcjd1k) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/build.go#L78)):*
> ```Go
> 	if cgoEnabled {
> 		// docker-targeted cgo-enabled binary must be built from within Docker environment
> 		return goBuildWithDocker(ctx, pkg, filepath.Join(dir, "muslc"), binName)
> ```

Could `muslc` be renamed to sth like `alpine-cgo`? `muslc` is not so self-explaining name.
___
*[`build/docker/Dockerfile.cgo` line 27 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N69P9HZCisIwUEDWbx8:-N6Bbnz-9YXc1ay9P6Ga:b-4okmsg) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/docker/Dockerfile.cgo#L27)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's a docker pattern, you cannot export any artifacts from the build phase. If you find a way, let me know.
</blockquote></details>

An alternative solution is described in one of the comments on top of the PR
___
*[`build/docker/Dockerfile.cgo` line 12 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6Bas2E2pYENZ79eUNB:-N6Bas2E2pYENZ79eUNC:bu3mn8x) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/docker/Dockerfile.cgo#L12)):*
> ```
> 
> # See https://github.com/CosmWasm/wasmvm/releases
> ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.aarch64.a /lib/libwasmvm_muslc.aarch64.a
> ```

Could you download only the version which is needed for the TARGET_ARCH?


<!-- Sent from Reviewable.io -->

2022-07-05 04:38 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6Bdafy56nS58RY9xE6:b-7rl5kr) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please look at this entire problem from different perspective.
You could take `Dockerfile` like this:

```
ARG GO_VERSION
FROM golang:${GO_VERSION}-alpine3.16 as builder

RUN apk add --no-cache git gcc make libc-dev linux-headers
RUN set -eux; apk add --no-cache ca-certificates build-base

# See https://github.com/CosmWasm/wasmvm/releases
ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.aarch64.a /lib/libwasmvm_muslc.aarch64.a
ADD https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.x86_64.a
RUN sha256sum /lib/libwasmvm_muslc.aarch64.a | grep 7d2239e9f25e96d0d4daba982ce92367aacf0cbd95d2facb8442268f2b1cc1fc
RUN sha256sum /lib/libwasmvm_muslc.x86_64.a | grep f6282df732a13dec836cda1f399dd874b1e3163504dbd9607c6af915b2740479

ARG TARGET_ARCH
RUN cp /lib/libwasmvm_muslc.${TARGET_ARCH}.a /lib/libwasmvm_muslc.a
ENTRYPOINT "go"
```

build the image if it doesn't exist, and then run it this way:

```
docker run
  -v absolutePathTo(".."):/src
  -v $HOME/go:/go
  -v /path/to/cache:/go-build
  --env GOPATH=/go
  --env GOCACHE=/go-build
  --workdir=/src/crust/+pkgPath
  --user=os.Getuid():os.Getgid()
image-name
build [all-the-magic-flags] -o /src/crust/bin/alpine-cgo/bin-name .
```

By doing it this way all the problems I mention in all the comments inside this PR are fixed instantly.
Dependencies are not redownloaded and rebuilds are faster.

@ysv You might also be interested
</blockquote></details>

Missed some args in `docker run`, more complete version:
```
docker run
  -v absolutePathTo(".."):/src
  -v $HOME/go:/go
  -v /path/to/cache:/go-build
  --env GOPATH=/go
  --env GOCACHE=/go-build
  --env CGO_ENABLED=1
  --workdir=/src/crust/+pkgPath
  --user=os.Getuid():os.Getgid()
  --rm
image-name
build [all-the-magic-flags] -o /src/crust/bin/alpine-cgo/bin-name .
```

But I'm sure you get the idea.

___


<!-- Sent from Reviewable.io -->

2022-07-05 09:01 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BSqe16bTs554V-eOn:-N6C_ERq4DFil9PLlB13:bb9i0ha) (no related file):*
>  without being built inside

we build inside because it uses `aarch64-alpine-linux-musl/bin/ld`




<!-- Sent from Reviewable.io -->

2022-07-05 09:02 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BR38gDByBcz1dhkjI:-N6C_zN2C35vSYje90gG:b-76s708) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After your latest changes `crust build/cored` gives me this error:
```
 => ERROR [builder 15/15] RUN echo "Ensuring binary is statically linked ..."   && (file /out/cored | grep "statically linked")                                                                                                                                                                                                                                                          2.4s
------
 > [builder 15/15] RUN echo "Ensuring binary is statically linked ..."   && (file /out/cored | grep "statically linked"):
#27 2.093 Ensuring binary is statically linked ...
------
executor failed running [/bin/sh -c echo "Ensuring binary is statically linked ..."   && (file /out/${BIN_NAME} | grep "statically linked")]: exit code: 1
```
</blockquote></details>

I have to remove this check, as it works unreliably, we don't really need it, even `-static` flag was extra, it works either way.




<!-- Sent from Reviewable.io -->

2022-07-05 09:03 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BTXKV5qgSBCJ0sSL4:-N6CaE1t6rhM1U5AsMWo:b-6o3aso) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The solution proposed in this PR does not support very important scenario. Let's say I need to modify some external dependency to fix a bug, make temporary change or test the code before opening PR in another repo. Let's take the cosmos SDK as an example.
What I do:

1. Clone the repo: `git clone https://github.com/cosmos/cosmos-sdk.git`
2. Create new branch: `cd cosmos-sdk && git checkout -b test-branch`
3. Modify cosmos-sdk source code
4. Edit coreum's `go.mod` to add: `replace github.com/cosmos/cosmos-sdk => ../cosmos-sdk`
5. Compile cored: `crust build/cored`

Uuups, last step does not work.
</blockquote></details>

Why it doesn't work, did you try it?




<!-- Sent from Reviewable.io -->

2022-07-05 09:03 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6CaRbx3b9GyWJffR4V:b-d2vbum) (no related file):*
> By doing it this way all the problems

Which problems tho?




<!-- Sent from Reviewable.io -->

2022-07-05 09:06 UTC, xlab commented
*[`build/docker/Dockerfile.cgo` line 12 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6Bas2E2pYENZ79eUNB:-N6Cb0Jm-277XVqUf5Zp:b-5imwma) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/docker/Dockerfile.cgo#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you download only the version which is needed for the TARGET_ARCH?
</blockquote></details>

I'd like to avoid using bash scripting in Dockerfiles and add dynamic conditions. However, both binaries are cached in layers, so it's not a problem in subsequential builds.



_Code quote:_
```
https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.x86_64.a
```


<!-- Sent from Reviewable.io -->

2022-07-05 09:12 UTC, xlab commented
*[`build/docker/Dockerfile.cgo` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BObFx5kVVjIwTjEoq:-N6CbFCFC0nmYCfoQGO5:b7vrqe5) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This command downloads all the modules instead of reusing what is already available under `$GOPATH` on host.
`docker build` spends ~6 minutes on this line and the job is repeated whenever `go.mod` is changed (so every time dependency is added, removed or replaced).
</blockquote></details>

Do we often replace dependencies in `go.mod`?

Btw, that's a good consideration when implementing a live rebuild image.


<!-- Sent from Reviewable.io -->

2022-07-05 09:17 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BTXKV5qgSBCJ0sSL4:-N6CbXav90S4v87ak2Io:bgghbr1) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Why it doesn't work, did you try it?
</blockquote></details>

Because you send only the specific module to `docker build` context. To make it work you would need to send parent directory of `crust` which would be really bad idea. That's why I'm proposing a solution which doesn't use `docker build` to run `go build`.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BSqe16bTs554V-eOn:-N6CcqhNAIt2m_C7f8hY:bw48dam) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

>  without being built inside

we build inside because it uses `aarch64-alpine-linux-musl/bin/ld`
</blockquote></details>

But if I'm on linux amd64, should statically linked binary work out of the box after being moved to alpine container?

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6Cc-F1AmBD0NZ-BIiz:b-4u81nz) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> By doing it this way all the problems

Which problems tho?
</blockquote></details>

Look at all my comments in this PR

___
___
*[`build/build.go` line 125 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rcdnBWyjs4wyUtWo:-N6Ccgxk2KKzM2bjQ9p5:b-6aoofj) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L125)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now `crust build/cored` fails with
```
cp: can't create '/mnt/cored': Permission denied
```
___
*[`build/docker/Dockerfile.cgo` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BObFx5kVVjIwTjEoq:-N6CcTPuDgDtK7VBloDE:b-u2880m) ([raw file](https://github.com/coreumfoundation/crust/blob/d38d638bf827435ff9d19484a428c90b861cff25/build/docker/Dockerfile.cgo#L14)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Do we often replace dependencies in `go.mod`?

Btw, that's a good consideration when implementing a live rebuild image.

</blockquote></details>

Yes, we do it often
___
*[`build/docker/Dockerfile.cgo` line 12 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6Bas2E2pYENZ79eUNB:-N6CcGSP8jHaadSnYE3M:b-6mxwra) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/docker/Dockerfile.cgo#L12)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I'd like to avoid using bash scripting in Dockerfiles and add dynamic conditions. However, both binaries are cached in layers, so it's not a problem in subsequential builds.
</blockquote></details>

You could store links and checksums in `go` and pass only the required one to `docker build`
___
*[`build/docker/Dockerfile.cgo` line 29 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6CaeC15r_TDpORw7pX:-N6CaeC2DfUIsdGv8QWL:bmfvpte) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/docker/Dockerfile.cgo#L29)):*
> ```
> ARG BIN_PACKAGE
> 
> RUN CGO_ENABLED=1 LEDGER_ENABLED=false go build -tags=muslc -ldflags="-extldflags=-static" -trimpath -o /out/${BIN_NAME} ${BIN_PACKAGE}
> ```

Is the `-static` flag needed? Does it do anything useful? If not, it probably only makes binary file larger and compilation slower


<!-- Sent from Reviewable.io -->

2022-07-05 09:19 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BTXKV5qgSBCJ0sSL4:-N6Ce-K08W4nFopWuNJf:bkrbtd8) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because you send only the specific module to `docker build` context. To make it work you would need to send parent directory of `crust` which would be really bad idea. That's why I'm proposing a solution which doesn't use `docker build` to run `go build`.
</blockquote></details>

Makes sense too.

___


<!-- Sent from Reviewable.io -->

2022-07-05 09:19 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BSqe16bTs554V-eOn:-N6Ce5BhA9qP2z9ZebtF:b-6rk9bp) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But if I'm on linux amd64, should statically linked binary work out of the box after being moved to alpine container?
</blockquote></details>

Try it out.

___


<!-- Sent from Reviewable.io -->

2022-07-05 09:20 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6Ce9mgBiEQlmnNEeXL:byv7ytf) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Okay, I think the real problem that affects performance is the `go download` step upon `go.mod` change and also `GOCACHE` upon rebuilding. Latter I cannot test really, it takes about 30s to compile for me
</blockquote></details>

+ the ability to reference modules from separate repositories




<!-- Sent from Reviewable.io -->

2022-07-05 09:20 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 11 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6Ce9A25gGfx3GwBC_6:b-rdiq28) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Okay, I think the real problem that affects performance is the `go download` step upon `go.mod` change and also `GOCACHE` upon rebuilding. Latter I cannot test really, it takes about 30s to compile for me
</blockquote></details>

30s to rebuild after a simple code editing is too long anyway

___


<!-- Sent from Reviewable.io -->

2022-07-05 12:15 UTC, xlab commented
*[`build/docker/Dockerfile.cgo` line 29 at r8](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6CaeC15r_TDpORw7pX:-N6DHD5D5xlV8Xe8EGYc:b-gesa3w) ([raw file](https://github.com/coreumfoundation/crust/blob/35f6135abbce84f3c713bd7914bcf8d274f4a12b/build/docker/Dockerfile.cgo#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is the `-static` flag needed? Does it do anything useful? If not, it probably only makes binary file larger and compilation slower
</blockquote></details>

It doesn't do anything useful, we can skip it. In most examples for wasmvm the static build is forced, but I think it worked fine without that explicit flag.


<!-- Sent from Reviewable.io -->

2022-07-05 12:18 UTC, xlab commented
*[`build/build.go` line 125 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rcdnBWyjs4wyUtWo:-N6DH7dVB02KseAB7VJ1:b-s7ygh2) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now `crust build/cored` fails with
```
cp: can't create '/mnt/cored': Permission denied
```
</blockquote></details>

I cannot reproduce this tho. I think you should take this PR from this point and implement your own changes because they are 100% about issues on linux and your machine.


<!-- Sent from Reviewable.io -->

2022-07-05 12:18 UTC, xlab commented
*[`build/build.go` line 125 at r6](https://reviewable.io/reviews/coreumfoundation/crust/5#-N68rcdnBWyjs4wyUtWo:-N6DHyzX3s6ER5Gd4h6V:boadm57) ([raw file](https://github.com/coreumfoundation/crust/blob/39f1b1b5d12c2f2c1a9f4c91507b8f421a3f8941/build/build.go#L125)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I cannot reproduce this tho. I think you should take this PR from this point and implement your own changes because they are 100% about issues on linux and your machine.
</blockquote></details>

You can also make dockerfile nicer and convert it to runner version if that makes rebuilding faster. But don't forget to coordinate with @ysv so he could reuse it for live reloading as well.


<!-- Sent from Reviewable.io -->

2022-07-05 14:13 UTC, wojtek-coreum reviewed
> Reviewed 4 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-05 14:16 UTC, wojtek-coreum reviewed
> Reviewed 3 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-07-05 17:19 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-07-06 05:49 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-07-06 11:02 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6I8JHJ68hiWfto-f3p:buvza5o) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I've made a simple performance evaluation of the new solution:
https://gist.github.com/xlab/b5fba50f10070b80fb0d44e6bce2c01a

5x performance degrade when there is no changes to the code
1x performance improvement when there is a change to the code.

Is this PR finished or there are other improvements planned?  Because we spent like 2 days improving nothing at this point.
</blockquote></details>

What I see is that results in your `docker_run.log` are actually better than the ones in `docker_cached_build.log`. Times are shorter but what's even more important CPU load is many times lower.

From my PoV this PR is ready.

___


<!-- Sent from Reviewable.io -->

2022-07-06 11:03 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IAPYi5De6uDrpCl1Z:bc6azsx) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What I see is that results in your `docker_run.log` are actually better than the ones in `docker_cached_build.log`. Times are shorter but what's even more important CPU load is many times lower.

From my PoV this PR is ready.
</blockquote></details>

ah sorry, cpu is higher - it's the next number

___


<!-- Sent from Reviewable.io -->

2022-07-06 11:06 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IAnLu3mJkY56uVaSt:b-re7eiq) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ah sorry, cpu is higher - it's the next number
</blockquote></details>

I guess cpu spends time on checking cache but if your mac is really able to recompile `cored` from scratch in 4 seconds then it means your box is a piece of magic

___


<!-- Sent from Reviewable.io -->

2022-07-06 11:22 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IEa4hEC9AOi64vx7L:bic8sqy) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I guess cpu spends time on checking cache but if your mac is really able to recompile `cored` from scratch in 4 seconds then it means your box is a piece of magic
</blockquote></details>

I don't care about internal CPU numbers, I just measure the user time for overall compilation.
My magic box spends 25s on your branch where no code has been changed.




<!-- Sent from Reviewable.io -->

2022-07-06 11:27 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IFlOe0rzSEhOSUlLg:bnvimau) (no related file):*
>  really able to recompile cored from scratch in 4 seconds then it means your box is a piece of magic

It's not from scratch, it's recompilation without changes. From scratch, it takes 45 seconds which is on par. So no improvement.




<!-- Sent from Reviewable.io -->

2022-07-06 11:54 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IM34R48KpD-8M49r2:bcz4z6) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

>  really able to recompile cored from scratch in 4 seconds then it means your box is a piece of magic

It's not from scratch, it's recompilation without changes. From scratch, it takes 45 seconds which is on par. So no improvement.
</blockquote></details>

@xlab These are my results. No code changes, time taken on second compilation (warm cache):

```
# docker build

real	5m14.168s
user	0m11.312s
sys	0m5.908s

# docker run

real	0m11.777s
user	0m7.474s
sys	0m2.584s
```

___


<!-- Sent from Reviewable.io -->

2022-07-06 12:06 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IO-7HAlSGIeNYYziC:bpgetzv) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab These are my results. No code changes, time taken on second compilation (warm cache):

```
# docker build

real	5m14.168s
user	0m11.312s
sys	0m5.908s

# docker run

real	0m11.777s
user	0m7.474s
sys	0m2.584s
```
</blockquote></details>

This is weird, I wonder where 5 extra minutes come from. You'll need to show me this on the call later.




<!-- Sent from Reviewable.io -->

2022-07-06 12:07 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IOLuU1bN20cyfHKs_:bstdrqj) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This is weird, I wonder where 5 extra minutes come from. You'll need to show me this on the call later.
</blockquote></details>

@xlab The high time I got for `docker build` was a suspicious to me because it rebuilt binary from source despite the fact I haven't modified the source. I repeated the experiment with Goland IDE closed. These are the results I got:

```
# docker build

real	0m26.460s
user	0m8.921s
sys	0m3.554s

# docker run

real	0m14.941s
user	0m8.573s
sys	0m3.295s
```

So now they seem to be correct. Code was not recompiled. What I see here is that:
- on linux `docker run` is still twice faster than `docker build`
- on your mac `docker build` is faster because it takes the cached layer from docker because code hasn't changed, while `docker run` still runs `go build`

___


<!-- Sent from Reviewable.io -->

2022-07-06 12:14 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6IQapE04COFPnLgI3O:b-wdjiwo) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So looks like Golang IDE modifies something on filesystem all the time causing recompilation to be done every time by `docker build`
</blockquote></details>

The most important part is that when code is modified `docker build` takes 5 minutes to recompile, while `docker run` takes 21 seconds

___


<!-- Sent from Reviewable.io -->

2022-07-06 15:22 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6BZLIB46U0W0v0NRur:-N6J5ayBAfr3cqQqcJc0:b-f1z078) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now I removed GOCACHE used by `docker run` to create the same condition for both environments and it took 3 minutes to recompile with cold cache. So it's still 40% faster than `docker build`
</blockquote></details>

@xlab could you unblock it please?

___


<!-- Sent from Reviewable.io -->

2022-07-07 13:12 UTC, xlab commented
*[`build/build.go` line 71 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6N9nTk87KoEC5aaTjx:-N6NmKTW4_X7IuTSLN7A:bewx2ah) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/build.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it should error out if none of the if conditions above are matched. 
</blockquote></details>

If cgo is not enabled, and  runtime.GOOS == dockerGOOS, that means the binary compiled by the host compiler (see above `goBuildPkg`) can be used inside Docker as-is.


<!-- Sent from Reviewable.io -->

2022-07-07 13:53 UTC, oliverasistemas approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-07 13:54 UTC, miladz68 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5#-:-N6Nw5YgAwqqsOV1tCYz:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-07-08 12:05 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/build.go` line 36 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SIOzD0Q5DJ9ewDOvd:-N6SgJi-0jvv1W-jFckN:b-feefig) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/build.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need to build Native and Docker for Zstress ?
</blockquote></details>

Yes, benchmarks are deployed by Artem's terraform magic using docker so zstress must run in docker
___
*[`build/go.go` line 120 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SH3Ro4uRYFnJvHDqa:-N6Sgaq0-3DB8RA1wVW-:b-gj64rr) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: we already have tooling for dependencies management defined in `tools.go`
we might not want to install docker from there but I would prefer to have this checks in a single place. Do you think it is possible ?
</blockquote></details>

It's completely different logic. The only thing I can do is to encapsulate it into function checking if particular binary is available in PATH


<!-- Sent from Reviewable.io -->

2022-07-08 12:09 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 91 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SOXL7EQAJp5ecYMwe:-N6She0j6KKrp4L7n0zn:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

specific error here ? smth like "failed to execute dockerfile template"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 12:15 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 147 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQi12BXZ5QtFODK6Q:-N6SiIqF0SqYQdA9VEkd:bg97gs5) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L147)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you explain this pls
do we mount whole src from local to a container ?
</blockquote></details>

yes, to support cases when someone might want to use `replace` directive in `go.mod` like this:
```
replace github.com/cosmos/cosmos-sdk => ../cosmos-sdk
```
to test bugfixes or some other changes made to external module.
If only `crust` repo is mounted to docker container it won't work.
___
*[`build/go.go` line 154 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQSAX3Hw9lc9c7lZy:-N6Siz3Z-hc93t7VKG51:bqudwni) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L154)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we use local OS user & group inside Docker ?
</blockquote></details>

Otherwise binary produced by docker is owned by `root` on host system, so user is not able to delete it


<!-- Sent from Reviewable.io -->

2022-07-08 12:21 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 147 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQi12BXZ5QtFODK6Q:-N6SjoA53YWxQmyBalTP:b-xon8ls) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, to support cases when someone might want to use `replace` directive in `go.mod` like this:
```
replace github.com/cosmos/cosmos-sdk => ../cosmos-sdk
```
to test bugfixes or some other changes made to external module.
If only `crust` repo is mounted to docker container it won't work.
</blockquote></details>

makes sense
but it mounts `..` from crust dir which is `src/github.com/CoreumFoundation` (correct me if I'm wrong)

do we wnt to mount only CoreumFoundation ?
___
*[`build/go.go` line 154 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQSAX3Hw9lc9c7lZy:-N6SkMfDCbZRQMdDd2gd:bwk9mg2) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L154)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Otherwise binary produced by docker is owned by `root` on host system, so user is not able to delete it
</blockquote></details>

ok
but it is another consequence of sharing docker image between docker and locally


<!-- Sent from Reviewable.io -->

2022-07-08 12:27 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 147 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQi12BXZ5QtFODK6Q:-N6SlAIeBEu6ar52Kbs0:b-obpgt7) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L147)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

makes sense
but it mounts `..` from crust dir which is `src/github.com/CoreumFoundation` (correct me if I'm wrong)

do we wnt to mount only CoreumFoundation ?

</blockquote></details>

it depends on how you structured directories on your machine. For example, in this case I keep all the sources inside `$HOME`. I assumed that whatever repos we work with in this project are in the same parent directory. I have to assume sth because otherwise I would have to mount`/`, which I would like to prevent.
___
*[`build/go.go` line 154 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQSAX3Hw9lc9c7lZy:-N6SlhEl2ucSbhEytG9C:b2nign6) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L154)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
but it is another consequence of sharing docker image between docker and locally
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-07-08 12:36 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 147 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQi12BXZ5QtFODK6Q:-N6Sn14y1_ivuCySnP0s:bus0sll) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it depends on how you structured directories on your machine. For example, in this case I keep all the sources inside `$HOME`. I assumed that whatever repos we work with in this project are in the same parent directory. I have to assume sth because otherwise I would have to mount`/`, which I would like to prevent.
</blockquote></details>

mounting whole / is definitely not a way
but in your case you mount whole `$HOME` don't you ? 
I would prevent mountign whole HOME also

what is more this will not work for me because I keep repos structured differently

another question is do you mean that you keep coreum, crust, cosmos-sdk all in the same folder directly in home ?


<!-- Sent from Reviewable.io -->

2022-07-08 12:39 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`build/go.go` line 147 at r16](https://reviewable.io/reviews/coreumfoundation/crust/5#-N6SQi12BXZ5QtFODK6Q:-N6SnwOx-tx0ucIb12qd:bdm92nz) ([raw file](https://github.com/coreumfoundation/crust/blob/eec4072217826a6545bb25de3ea5c5cf1f6b9081/build/go.go#L147)):*
I mount $HOME - because the code is almost the only thing I keep there. And I run it inside VM so I really don't care.
I could easily isolate it in a subdirectory, but I don't need it.

> what is more this will not work for me because I keep repos structured differently

I could mount entire `$HOME` for everyone but I dont't think it's a good idea.

> another question is do you mean that you keep coreum, crust, cosmos-sdk all in the same folder directly in home ?

yes, if I want to make some temporary changes to some external repo I just clone it to `$HOME`


<!-- Sent from Reviewable.io -->

2022-07-08 14:26 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xlab)



<!-- Sent from Reviewable.io -->

2022-07-08 14:26 UTC, merged